package middleware

import (
	"context"
	"net/http"
	"net/http/httptest"
	"strings"
	"testing"
)

// TestCSRF_GetReplacesStaleCookie pins the post-restart bug:
//
// 1. Process A mints a cookie signed by keyA.
// 2. Process B (after restart) has keyB only — keyA is GONE, not even in
//    AdditionalKeys.
// 3. The browser still sends the keyA cookie on the next GET.
//
// Old behavior: GET path reuses the existing cookie verbatim (csrf.go:195),
// stashes the stale value on ctx, and the rendered form's hidden _csrf
// input carries it. The POST then double-submits a value that cannot
// verify under keyB → 403. The user sees a "session expired" page after
// every deploy.
//
// Fixed behavior: GET must validate the existing cookie's signature
// against the current key set; if invalid, re-mint and overwrite.
func TestCSRF_GetReplacesStaleCookie(t *testing.T) {
	oldKey := mustRandomKey()
	newKey := mustRandomKey()

	// Step 1: mint a cookie under the OLD key (simulates pre-restart).
	mwOld := CSRF(CSRFConfig{SecretKey: oldKey, FormField: "_csrf"})
	primeRec := httptest.NewRecorder()
	mwOld(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {})).
		ServeHTTP(primeRec, httptest.NewRequest(http.MethodGet, "/", nil))
	var staleCookie *http.Cookie
	for _, c := range primeRec.Result().Cookies() {
		if c.Name == "csrf_token" {
			staleCookie = c
		}
	}
	if staleCookie == nil {
		t.Fatal("setup: no stale cookie minted")
	}

	// Step 2: NEW middleware — only newKey, oldKey is dropped entirely
	// (e.g. operator forgot to put it in AdditionalKeys, or the previous
	// process used an autogenerated per-process key that's now gone).
	mwNew := CSRF(CSRFConfig{SecretKey: newKey, FormField: "_csrf"})

	// Step 3: GET request carrying the stale cookie. The middleware must
	// NOT reuse it — it must mint a fresh cookie signed by newKey AND
	// stash the new value on ctx for the form helper to render.
	var ctxToken string
	getReq := httptest.NewRequest(http.MethodGet, "/form", nil)
	getReq.AddCookie(staleCookie)
	getRec := httptest.NewRecorder()
	mwNew(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		ctxToken = TokenFromContext(r.Context())
	})).ServeHTTP(getRec, getReq)

	// Find what the middleware put in Set-Cookie. With the bug, NONE is
	// set (it reused the stale one); after the fix, a fresh cookie is set.
	var setCookie *http.Cookie
	for _, c := range getRec.Result().Cookies() {
		if c.Name == "csrf_token" {
			setCookie = c
		}
	}
	if setCookie == nil {
		t.Fatal("stale cookie was reused on GET — middleware never re-minted (Set-Cookie absent)")
	}
	if setCookie.Value == staleCookie.Value {
		t.Fatal("stale cookie value preserved — middleware did not regenerate")
	}
	if !verifySignedCSRFToken(setCookie.Value, newKey) {
		t.Fatalf("freshly minted cookie does not verify under new primary key: %q", setCookie.Value)
	}

	// Ctx token must match the new cookie (form helper reads ctx).
	if ctxToken != setCookie.Value {
		t.Errorf("ctx token (%q) != Set-Cookie value (%q)", ctxToken, setCookie.Value)
	}

	// Step 4: simulate the user submitting the form with the new token
	// (browser will have updated to the new Set-Cookie). POST must succeed.
	postReq := httptest.NewRequest(http.MethodPost, "/save",
		strings.NewReader("_csrf="+setCookie.Value))
	postReq.Header.Set("Content-Type", "application/x-www-form-urlencoded")
	postReq.AddCookie(setCookie)
	postRec := httptest.NewRecorder()
	mwNew(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.WriteHeader(http.StatusOK)
	})).ServeHTTP(postRec, postReq)
	if postRec.Code != http.StatusOK {
		t.Errorf("post-restart form submit failed: status=%d body=%s",
			postRec.Code, postRec.Body.String())
	}
}

// TestCSRF_GetReplacesMalformedCookie pins the same fix for cookies that
// aren't even shaped like signed tokens — truncated, tampered, missing
// the "." separator, etc. Reusing them would produce a form whose POST
// is guaranteed to 403.
func TestCSRF_GetReplacesMalformedCookie(t *testing.T) {
	key := mustRandomKey()
	mw := CSRF(CSRFConfig{SecretKey: key, FormField: "_csrf"})

	for _, val := range []string{
		"",                                  // empty
		"not-a-token",                       // no separator
		"abc.def",                           // separator but bogus HMAC
		strings.Repeat("a", 64) + ".sig",    // shaped but wrong
		".",                                 // degenerate
	} {
		t.Run(val, func(t *testing.T) {
			req := httptest.NewRequest(http.MethodGet, "/", nil)
			req.AddCookie(&http.Cookie{Name: "csrf_token", Value: val})
			rec := httptest.NewRecorder()

			var ctxToken string
			mw(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
				ctxToken = TokenFromContext(r.Context())
			})).ServeHTTP(rec, req)

			var set *http.Cookie
			for _, c := range rec.Result().Cookies() {
				if c.Name == "csrf_token" {
					set = c
				}
			}
			if set == nil {
				t.Fatalf("malformed cookie %q reused — no Set-Cookie emitted", val)
			}
			if !verifySignedCSRFToken(set.Value, key) {
				t.Fatalf("re-minted cookie does not verify under current key: %q", set.Value)
			}
			if ctxToken != set.Value {
				t.Errorf("ctx token diverged from Set-Cookie: %q vs %q", ctxToken, set.Value)
			}
		})
	}
}

// TestCSRF_GetPreservesValidCookie guards the happy path: the fix must
// NOT re-mint when the existing cookie is still valid (under primary OR
// any rotation key). Otherwise every GET would burn a fresh cookie,
// which is wasteful and would break sticky CSRF flows.
func TestCSRF_GetPreservesValidCookie(t *testing.T) {
	oldKey := mustRandomKey()
	newKey := mustRandomKey()

	// Mint under oldKey.
	mwOld := CSRF(CSRFConfig{SecretKey: oldKey, FormField: "_csrf"})
	primeRec := httptest.NewRecorder()
	mwOld(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {})).
		ServeHTTP(primeRec, httptest.NewRequest(http.MethodGet, "/", nil))
	var validCookie *http.Cookie
	for _, c := range primeRec.Result().Cookies() {
		if c.Name == "csrf_token" {
			validCookie = c
		}
	}
	if validCookie == nil {
		t.Fatal("setup: no cookie minted")
	}

	// Rolling deploy: newKey is primary, oldKey is in AdditionalKeys.
	// The existing oldKey-signed cookie is STILL VALID, so the middleware
	// should reuse it on GET (not churn the cookie every page load).
	mwNew := CSRF(CSRFConfig{
		SecretKey:      newKey,
		AdditionalKeys: [][]byte{oldKey},
		FormField:      "_csrf",
	})
	getReq := httptest.NewRequest(http.MethodGet, "/", nil)
	getReq.AddCookie(validCookie)
	getRec := httptest.NewRecorder()
	var ctxToken string
	mwNew(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		ctxToken = TokenFromContext(r.Context())
	})).ServeHTTP(getRec, getReq)

	// No Set-Cookie expected — the existing one verifies.
	for _, c := range getRec.Result().Cookies() {
		if c.Name == "csrf_token" {
			t.Errorf("middleware re-minted a still-valid cookie (old=%q new=%q)",
				validCookie.Value, c.Value)
		}
	}
	if ctxToken != validCookie.Value {
		t.Errorf("ctx token diverged from existing valid cookie: ctx=%q cookie=%q",
			ctxToken, validCookie.Value)
	}
}

// TestCSRF_GetNestedCtxStillShortCircuits guards the nested-instance
// guard at csrf.go:190. If an outer CSRF middleware already stashed a
// token on ctx, the inner one must NOT re-mint or emit a duplicate
// Set-Cookie — even with the new "validate before reuse" logic.
func TestCSRF_GetNestedCtxStillShortCircuits(t *testing.T) {
	key := mustRandomKey()
	mw := CSRF(CSRFConfig{SecretKey: key, FormField: "_csrf"})

	req := httptest.NewRequest(http.MethodGet, "/", nil)
	// Outer middleware planted a token on ctx; whatever it was, the
	// inner instance must defer to it.
	req = req.WithContext(context.WithValue(req.Context(), csrfTokenCtxKey{}, "outer-token"))
	// Add a stale cookie too — the inner instance must NOT touch it.
	req.AddCookie(&http.Cookie{Name: "csrf_token", Value: "stale-and-bogus"})

	rec := httptest.NewRecorder()
	mw(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {})).
		ServeHTTP(rec, req)

	for _, c := range rec.Result().Cookies() {
		if c.Name == "csrf_token" {
			t.Errorf("nested CSRF emitted a Set-Cookie despite outer ctx token present: %q", c.Value)
		}
	}
}
