package ecommerce_test

import (
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"
)

// scratchPkg is the throwaway package the blueprint is generated into.
//
// It lives inside the repo module so the generated code's self-imports
// (github.com/DonaldMurillo/gofastr/examples/ecommerce/<scratchPkg>/entities)
// resolve without a go.mod, a replace directive, or a network fetch — the same
// arrangement examples/meridian/blueprint_gate_test.go uses. Gitignored, and
// removed before and after the run so a killed test cannot leave a package
// behind that later trips `go build ./...`.
const scratchPkg = "blueprintgen"

// realModule is the module path the committed app/ is generated under. The
// scratch copy appends scratchPkg to it, and normalizeModule below undoes that
// rewrite so generated output can be compared to the committed files.
const realModule = "github.com/DonaldMurillo/gofastr/examples/ecommerce"

// generateShopfront runs the in-tree generator against gofastr.yml, emitting
// into a gitignored scratch package, and returns its absolute path.
//
// It used to run with --force in the repo directory, which rewrote the tracked
// examples/ecommerce/app/ on every suite run (#176). Building fresh generator
// output is the right thing to test; writing it over the committed copy is
// what caused the trouble — a full suite left the tree dirty, and the drift it
// papered over was invisible until someone looked at a diff.
func generateShopfront(t *testing.T) string {
	t.Helper()

	dir, err := filepath.Abs(scratchPkg)
	if err != nil {
		t.Fatalf("abs %s: %v", scratchPkg, err)
	}
	if err := os.RemoveAll(dir); err != nil {
		t.Fatalf("clear stale %s: %v", scratchPkg, err)
	}
	if err := os.MkdirAll(dir, 0o755); err != nil {
		t.Fatalf("mkdir %s: %v", scratchPkg, err)
	}
	t.Cleanup(func() { _ = os.RemoveAll(dir) })

	// Copy the blueprint in, repointing module at the scratch package so the
	// generated self-imports resolve to the code just emitted rather than to
	// the committed package next door, and flattening output_dir so the app
	// lands directly in the scratch package.
	src, err := os.ReadFile("gofastr.yml")
	if err != nil {
		t.Fatalf("read gofastr.yml: %v", err)
	}
	blueprint := string(src)
	moduleLine := "module: " + realModule
	if !strings.Contains(blueprint, moduleLine) {
		t.Fatalf("gofastr.yml no longer declares %q — update this test's rewrite", moduleLine)
	}
	blueprint = strings.Replace(blueprint, moduleLine, moduleLine+"/"+scratchPkg, 1)
	// output_dir is left alone on purpose. Flattening it to "." changes the
	// generated self-imports (.../ecommerce/<scratch>/entities instead of
	// .../ecommerce/<scratch>/app/entities), so normalizing the module path
	// back out no longer reproduces the committed bytes and every file reads
	// as drifted. The first version of this test did exactly that and reported
	// app/main.go stale over a one-line import difference it had introduced
	// itself.
	if !strings.Contains(blueprint, "output_dir: app") {
		t.Fatalf("gofastr.yml no longer declares output_dir: app — update this test's rewrite")
	}
	if err := os.WriteFile(filepath.Join(dir, "gofastr.yml"), []byte(blueprint), 0o644); err != nil {
		t.Fatalf("write scratch blueprint: %v", err)
	}

	gen := exec.Command("go", "run", "github.com/DonaldMurillo/gofastr/cmd/gofastr",
		"generate", "--from=gofastr.yml")
	gen.Dir = dir
	if out, err := gen.CombinedOutput(); err != nil {
		t.Fatalf("gofastr generate --from=gofastr.yml: %v\n%s", err, out)
	}
	// output_dir: app, so the emitted app is one level down — the same layout
	// as the committed copy, which is what makes a byte comparison possible.
	return filepath.Join(dir, "app")
}

// normalizeModule undoes the scratch-package rewrite so generated bytes can be
// compared against the committed copy.
func normalizeModule(s string) string {
	return strings.ReplaceAll(s, realModule+"/"+scratchPkg, realModule)
}

// TestCommittedAppMatchesGeneratorOutput is the assertion the old --force
// behaviour was standing in for, made explicit.
//
// examples/ecommerce is the GENERATOR fixture (examples/meridian/doc.go says
// so), meaning its committed app/ is supposed to be what the generator emits
// today. Regenerating in place kept that true by overwriting it, which is not
// the same as checking it: the files silently drifted for some time before
// #175 refreshed them, and nothing failed while they did.
//
// This fails with the file that differs instead, so drift is a red test rather
// than a dirty tree nobody reads.
func TestCommittedAppMatchesGeneratorOutput(t *testing.T) {
	if testing.Short() {
		t.Skip("runs the generator; skipped under -short")
	}
	dir := generateShopfront(t)

	// Only the generator's own output is comparable. Hand-written tests that
	// live alongside it in app/ are not emitted and must not be demanded.
	var checked int
	err := filepath.Walk(dir, func(path string, info os.FileInfo, err error) error {
		if err != nil || info.IsDir() || !strings.HasSuffix(path, ".go") {
			return err
		}
		rel, relErr := filepath.Rel(dir, path)
		if relErr != nil {
			return relErr
		}
		if strings.HasSuffix(rel, "_test.go") {
			return nil
		}
		gotBytes, readErr := os.ReadFile(path)
		if readErr != nil {
			return readErr
		}
		committedPath := filepath.Join("app", rel)
		wantBytes, readErr := os.ReadFile(committedPath)
		if os.IsNotExist(readErr) {
			t.Errorf("the generator emits %s but it is not committed under app/ — regenerate and commit", rel)
			return nil
		}
		if readErr != nil {
			return readErr
		}
		checked++
		if normalizeModule(string(gotBytes)) != string(wantBytes) {
			t.Errorf("app/%s is stale: the generator emits different bytes. Regenerate with\n"+
				"    (cd examples/ecommerce && go run github.com/DonaldMurillo/gofastr/cmd/gofastr generate --from=gofastr.yml --force)",
				rel)
		}
		return nil
	})
	if err != nil {
		t.Fatalf("walk generated output: %v", err)
	}
	// A walk that matched nothing would make every assertion above vacuous and
	// report a clean pass over an empty set.
	if checked == 0 {
		t.Fatal("compared no generated files — the generator emitted nothing, or the walk is wrong")
	}
	t.Logf("compared %d generated files against the committed app/", checked)
}
