package schema

// FieldType enumerates all supported field types in a GoFastr entity schema.
type FieldType int

const (
	String    FieldType = iota // short string
	Text                       // long text / textarea
	Int                        // integer
	Float                      // floating point
	Decimal                    // fixed-precision decimal (stored as string)
	Bool                       // boolean
	Enum                       // one of a fixed set of strings
	UUID                       // UUID v4 identifier
	Timestamp                  // RFC 3339 timestamp
	Date                       // calendar date (2006-01-02)
	JSON                       // arbitrary JSON blob
	Relation                   // reference to another entity
	Image                      // image URL or path
	File                       // file URL or path
)

// AutoGenerate controls how a field value is automatically produced server-side.
type AutoGenerate int

const (
	AutoNone      AutoGenerate = iota // not auto-generated
	AutoUUID                          // UUID v4
	AutoTimestamp                     // current RFC 3339 timestamp
	AutoIncrement                     // auto-incrementing integer
)

// Field defines a single field in an entity schema.
type Field struct {
	Name         string       // field name (must be unique within a Schema)
	Type         FieldType    // field type
	Required     bool         // value must be present and non-zero
	Unique       bool         // value must be unique across entities
	Default      any          // default value when omitted
	AutoGenerate AutoGenerate // server-side auto-generation strategy
	ReadOnly     bool         // excluded from create/update request bodies
	Hidden       bool         // excluded from API responses
	Max          *float64     // upper bound (numeric max / string max-length)
	Min          *float64     // lower bound (numeric min / string min-length)
	Pattern      string       // regex pattern for string validation
	Values       []string     // allowed values for Enum
	To           string       // target entity name for Relation
	Many         bool         // has-many relation flag
}

// Schema is an ordered collection of Fields with convenience helpers.
type Schema struct {
	Fields []Field
}

// FieldByName returns the field with the given name and true,
// or the zero Field and false if not found.
func (s Schema) FieldByName(name string) (Field, bool) {
	for _, f := range s.Fields {
		if f.Name == name {
			return f, true
		}
	}
	return Field{}, false
}

// Names returns the ordered list of field names.
func (s Schema) Names() []string {
	names := make([]string, len(s.Fields))
	for i, f := range s.Fields {
		names[i] = f.Name
	}
	return names
}

// RequiredFields returns only the required fields.
func (s Schema) RequiredFields() []Field {
	var out []Field
	for _, f := range s.Fields {
		if f.Required {
			out = append(out, f)
		}
	}
	return out
}

// AutoGeneratedFields returns fields that are auto-generated server-side.
func (s Schema) AutoGeneratedFields() []Field {
	var out []Field
	for _, f := range s.Fields {
		if f.AutoGenerate != AutoNone {
			out = append(out, f)
		}
	}
	return out
}

// WritableFields returns fields that can be set by the client (not auto-generated, not read-only).
func (s Schema) WritableFields() []Field {
	var out []Field
	for _, f := range s.Fields {
		if f.AutoGenerate == AutoNone && !f.ReadOnly {
			out = append(out, f)
		}
	}
	return out
}

// VisibleFields returns fields that are included in API responses (not hidden).
func (s Schema) VisibleFields() []Field {
	var out []Field
	for _, f := range s.Fields {
		if !f.Hidden {
			out = append(out, f)
		}
	}
	return out
}

// Validate checks a single value against a Field definition.
// Returns nil on success or a descriptive error on failure.
func Validate(field Field, value any) error {
	return validateField(field, value)
}

// ValidationResult holds the outcome of validating a full map of values.
type ValidationResult struct {
	Valid  bool
	Errors map[string][]string // field name → list of error messages
}

// ValidateAll validates a map of values against every Field in the Schema.
// Unknown keys are ignored; missing required fields produce errors.
func ValidateAll(s Schema, values map[string]any) ValidationResult {
	result := ValidationResult{
		Errors: make(map[string][]string),
	}

	for _, f := range s.Fields {
		// Auto-generated fields are created server-side, skip validation
		if f.AutoGenerate != AutoNone {
			continue
		}
		val, present := values[f.Name]
		if !present {
			if f.Required && f.Default == nil {
				result.Errors[f.Name] = append(result.Errors[f.Name], "is required")
			}
			continue
		}
		if err := validateField(f, val); err != nil {
			result.Errors[f.Name] = append(result.Errors[f.Name], err.Error())
		}
	}

	result.Valid = len(result.Errors) == 0
	return result
}

// ValidatePartial validates only the fields that are present in `values`.
// Missing fields — required or not — are not reported. Use this for
// partial-update flows (PUT/PATCH with only the fields the caller wants
// to change) so a sparse update doesn't fail because some other required
// field happens not to be in the body.
func ValidatePartial(s Schema, values map[string]any) ValidationResult {
	result := ValidationResult{
		Errors: make(map[string][]string),
	}

	for _, f := range s.Fields {
		if f.AutoGenerate != AutoNone {
			continue
		}
		val, present := values[f.Name]
		if !present {
			continue
		}
		if err := validateField(f, val); err != nil {
			result.Errors[f.Name] = append(result.Errors[f.Name], err.Error())
		}
	}

	result.Valid = len(result.Errors) == 0
	return result
}
