package desktop

import (
	"encoding/json"
	"fmt"
	"runtime"
	"strings"
)

// BridgeJS emits the per-host typed bridge served at
// /__gofastr/desktop/bridge.js. It layers the frozen manifest's typed
// namespaces on top of the fixed desktop runtime module.
//
// Emission discipline: every capability and method name reaches the
// emitted JavaScript ONLY as a quoted Go string (%q) or a bracket
// string key, never as a bare identifier, even though the registry
// validated the grammar. The manifest itself is one quoted JSON string
// handed to JSON.parse, never an object literal (a __proto__ key in a
// literal is a setter at best and a duplicate is a SyntaxError).
// A capability absent from this host's manifest simply has no JS
// namespace; calling it goes through `call` and rejects not_found
// server-side.
func BridgeJS(m Manifest) []byte {
	manifestJSON, err := json.Marshal(m)
	if err != nil {
		manifestJSON = []byte(`{}`)
	}
	var b strings.Builder
	b.WriteString("// Generated by battery/desktop from the frozen capability manifest. Do not edit.\n")
	b.WriteString("(() => {\n")
	b.WriteString("  'use strict';\n")
	b.WriteString("  window.__gofastr = window.__gofastr || {};\n")
	b.WriteString("  const NS = window.__gofastr;\n")
	b.WriteString("  const init = () => {\n")
	b.WriteString("    const D = NS.desktop;\n")
	b.WriteString("    D.manifest = JSON.parse(" + jsQuote(string(manifestJSON)) + ");\n")
	for _, cap := range m.Capabilities {
		// jsQuote, never %q: Go quoting emits \U0001F600 for an astral
		// rune (JS cannot parse it) and leaves U+2028/U+2029 raw. The name
		// grammars are anchored ASCII today, so this is drift rather than a
		// live hole - but the emitter must not depend on a validator two
		// files away for a property it can guarantee itself.
		fmt.Fprintf(&b, "    D[%s] = {\n", jsQuote(cap.Name))
		for _, mm := range cap.Methods {
			fmt.Fprintf(&b, "      %s: (input) => D.call(%s, %s, input),\n",
				jsQuote(mm.Name), jsQuote(cap.Name), jsQuote(mm.Name))
		}
		b.WriteString("    };\n")
	}
	b.WriteString("  };\n")
	b.WriteString("  (NS.loadModule ? NS.loadModule('desktop') : Promise.reject(new Error('runtime missing'))).then(init).catch(() => {});\n")
	b.WriteString("})();\n")
	return []byte(b.String())
}

// jsQuote renders s as a JavaScript string literal. It goes through
// encoding/json, not strconv.Quote: Go's quoting emits \U000E0001 for
// a non-printable astral rune, which JavaScript does not parse, while
// a JSON string literal is a valid JavaScript literal (json.Marshal
// escapes U+2028 and U+2029 as well). Every string spliced into
// evaluated or served JavaScript uses this.
func jsQuote(s string) string {
	q, err := json.Marshal(s)
	if err != nil {
		// A Go string always marshals; keep the failure loud but safe.
		return `""`
	}
	return string(q)
}

// DTS emits a starting-point TypeScript declaration for the desktop
// bridge: one namespace per capability, method signatures typed from
// the JSON Schemas when they are object schemas with primitive
// properties, unknown otherwise. The `gofastr desktop types` command
// (phase 3) serves this per host.
func DTS(m Manifest) string {
	var b strings.Builder
	b.WriteString("// Generated by battery/desktop from the frozen capability manifest.\n")
	b.WriteString("declare global {\n")
	b.WriteString("  interface Window {\n")
	b.WriteString("    __gofastr: {\n")
	b.WriteString("      desktop: {\n")
	b.WriteString("        available: boolean;\n")
	b.WriteString("        manifest: unknown | null;\n")
	b.WriteString("        call: (cap: string, method: string, input?: unknown) => Promise<unknown>;\n")
	b.WriteString("        on: (name: string, fn: (payload: unknown) => void) => void;\n")
	b.WriteString("        off: (name: string, fn: (payload: unknown) => void) => void;\n")
	for _, cap := range m.Capabilities {
		fmt.Fprintf(&b, "        %s: {\n", tsSafeName(cap.Name))
		fmt.Fprintf(&b, "          // v%d\n", cap.Version)
		for _, mm := range cap.Methods {
			out := tsTypeFromSchema(mm.Output)
			var sig string
			if len(mm.Input) > 0 {
				sig = fmt.Sprintf("(input: %s): Promise<%s>", tsTypeFromSchema(mm.Input), out)
			} else {
				sig = fmt.Sprintf("(): Promise<%s>", out)
			}
			fmt.Fprintf(&b, "          %s: %s;\n", tsSafeName(mm.Name), sig)
		}
		b.WriteString("        };\n")
	}
	b.WriteString("      };\n")
	b.WriteString("    };\n")
	b.WriteString("  }\n")
	b.WriteString("}\n")
	b.WriteString("export {};\n")
	return b.String()
}

// tsSafeName quotes a validated identifier for a TS property slot.
// Names already passed the registry grammar; quoting through jsQuote
// (the same helper the JS emitter uses) keeps the generator honest
// without depending on that grammar.
func tsSafeName(name string) string {
	return jsQuote(name)
}

// tsTypeFromSchema renders an input/output type from a JSON Schema.
// Only object schemas whose properties are all primitives are typed;
// anything else is "unknown". An absent schema is "void" (no output
// worth declaring).
func tsTypeFromSchema(schema json.RawMessage) string {
	if len(schema) == 0 {
		return "void"
	}
	var s struct {
		Type       string `json:"type"`
		Properties map[string]struct {
			Type string `json:"type"`
		} `json:"properties"`
		Required []string `json:"required"`
	}
	if err := json.Unmarshal(schema, &s); err != nil || s.Type != "object" {
		return "unknown"
	}
	if len(s.Properties) == 0 {
		return "unknown"
	}
	required := make(map[string]bool, len(s.Required))
	for _, r := range s.Required {
		required[r] = true
	}
	// Deterministic: sorted property order (mapwriter discipline).
	keys := make([]string, 0, len(s.Properties))
	for k := range s.Properties {
		keys = append(keys, k)
	}
	sortStrings(keys)
	var parts []string
	for _, k := range keys {
		ts, ok := tsPrimitive(s.Properties[k].Type)
		if !ok {
			return "unknown"
		}
		if required[k] {
			parts = append(parts, fmt.Sprintf("%s: %s", tsSafeName(k), ts))
		} else {
			parts = append(parts, fmt.Sprintf("%s?: %s", tsSafeName(k), ts))
		}
	}
	return "{ " + strings.Join(parts, "; ") + " }"
}

// tsPrimitive maps a JSON Schema primitive to its TS spelling.
func tsPrimitive(t string) (string, bool) {
	switch t {
	case "string":
		return "string", true
	case "number", "integer":
		return "number", true
	case "boolean":
		return "boolean", true
	default:
		return "", false
	}
}

// sortStrings sorts in place (slices.Sort, named so the generator has
// no direct slices dependency at every emit site).
func sortStrings(s []string) {
	for i := 1; i < len(s); i++ {
		for j := i; j > 0 && s[j] < s[j-1]; j-- {
			s[j], s[j-1] = s[j-1], s[j]
		}
	}
}

// BootstrapJS is the ONE script a native shell injects into a window's
// pages at document start: the host marker the desktop runtime module
// detects (`window.__gofastr_desktop`, with the host OS, the battery's
// module version, and the id of the window the page lives in, "main"
// for the first window). Every window gets its own copy carrying its
// own id. A test harness that drives a real browser injects the same
// script so the page sees a desktop host.
//
// The value is built in Go and spliced in as a quoted string handed to
// JSON.parse, never an object literal (the jsQuote rule: __proto__ in a
// literal is a setter, a duplicate key a SyntaxError).
func BootstrapJS(windowID string) string {
	payload, err := json.Marshal(map[string]string{"os": runtime.GOOS, "version": moduleVersion(), "window": windowID})
	if err != nil {
		payload = []byte(`{"os":"` + runtime.GOOS + `","version":"dev","window":"main"}`)
	}
	return "window.__gofastr_desktop = JSON.parse(" + jsQuote(string(payload)) + ")"
}
