package chat

import (
	"github.com/gofastr/gofastr/core-ui/style"
	"github.com/gofastr/gofastr/core-ui/widget/theme"
	"github.com/gofastr/gofastr/kiln/world"
)

// pageCSS resolves the kiln page stylesheet through core-ui/widget/theme.
// World.App.Theme overrides (e.g. set by a future set_theme tool) merge
// on top of the framework default. No CSS lives in this package — it's
// all generated by the framework's stylesheet builder.
func pageCSS() string {
	return pageCSSFor(nil)
}

// pageCSSFor resolves the page CSS with optional world-level overrides.
// Used by /kiln/theme.css when the kiln server has access to the live
// session and can pull the current world.App.Theme.
func pageCSSFor(app *world.AppConfig) string {
	overlay := overrideTheme(app)
	t := theme.PageTheme(overlay)
	return theme.PageCSS(t)
}

// overrideTheme converts world.App.Theme (a flat key→value map) into a
// style.Theme overlay. Keys map to color tokens — that's the surface
// area exposed to set_theme today; spacing/radii/font overrides can
// land later without churning the protocol.
func overrideTheme(app *world.AppConfig) style.Theme {
	if app == nil || len(app.Theme) == 0 {
		return style.Theme{}
	}
	colors := style.Colors{}
	for k, v := range app.Theme {
		colors[k] = v
	}
	return style.Theme{Colors: colors}
}
