package contracts

import (
	"strings"
	"testing"
)

// Property: the generated-code exemption requires the full conventional
// header (`// Code generated … DO NOT EDIT.`), not either half of it.
// The exemption removes a file from every analyzer, and the header is
// repo content: a PR that adds a bare `// DO NOT EDIT` line to the file
// carrying its violation buys a whole-tree exemption that reads like a
// comment in review.
func TestGeneratedSourceNeedsFullHeader(t *testing.T) {
	cases := []struct {
		name string
		body string
		want bool
	}{
		{"conventional header", "// Code generated by tool. DO NOT EDIT.\npackage a\n", true},
		{"edit half alone", "// DO NOT EDIT\npackage a\n", false},
		{"generated half alone", "// Code generated by hand\npackage a\n", false},
	}
	for _, c := range cases {
		if got := IsGeneratedSource([]byte(c.body)); got != c.want {
			t.Errorf("SECURITY: [exempt-evasion] IsGeneratedSource(%s) = %v, want %v: half a header must not exempt a file from every analyzer", c.name, got, c.want)
		}
	}
	// The phrase beyond the 512-byte window never exempts (documented).
	far := strings.Repeat("// filler line to push past the window\n", 20) + "// Code generated by x. DO NOT EDIT.\npackage a\n"
	if IsGeneratedSource([]byte(far)) {
		t.Error("SECURITY: [exempt-evasion] a header past the 512-byte window exempted the file")
	}

	// Discovery surface: NewPass applies the same predicate when
	// classifying files, so the half-header file must still be analysed.
	dir := t.TempDir()
	writeTemp(t, dir, "hand.go", "// DO NOT EDIT\npackage a\n")
	writeTemp(t, dir, "gen.go", "// Code generated by x. DO NOT EDIT.\npackage a\n")
	p, err := NewPass(dir, DefaultConfig())
	if err != nil {
		t.Fatal(err)
	}
	analysed := map[string]bool{}
	for _, f := range p.AppFiles() {
		analysed[f.Rel] = true
	}
	if !analysed["hand.go"] {
		t.Error("SECURITY: [exempt-evasion] a file whose only marker is `// DO NOT EDIT` was skipped by every analyzer")
	}
	if analysed["gen.go"] {
		t.Error("premise broken: a genuinely generated file was analysed")
	}
}

// Property: traversal-shaped and absolute glob patterns are inert —
// they can never match a discovered (pass-relative) path, so no
// exemption written in a config can waive findings via an out-of-tree
// pattern. Pin it so a change in path normalisation (Rel producing
// `..` segments, absolute patterns matching) fails loudly instead of
// quietly broadening exemptions.
func TestGlobTraversalPatternsInert(t *testing.T) {
	inert := []string{"..", "../**", "../a.go", "/a.go", `..\..\a.go`, "a/../../b.go", ""}
	// Every path discovery can actually produce: pass-relative, slash-
	// separated, no `..` or leading `/`.
	paths := []string{"a.go", "a/b.go", "core/handler.go", "dist/x.go", "a/b/c/d.go"}
	for _, pat := range inert {
		for _, p := range paths {
			if matchGlob(pat, p) {
				t.Errorf("SECURITY: [traversal] out-of-tree pattern %q matched in-tree path %q", pat, p)
			}
		}
	}
	// Happy controls: the matcher itself works, so the loop above cannot
	// pass by accident of a broken matcher.
	if !matchGlob("core/**", "core/handler/x.go") || !matchGlob("core/**", "core") {
		t.Error("premise broken: documented `**` matching does not work")
	}
	if !MatchPath("core/*", "core/router") {
		t.Error("premise broken: MatchPath does not match a single segment")
	}
}
