// Code generated by "gofastr gen styles" from helpdocs.tokens.css. DO NOT EDIT.
// Source hash: sha256:8e700f6e14116478a9b3b54575271de94033c13f99b005f1e3d181679c9ca63b

package helpdocs

import "github.com/DonaldMurillo/gofastr/core-ui/style"

// Tokens is helpdocs.tokens.css as typed theme tokens. Add them to the theme with
// Extend, which also takes the file's dark values:
//
//	site.WithTheme(theme.Default().Extend(helpdocs.Tokens))
var Tokens = helpdocsTokens{
	Sizes: helpdocsSizes{
		ProseMeasure: style.Size{Name: "prose-measure", Value: "68ch"},
	},
}

// helpdocsTokens is the token set of helpdocs.tokens.css, grouped like style.Theme.
type helpdocsTokens struct {
	Sizes helpdocsSizes
}

// helpdocsSizes are the style.Size tokens of helpdocs.tokens.css.
type helpdocsSizes struct {
	// ProseMeasure is --size-prose-measure. The longest line an article's text runs to.
	ProseMeasure style.Size
}
