// Code generated by "gofastr gen styles" from helpdocs.style.css. DO NOT EDIT.
// Source hash: sha256:c87f52be62d80d7f93b2d88df9e0ce22cbfaae48ca2cb10a3acb5bb5e47dc83b

package helpdocs

import (
	"strings"

	"github.com/DonaldMurillo/gofastr/core-ui/ownstyle"
)

// helpdocsCSS is the checked source of the helpdocs owned style.
const helpdocsCSS = `/* The help center page: nav | article | contents, on the page measure
   (--size-page-width, with --size-page-gutter outside it) so the rails
   line up with the header's brand and call to action. */
:scope {
  display: grid;
  grid-template-columns: 13rem minmax(0, 1fr) 12rem;
  gap: var(--spacing-2xl);
  max-inline-size: calc(var(--size-page-width) + 2 * var(--size-page-gutter));
  margin-inline: auto;
  padding: var(--spacing-2xl) var(--size-page-gutter) var(--spacing-3xl);
}
/* An article with no headings fills no contents: the column goes. */
:scope:has(.toc > :empty) { grid-template-columns: 13rem minmax(0, 1fr); }
.toc:has(> :empty) { display: none; }

/* The rails stay in view under the pinned header while the article
   scrolls; a long nav scrolls on its own. */
.nav,
.toc {
  position: sticky;
  inset-block-start: calc(var(--size-header-height) + var(--spacing-2xl));
  align-self: start;
  max-block-size: calc(100dvh - var(--size-header-height) - 2 * var(--spacing-2xl));
  overflow-y: auto;
}

.article { min-inline-size: 0; }
.crumbs { margin-block-end: var(--spacing-lg); }
/* The article's own page header (the class rides its root). */
.title { margin-block-end: var(--spacing-lg); }

/* Article rhythm: headings open a section with room above, body text
   sits at a reading line height. A heading a contents link scrolls to
   stops below the header, not under it. */
.article h2,
.article h3 {
  scroll-margin-block-start: calc(var(--size-header-height) + var(--spacing-lg));
  line-height: 1.3;
}
.article h2 {
  margin: var(--spacing-3xl) 0 var(--spacing-md);
  font-size: var(--text-2xl);
}
.article h3 {
  margin: var(--spacing-2xl) 0 var(--spacing-sm);
  font-size: var(--text-xl);
}
/* Text stops at a reading measure, so an article with no contents
   rail does not run its lines across the freed column. */
.article p,
.article ul {
  max-inline-size: var(--size-prose-measure);
  margin-block: 0 var(--spacing-lg);
  line-height: 1.7;
}
.article ul { padding-inline-start: var(--spacing-xl); }
.article li + li { margin-block-start: var(--spacing-sm); }

/* Previous / next: two cards under the article, the next one on the
   right even when there is no previous. */
.pager {
  display: grid;
  grid-template-columns: repeat(2, minmax(0, 1fr));
  gap: var(--spacing-lg);
  margin-block-start: var(--spacing-3xl);
  padding-block-start: var(--spacing-xl);
  border-block-start: 1px solid var(--color-border);
}
.page {
  display: flex;
  flex-direction: column;
  gap: var(--spacing-xs);
  padding: var(--spacing-lg);
  border: 1px solid var(--color-border);
  border-radius: var(--radii-md);
  text-decoration: none;
  transition: border-color var(--duration-fast) var(--easing-ease-out);
}
.page.next {
  grid-column: 2;
  text-align: end;
}
.page:hover { border-color: var(--color-border-strong); }
.page:focus-visible { outline: 2px solid var(--color-text-subtle); outline-offset: 2px; }
.dir {
  color: var(--color-text-subtle);
  font-size: var(--text-xs);
}
.page-title {
  color: var(--color-text);
  font-weight: var(--font-weight-medium);
}

@media (--reduced-motion) {
  .page { transition: none; }
}

/* Below lg the contents rail goes; the nav and the article remain. */
@media (--below-lg) {
  :scope,
  :scope:has(.toc > :empty) { grid-template-columns: 13rem minmax(0, 1fr); }
  .toc { display: none; }
}

/* Phones: one column. The nav is the Sidebar's own drawer row above
   the article, so it no longer pins. */
@media (--below-md) {
  :scope,
  :scope:has(.toc > :empty) {
    grid-template-columns: minmax(0, 1fr);
    gap: var(--spacing-lg);
    padding-block-start: var(--spacing-lg);
  }
  .nav {
    position: static;
    max-block-size: none;
    overflow-y: visible;
  }
  .pager { grid-template-columns: minmax(0, 1fr); }
  .page.next { grid-column: auto; }
}
`

// helpdocsStyle carries the helpdocs owned style: the registered sheet (Name, Kind and
// Scope come from the embedded *ownstyle.Sheet) plus its class
// vocabulary as methods returning local class names.
type helpdocsStyle struct {
	*ownstyle.Sheet
}

// Style is the helpdocs owned style, registered at init.
// This package holds exactly one style file, so the handle is
// exported as Style; a package holding several exports each as
// <Owner>Style.
var Style = helpdocsStyle{ownstyle.Must("helpdocs", ownstyle.KindScoped, helpdocsCSS)}

// Toc returns the local class name "toc".
//
// The rails stay in view under the pinned header while the article
// scrolls; a long nav scrolls on its own.
func (s helpdocsStyle) Toc() string { return "toc" }

// Nav returns the local class name "nav".
//
// The rails stay in view under the pinned header while the article
// scrolls; a long nav scrolls on its own.
func (s helpdocsStyle) Nav() string { return "nav" }

// Article returns the local class name "article".
//
// Article rhythm: headings open a section with room above, body text
// sits at a reading line height. A heading a contents link scrolls to
// stops below the header, not under it.
func (s helpdocsStyle) Article() string { return "article" }

// Crumbs returns the local class name "crumbs".
func (s helpdocsStyle) Crumbs() string { return "crumbs" }

// Title returns the local class name "title".
//
// The article's own page header (the class rides its root).
func (s helpdocsStyle) Title() string { return "title" }

// Pager returns the local class name "pager".
//
// Previous / next: two cards under the article, the next one on the
// right even when there is no previous.
func (s helpdocsStyle) Pager() string { return "pager" }

// Page returns the local class name "page".
func (s helpdocsStyle) Page() string { return "page" }

// PageVariants selects the variants of the page base class.
type PageVariants struct {
	// Next reports whether the "next" flag class is set.
	Next bool
}

// PageWith returns the page base class plus the selected
// variants, space-separated in declaration order.
func (s helpdocsStyle) PageWith(v PageVariants) string {
	classes := []string{s.Page()}
	if v.Next {
		classes = append(classes, "next")
	}
	return strings.Join(classes, " ")
}

// Dir returns the local class name "dir".
func (s helpdocsStyle) Dir() string { return "dir" }

// PageTitle returns the local class name "page-title".
func (s helpdocsStyle) PageTitle() string { return "page-title" }
