// Code generated by gofastr. Owned — safe to edit.
package main

import (
	"encoding/json"
	"net/http"
	"net/http/cookiejar"
	"net/url"
	"os"
	"strings"
	"testing"
)

// TestMeridianTokenAuth exercises the customer-CLI credential path end to
// end: session login → mint a scoped API token via TokensPlugin → hit the
// owner-scoped customers API with the bearer token and no cookies.
func TestMeridianTokenAuth(t *testing.T) {
	if testing.Short() {
		t.Skip("builds + boots the binary")
	}
	base := e2eBootApp(t)
	adminPass := os.Getenv("ADMIN_SEED_PASSWORD")

	jar, _ := cookiejar.New(nil)
	session := &http.Client{Jar: jar}
	if _, err := session.PostForm(base+"/auth/login", url.Values{"email": {"admin@meridian.dev"}, "password": {adminPass}}); err != nil {
		t.Fatalf("login: %v", err)
	}

	// Mint a scoped token; the plaintext is shown exactly once.
	code, body := e2eDo(t, session, "POST", base+"/auth/tokens", `{"name":"cli-e2e","scopes":["customers:*"]}`)
	if code < 200 || code >= 300 {
		t.Fatalf("mint token = %d: %s", code, body)
	}
	var minted struct {
		Token string `json:"token"`
	}
	if err := json.Unmarshal([]byte(body), &minted); err != nil || !strings.HasPrefix(minted.Token, "gfsk_") {
		t.Fatalf("mint response missing plaintext token: %v %s", err, body)
	}

	bearer := func(method, path, payload string) (int, string) {
		t.Helper()
		var req *http.Request
		var err error
		if payload == "" {
			req, err = http.NewRequest(method, base+path, nil)
		} else {
			req, err = http.NewRequest(method, base+path, strings.NewReader(payload))
			if err == nil {
				req.Header.Set("Content-Type", "application/json")
			}
		}
		if err != nil {
			t.Fatal(err)
		}
		req.Header.Set("Authorization", "Bearer "+minted.Token)
		resp, err := http.DefaultClient.Do(req)
		if err != nil {
			t.Fatal(err)
		}
		defer resp.Body.Close()
		var sb strings.Builder
		buf := make([]byte, 32*1024)
		for {
			n, rerr := resp.Body.Read(buf)
			sb.Write(buf[:n])
			if rerr != nil {
				break
			}
		}
		return resp.StatusCode, sb.String()
	}

	// Bearer create + list on the owner-scoped entity: the token carries the
	// admin's identity, so the row lands (and stays) in the admin's scope.
	code, body = bearer("POST", "/api/customers", `{"name":"token-made","email":"token@example.com"}`)
	if code != http.StatusCreated {
		t.Fatalf("bearer create = %d, want 201: %s", code, body)
	}
	code, body = bearer("GET", "/api/customers", "")
	if code != http.StatusOK || !strings.Contains(body, "token-made") {
		t.Fatalf("bearer list = %d, row visible=%v: %s", code, strings.Contains(body, "token-made"), body)
	}

	// The minted scopes must be enforced: a customers-only token is 403'd
	// off every other resource, read and write alike.
	code, body = bearer("GET", "/api/invoices", "")
	if code != http.StatusForbidden {
		t.Fatalf("customers-scoped token on invoices = %d, want 403: %s", code, body)
	}
	code, body = bearer("POST", "/api/plans", `{"name":"evil"}`)
	if code != http.StatusForbidden {
		t.Fatalf("customers-scoped token writing plans = %d, want 403: %s", code, body)
	}

	// A token scoped to customers must not satisfy other entity scopes'
	// baseline auth differently than sessions — but anonymous must 401.
	req, _ := http.NewRequest("GET", base+"/api/customers", nil)
	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		t.Fatal(err)
	}
	resp.Body.Close()
	if resp.StatusCode != http.StatusUnauthorized {
		t.Fatalf("anonymous list = %d, want 401", resp.StatusCode)
	}

	// Token-authenticated callers cannot manage tokens (session-only
	// surface): a leaked token must not mint siblings.
	code, body = bearer("POST", "/auth/tokens", `{"name":"evil","scopes":["*:*"]}`)
	if code != http.StatusUnauthorized {
		t.Fatalf("token-auth mint = %d, want 401: %s", code, body)
	}
}
