package main

import (
	"github.com/DonaldMurillo/gofastr/internal/scratchdir"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"
)

// scratchPkg is the throwaway package the blueprint is generated into.
// It lives inside the repo module so the generated code's self-import
// (github.com/DonaldMurillo/gofastr/examples/meridian/<scratchPkg>/entities)
// resolves without a go.mod, a replace directive, or a network fetch.
// Gitignored; removed before and after the test so a killed run cannot
// leave a package behind that later trips `go build ./...`.
// The leading underscore is what keeps the window shut: the directory
// is created mid-test and filled a moment later, so a `go list ./...`
// in another package's test binary at that instant used to fail hard
// with "no Go files in". Go's tooling ignores a "_"-prefixed directory
// when expanding `./...`, at every moment, while still resolving an
// explicit import path through it.
const scratchPkg = "_blueprintgen"

// TestScratchHiddenFromGoList: the scratch package must stay out of a ./... expansion while it
// exists, or a parallel `go build ./...` sees a half-written package.
func TestScratchHiddenFromGoList(t *testing.T) {
	scratchdir.AssertHiddenFromGoList(t, ".", scratchPkg)
}

// realModule is the module path the committed trees live under. The scratch
// copy appends scratchPkg to it, and normalizeModule below undoes that
// rewrite so generated output can be compared to the committed files.
const realModule = "github.com/DonaldMurillo/gofastr/examples/meridian"

// normalizeModule undoes the scratch-package rewrite so generated bytes can
// be compared against the committed files.
func normalizeModule(s string) string {
	return strings.ReplaceAll(s, realModule+"/"+scratchPkg, realModule)
}

// scratchWithBlueprint creates the scratch package with gofastr.yml copied
// in and app.module repointed at the scratch package, so the generated
// self-imports resolve to the code just emitted rather than to the
// committed package next door. Returns the absolute scratch dir; removal
// is registered as a cleanup.
func scratchWithBlueprint(t *testing.T) string {
	t.Helper()

	dir, err := filepath.Abs(scratchPkg)
	if err != nil {
		t.Fatalf("abs %s: %v", scratchPkg, err)
	}
	if err := os.RemoveAll(dir); err != nil {
		t.Fatalf("clear stale %s: %v", scratchPkg, err)
	}
	if err := os.MkdirAll(dir, 0o755); err != nil {
		t.Fatalf("mkdir %s: %v", scratchPkg, err)
	}
	t.Cleanup(func() { _ = os.RemoveAll(dir) })

	src, err := os.ReadFile("gofastr.yml")
	if err != nil {
		t.Fatalf("read gofastr.yml: %v", err)
	}
	moduleLine := "module: " + realModule
	if !strings.Contains(string(src), moduleLine) {
		t.Fatalf("gofastr.yml no longer declares %q: update this test's rewrite", moduleLine)
	}
	rewritten := strings.Replace(string(src), moduleLine, moduleLine+"/"+scratchPkg, 1)
	if err := os.WriteFile(filepath.Join(dir, "gofastr.yml"), []byte(rewritten), 0o644); err != nil {
		t.Fatalf("write scratch blueprint: %v", err)
	}
	return dir
}

// runGenerator runs the in-tree CLI source inside dir, so a generator
// regression fails here rather than at the next release.
func runGenerator(t *testing.T, dir string, args ...string) {
	t.Helper()
	argv := append([]string{"run", "github.com/DonaldMurillo/gofastr/cmd/gofastr"}, args...)
	gen := exec.Command("go", argv...)
	gen.Dir = dir
	if out, err := gen.CombinedOutput(); err != nil {
		t.Fatalf("gofastr %s: %v\n%s", strings.Join(args, " "), err, out)
	}
}

// TestBlueprintStillGenerates compiles gofastr.yml.
//
// The blueprint that seeded this app must keep producing an app that
// BUILDS. Without this gate, gofastr.yml can rot silently, which is
// exactly how #131 went unnoticed. Byte-parity of the whole app is not
// this test's contract (the hand-maintained surfaces are deliberately
// not generator output); the two generator-owned trees have their own
// gate in TestGeneratedTreesMatchGenerator below.
func TestBlueprintStillGenerates(t *testing.T) {
	if testing.Short() {
		t.Skip("runs the generator and compiles its output; skipped under -short")
	}
	dir := scratchWithBlueprint(t)
	runGenerator(t, dir, "generate", "--from=gofastr.yml")

	// Compile the result. The binary goes to a temp dir, never the
	// worktree. Building the main package pulls in the generated
	// entities package transitively; ./entities/... covers the rest
	// (non-main packages compile without emitting artifacts).
	bin := filepath.Join(t.TempDir(), "meridian-from-blueprint")
	build := exec.Command("go", "build", "-o", bin, ".")
	build.Dir = dir
	if out, err := build.CombinedOutput(); err != nil {
		t.Fatalf("generated app does not compile: gofastr.yml has rotted:\n%s", out)
	}

	rest := exec.Command("go", "build", "./entities/...")
	rest.Dir = dir
	if out, err := rest.CombinedOutput(); err != nil {
		t.Fatalf("generated entities packages do not compile:\n%s", out)
	}
}

// TestGeneratedTreesMatchGenerator gates the two generator-owned trees,
// entities/ and cmd/meridian/, for byte drift against today's templates,
// the meridian twin of examples/ecommerce's
// TestCommittedAppMatchesGeneratorOutput.
//
// Everything under those two trees is generator output and must stay
// byte-identical to a fresh regeneration (after the scratch module path
// is normalized away), with one exception: cmd/meridian/custom.go is the
// dev-owned extension seam, created when absent and never overwritten,
// so the generator cannot be its source of truth.
//
// Knowledge that used to live in comments inside these files (the plans
// cross-tenant catalog note) lives in gofastr.yml instead: exactly one
// non-generated place, and the generated files stay pristine so this
// gate can hold.
//
// The reverse direction is checked too: a committed file the generator
// no longer emits would linger as dead code that looks owned, so it
// fails the gate until deleted.
func TestGeneratedTreesMatchGenerator(t *testing.T) {
	if testing.Short() {
		t.Skip("runs the generator; skipped under -short")
	}
	dir := scratchWithBlueprint(t)
	runGenerator(t, dir, "generate", "--from=gofastr.yml")
	// The CLI reads the freshly emitted entities/ package, so it must
	// run after generate, from the scratch root. --binary=meridian is
	// load-bearing: the default derives the name from the scratch dir
	// name, and the binary name reaches the emitted header comment and
	// env prefix.
	runGenerator(t, dir, "generate", "cli", "--binary=meridian")

	owned := []struct{ generated, committed string }{
		{filepath.Join(dir, "entities"), "entities"},
		{filepath.Join(dir, "cmd", "meridian"), filepath.Join("cmd", "meridian")},
	}
	var checked int
	for _, tree := range owned {
		// Forward: every file the generator emits must be committed
		// with the same bytes.
		err := filepath.Walk(tree.generated, func(path string, info os.FileInfo, err error) error {
			if err != nil || info.IsDir() || !strings.HasSuffix(path, ".go") {
				return err
			}
			rel, relErr := filepath.Rel(tree.generated, path)
			if relErr != nil {
				return relErr
			}
			if rel == "custom.go" {
				return nil
			}
			gotBytes, readErr := os.ReadFile(path)
			if readErr != nil {
				return readErr
			}
			wantBytes, readErr := os.ReadFile(filepath.Join(tree.committed, rel))
			if os.IsNotExist(readErr) {
				t.Errorf("the generator emits %s but it is not committed under %s; regenerate and commit",
					rel, tree.committed)
				return nil
			}
			if readErr != nil {
				return readErr
			}
			checked++
			if normalizeModule(string(gotBytes)) != string(wantBytes) {
				t.Errorf("%s is stale: the generator emits different bytes. Regenerate with\n"+
					"    (cd examples/meridian/_blueprintgen && go run github.com/DonaldMurillo/gofastr/cmd/gofastr generate --from=gofastr.yml && go run github.com/DonaldMurillo/gofastr/cmd/gofastr generate cli --binary=meridian)\n"+
					"and copy entities/ and cmd/meridian/ over the committed trees (keep cmd/meridian/custom.go)",
					filepath.Join(tree.committed, rel))
			}
			return nil
		})
		if err != nil {
			t.Fatalf("walk generated %s: %v", tree.generated, err)
		}

		// Reverse: every committed file must be generator output
		// (custom.go excepted), or it is a leftover the generator no
		// longer emits.
		err = filepath.Walk(tree.committed, func(committedPath string, info os.FileInfo, err error) error {
			if err != nil || info.IsDir() || !strings.HasSuffix(committedPath, ".go") {
				return err
			}
			rel, relErr := filepath.Rel(tree.committed, committedPath)
			if relErr != nil {
				return relErr
			}
			if rel == "custom.go" {
				return nil
			}
			if _, statErr := os.Stat(filepath.Join(tree.generated, rel)); statErr != nil {
				t.Errorf("%s is committed but the generator no longer emits it; delete it or move it into the hand-maintained part of the app",
					committedPath)
			}
			return nil
		})
		if err != nil {
			t.Fatalf("walk committed %s: %v", tree.committed, err)
		}
	}
	// A walk that matched nothing would make every assertion above vacuous and
	// report a clean pass over an empty set.
	if checked == 0 {
		t.Fatal("compared no generated files: the generator emitted nothing, or the walk is wrong")
	}
	t.Logf("compared %d generated files against the committed trees", checked)
}
