// Code generated by gofastr. Owned — safe to edit.
package main

// Browser-driven checks for the interactive design-system surfaces the
// plain-HTTP TestE2E can't see: the quick-add customer modal (a plain
// preset.Modal relying on the default centered panel) and the Customers
// DataTable running in island mode (sort + pagination via RPC, swapping
// just the table — never a document navigation).

import (
	"context"
	"io"
	"os"
	"os/exec"
	"path/filepath"
	"testing"
	"time"

	"github.com/chromedp/chromedp"
	"github.com/chromedp/chromedp/kb"

	"github.com/DonaldMurillo/gofastr/core/dotenv"
)

// e2eBootApp builds and boots the app on a free port with a throwaway
// database, mirroring TestE2E's boot, and returns the base URL.
func e2eBootApp(t *testing.T) string {
	t.Helper()
	_ = dotenv.LoadAndApply(".env.local", ".env")
	if os.Getenv("ADMIN_SEED_PASSWORD") == "" {
		t.Setenv("ADMIN_SEED_PASSWORD", "e2e-seed-admin-pw")
	}
	dir := t.TempDir()
	bin := filepath.Join(dir, "app")
	build := exec.Command("go", "build", "-o", bin, ".")
	build.Stderr = os.Stderr
	if err := build.Run(); err != nil {
		t.Fatalf("build: %v", err)
	}
	addr := e2eFreeAddr(t)
	srv := exec.Command(bin)
	srv.Dir = dir
	srv.Env = append(os.Environ(), "PORT="+addr, "DATABASE_URL=file:"+filepath.Join(dir, "e2e.db"))
	srv.Stdout, srv.Stderr = io.Discard, io.Discard
	if err := srv.Start(); err != nil {
		t.Fatalf("start: %v", err)
	}
	t.Cleanup(func() { _ = srv.Process.Kill(); _, _ = srv.Process.Wait() })
	base := "http://" + addr
	e2eWaitReady(t, base)
	return base
}

// e2eBrowser returns a headless Chrome context with a test-scoped timeout.
func e2eBrowser(t *testing.T) context.Context {
	t.Helper()
	opts := append(chromedp.DefaultExecAllocatorOptions[:],
		chromedp.Flag("headless", true),
		chromedp.Flag("disable-gpu", true),
		chromedp.Flag("no-sandbox", true),
		chromedp.WindowSize(1280, 800),
	)
	allocCtx, allocCancel := chromedp.NewExecAllocator(context.Background(), opts...)
	t.Cleanup(allocCancel)
	browserCtx, browserCancel := chromedp.NewContext(allocCtx)
	t.Cleanup(browserCancel)
	ctx, cancel := context.WithTimeout(browserCtx, 60*time.Second)
	t.Cleanup(cancel)
	return ctx
}

// e2eLogin signs the seeded admin in through the real login form.
// chromedp.Submit doesn't fire the submit event — click the button.
func e2eLogin(t *testing.T, ctx context.Context, base string) {
	t.Helper()
	if err := chromedp.Run(ctx,
		chromedp.Navigate(base+"/login"),
		chromedp.WaitVisible(`#auth-email`, chromedp.ByQuery),
		chromedp.SendKeys(`#auth-email`, "admin@meridian.dev", chromedp.ByQuery),
		chromedp.SendKeys(`#auth-password`, os.Getenv("ADMIN_SEED_PASSWORD"), chromedp.ByQuery),
		chromedp.Click(`button[type="submit"]`, chromedp.ByQuery),
		chromedp.WaitVisible(`a[href="/app/customers"]`, chromedp.ByQuery),
	); err != nil {
		t.Fatalf("login: %v", err)
	}
}

func TestE2E_QuickAddModal(t *testing.T) {
	if testing.Short() {
		t.Skip("builds + boots the binary")
	}
	base := e2eBootApp(t)
	ctx := e2eBrowser(t)
	e2eLogin(t, ctx, base)

	// A dismissed widget is hidden in place when it hydrated from SSR
	// chrome, and detached when it was lazy-mounted — both count as closed.
	const closedJS = `(() => {
		const w = document.querySelector('[data-fui-widget="customer-quick-add"]');
		return !w || w.hidden;
	})()`
	var panelBG string
	var closedAfterEsc, closedAfterSave, countBumped bool
	if err := chromedp.Run(ctx,
		chromedp.Navigate(base+"/app/customers"),
		chromedp.WaitVisible(`button[data-fui-open="customer-quick-add"]`, chromedp.ByQuery),
		chromedp.Click(`button[data-fui-open="customer-quick-add"]`, chromedp.ByQuery),
		chromedp.WaitVisible(`#qa-name`, chromedp.ByQuery),
		// The default centered panel must paint a surface behind the form.
		chromedp.Evaluate(`(() => {
			const s = document.querySelector('[data-fui-widget="customer-quick-add"] .fui-panel');
			return s ? getComputedStyle(s).backgroundColor : "";
		})()`, &panelBG),
		// ESC dismisses…
		chromedp.KeyEvent(kb.Escape),
		chromedp.Sleep(400*time.Millisecond),
		chromedp.Evaluate(closedJS, &closedAfterEsc),
		// …and re-opening + submitting creates the customer and closes.
		chromedp.Click(`button[data-fui-open="customer-quick-add"]`, chromedp.ByQuery),
		chromedp.WaitVisible(`#qa-name`, chromedp.ByQuery),
		chromedp.SendKeys(`#qa-name`, "Modal E2E", chromedp.ByQuery),
		chromedp.SendKeys(`#qa-email`, "modal-e2e@example.com", chromedp.ByQuery),
		chromedp.Click(`[data-fui-widget="customer-quick-add"] button[type="submit"]`, chromedp.ByQuery),
		chromedp.Sleep(1200*time.Millisecond),
		chromedp.Evaluate(closedJS, &closedAfterSave),
		// data-fui-rpc-navigate re-rendered the list: 10 seeds + 1.
		chromedp.Evaluate(`document.body.innerText.includes("11 customers")`, &countBumped),
	); err != nil {
		t.Fatalf("modal flow: %v", err)
	}
	if panelBG == "" || panelBG == "rgba(0, 0, 0, 0)" || panelBG == "transparent" {
		t.Errorf("modal panel background = %q — default panel surface missing", panelBG)
	}
	if !closedAfterEsc {
		t.Error("Escape did not close the modal")
	}
	if !closedAfterSave {
		t.Error("successful submit did not close the modal")
	}
	if !countBumped {
		t.Error("list did not refresh to 11 customers after quick add")
	}
}

func TestE2E_CustomersSortIsland(t *testing.T) {
	if testing.Short() {
		t.Skip("builds + boots the binary")
	}
	base := e2eBootApp(t)
	ctx := e2eBrowser(t)
	e2eLogin(t, ctx, base)

	sortBtn := `.ui-data-table th:first-child button.ui-data-table__sort`
	var mark int
	var first, loc string
	if err := chromedp.Run(ctx,
		chromedp.Navigate(base+"/app/customers"),
		chromedp.WaitVisible(`.ui-data-table`, chromedp.ByQuery),
		chromedp.Evaluate(`window.__e2eMark = 1`, nil),
		// Two clicks on the Name header: asc, then desc. Each swap
		// re-renders the island, so re-query the button per click.
		chromedp.Click(sortBtn, chromedp.ByQuery),
		chromedp.Sleep(700*time.Millisecond),
		chromedp.Click(sortBtn, chromedp.ByQuery),
		chromedp.Sleep(700*time.Millisecond),
		chromedp.Evaluate(`document.querySelector('.ui-data-table tbody tr td').innerText`, &first),
		chromedp.Evaluate(`window.__e2eMark || 0`, &mark),
		chromedp.Evaluate(`location.search`, &loc),
	); err != nil {
		t.Fatalf("sort flow: %v", err)
	}
	if first != "Tim Berners-Lee" {
		t.Errorf("first row after desc name sort = %q, want Tim Berners-Lee", first)
	}
	if mark != 1 {
		t.Error("window marker lost — sort caused a document navigation, not an island swap")
	}
	if loc != "?sort=name&dir=desc" {
		t.Errorf("push-state URL = %q, want ?sort=name&dir=desc", loc)
	}
}

func TestE2E_CustomersPageIsland(t *testing.T) {
	if testing.Short() {
		t.Skip("builds + boots the binary")
	}
	base := e2eBootApp(t)
	ctx := e2eBrowser(t)
	e2eLogin(t, ctx, base)

	var mark, rows int
	var loc string
	if err := chromedp.Run(ctx,
		chromedp.Navigate(base+"/app/customers"),
		chromedp.WaitVisible(`.ui-data-table`, chromedp.ByQuery),
		chromedp.Evaluate(`window.__e2eMark = 1`, nil),
		// 10 seeded customers at page size 8 → the seed data alone
		// paginates. Page 2 holds the last two rows.
		chromedp.Click(`.ui-data-table__footer button[data-fui-rpc$="p=2"]`, chromedp.ByQuery),
		chromedp.Sleep(700*time.Millisecond),
		chromedp.Evaluate(`document.querySelectorAll('.ui-data-table tbody tr').length`, &rows),
		chromedp.Evaluate(`window.__e2eMark || 0`, &mark),
		chromedp.Evaluate(`location.search`, &loc),
	); err != nil {
		t.Fatalf("page flow: %v", err)
	}
	if rows != 2 {
		t.Errorf("page 2 rows = %d, want 2", rows)
	}
	if mark != 1 {
		t.Error("window marker lost — paging caused a document navigation, not an island swap")
	}
	if loc != "?p=2" {
		t.Errorf("push-state URL = %q, want ?p=2", loc)
	}
}
