// Code generated by gofastr. Owned — safe to edit.
package main

import (
	"io"
	"net"
	"net/http"
	"net/http/cookiejar"
	"net/url"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"strings"
	"testing"
	"time"
)

func TestBlueprintE2E(t *testing.T) {
	if testing.Short() {
		t.Skip("builds + boots the binary")
	}
	dir := t.TempDir()
	bin := filepath.Join(dir, "app")
	build := exec.Command("go", "build", "-o", bin, ".")
	build.Stderr = os.Stderr
	if err := build.Run(); err != nil {
		t.Fatalf("build: %v", err)
	}
	addr := e2eFreeAddr(t)
	srv := exec.Command(bin)
	srv.Dir = dir
	srv.Env = append(os.Environ(), "PORT="+addr, "DATABASE_URL=file:"+filepath.Join(dir, "e2e.db"))
	srv.Stdout, srv.Stderr = io.Discard, io.Discard
	if err := srv.Start(); err != nil {
		t.Fatalf("start: %v", err)
	}
	t.Cleanup(func() { _ = srv.Process.Kill(); _, _ = srv.Process.Wait() })
	base := "http://" + addr
	e2eWaitReady(t, base)

	if code, body := e2eDo(t, http.DefaultClient, "GET", base+"/", ""); code != http.StatusOK || !strings.Contains(body, "Meridian") {
		t.Errorf("home page = %d, missing brand? %v", code, !strings.Contains(body, "Meridian"))
	}

	// Public screens render for anonymous visitors.
	for _, p := range []string{"/", "/pricing", "/about", "/terms", "/privacy", "/login", "/signup"} {
		if code, body := e2eDo(t, http.DefaultClient, "GET", base+p, ""); code != http.StatusOK {
			t.Errorf("public screen %s = %d, want 200", p, code)
		} else if len(body) < 120 {
			t.Errorf("public screen %s body suspiciously short (%d bytes)", p, len(body))
		}
	}

	// Gated screens redirect anonymous callers to the login page.
	noRedir := &http.Client{CheckRedirect: func(*http.Request, []*http.Request) error { return http.ErrUseLastResponse }}
	for _, p := range []string{"/app", "/app/customers", "/app/invoices", "/app/subscriptions", "/app/customers/new", "/app/invoices/new", "/app/subscriptions/new"} {
		if r, err := noRedir.Get(base + p); err == nil {
			r.Body.Close()
			if r.StatusCode != http.StatusSeeOther {
				t.Errorf("gated %s anon = %d, want 303 redirect", p, r.StatusCode)
			}
		}
	}

	// Sign in, then every gated screen renders.
	jar, _ := cookiejar.New(nil)
	client := &http.Client{Jar: jar}
	if _, err := client.PostForm(base+"/auth/login", url.Values{"email": {"admin@meridian.dev"}, "password": {"change-me-now-123"}}); err != nil {
		t.Fatalf("login: %v", err)
	}
	for _, p := range []string{"/app", "/app/customers", "/app/invoices", "/app/subscriptions", "/app/customers/new", "/app/invoices/new", "/app/subscriptions/new"} {
		if code, body := e2eDo(t, client, "GET", base+p, ""); code != http.StatusOK {
			t.Errorf("authed screen %s = %d, want 200", p, code)
		} else if len(body) < 120 {
			t.Errorf("authed screen %s body suspiciously short (%d bytes)", p, len(body))
		}
	}

	// Full CRUD lifecycle for customers through its API + form screens.
	code, body := e2eDo(t, client, "POST", base+"/api/customers", `{"name": "e2e-name", "email": "e2e-email@example.com"}`)
	if code != http.StatusCreated {
		t.Fatalf("create customers = %d, want 201: %s", code, body)
	}
	id := e2eExtractID(body)
	if id == "" {
		t.Fatalf("create customers: no id in response: %s", body)
	}
	if code, body := e2eDo(t, client, "GET", base+"/app/customers/new", ""); code != http.StatusOK || !strings.Contains(body, "<form") {
		t.Errorf("new form customers = %d (has <form>? %v)", code, strings.Contains(body, "<form"))
	}
	if code, body := e2eDo(t, client, "GET", base+"/app/customers"+"/"+id, ""); code != http.StatusOK {
		t.Errorf("detail customers = %d, want 200", code)
	} else if !strings.Contains(body, "e2e-name") {
		t.Errorf("detail customers missing created value")
	}
	if code, body := e2eDo(t, client, "GET", base+"/app/customers"+"/"+id+"/edit", ""); code != http.StatusOK || !strings.Contains(body, "e2e-name") {
		t.Errorf("edit form customers = %d, prefilled? %v", code, strings.Contains(body, "e2e-name"))
	}
	if code, body := e2eDo(t, client, "PUT", base+"/api/customers"+"/"+id, `{"name": "e2e-updated"}`); code/100 != 2 {
		t.Errorf("update customers = %d: %s", code, body)
	}
	if code, _ := e2eDo(t, client, "DELETE", base+"/api/customers"+"/"+id, ""); code/100 != 2 {
		t.Errorf("delete customers = %d, want 2xx", code)
	}
	if code, _ := e2eDo(t, client, "GET", base+"/api/customers"+"/"+id, ""); code != http.StatusNotFound {
		t.Errorf("get deleted customers = %d, want 404", code)
	}

	// Scoping: an anonymous write to the access-/owner-scoped customers API is refused.
	if code, _ := e2eDo(t, http.DefaultClient, "POST", base+"/api/customers", `{"name": "e2e-name", "email": "e2e-email@example.com"}`); code != http.StatusUnauthorized && code != http.StatusForbidden {
		t.Errorf("anonymous write to customers = %d, want 401/403", code)
	}
}

func e2eFreeAddr(t *testing.T) string {
	t.Helper()
	l, err := net.Listen("tcp", "127.0.0.1:0")
	if err != nil {
		t.Fatal(err)
	}
	defer l.Close()
	return l.Addr().String()
}

func e2eWaitReady(t *testing.T, base string) {
	t.Helper()
	for i := 0; i < 100; i++ {
		if r, err := http.Get(base + "/"); err == nil {
			r.Body.Close()
			return
		}
		time.Sleep(100 * time.Millisecond)
	}
	t.Fatal("server did not become ready")
}

// e2eDo runs one request and returns the status code + body. A non-empty
// body is sent as JSON. Network errors fail the test.
func e2eDo(t *testing.T, client *http.Client, method, u, body string) (int, string) {
	t.Helper()
	var rdr io.Reader
	if body != "" {
		rdr = strings.NewReader(body)
	}
	req, err := http.NewRequest(method, u, rdr)
	if err != nil {
		t.Fatalf("%s %s: %v", method, u, err)
	}
	if body != "" {
		req.Header.Set("Content-Type", "application/json")
	}
	r, err := client.Do(req)
	if err != nil {
		t.Fatalf("%s %s: %v", method, u, err)
	}
	defer r.Body.Close()
	bb, _ := io.ReadAll(r.Body)
	return r.StatusCode, string(bb)
}

var e2eIDRe = regexp.MustCompile(`"id"\s*:\s*"([^"]+)"`)

func e2eExtractID(body string) string {
	if m := e2eIDRe.FindStringSubmatch(body); len(m) == 2 {
		return m[1]
	}
	return ""
}
