// Seeded by `gofastr generate --from=gofastr.yml`, then hand-evolved.
// Meridian is hand-maintained and NOT regenerable. See doc.go.

package main

import (
	"context"

	appui "github.com/DonaldMurillo/gofastr/core-ui/app"
	"github.com/DonaldMurillo/gofastr/core/render"
	"github.com/DonaldMurillo/gofastr/framework/ui"
	"github.com/DonaldMurillo/gofastr/framework/ui/resource"
)

// Meridian keeps its app-specific resource registry here. Generic list,
// detail, form, relation, filter, island, and aggregate behavior comes from
// framework/ui/resource.
var appResources = resource.Registry{}

// The hand-authored Meridian config still uses the names generated by the
// original blueprint. They name the supported framework resource types
// directly; no engine implementation remains in this app.
type ResourceConfig = resource.Config
type ResField = resource.Field
type RelSource = resource.Relation
type ResFilter = resource.Filter
type Transition = resource.Transition
type RelatedList = resource.RelatedList

// authError maps auth redirect codes to the alert rendered by Meridian's auth
// screens. It remains app-owned because the copy belongs to the product.
func authError(ctx context.Context) render.HTML {
	switch appui.QueryFromContext(ctx).Get("error") {
	case "":
		return ""
	case "invalid_credentials":
		return render.Text("Invalid email or password.")
	case "credentials_required":
		return render.Text("Enter your email and password.")
	case "rate_limit":
		return render.Text("Too many attempts. Please wait a moment and try again.")
	case "email_taken", "user_exists", "duplicate":
		return render.Text("That email is already registered.")
	default:
		return render.Text("Sorry, something went wrong. Please try again.")
	}
}

// These two names are used by Meridian's hand-authored overview screen. The
// calculations run in the shared registry engine.
func statValue(ctx context.Context, entity, agg, field, filterStr, format string) string {
	return appResources.StatValue(ctx, entity, agg, field, filterStr, format)
}

func groupBars(ctx context.Context, entity, groupBy string) []ui.BarChartBar {
	return appResources.GroupBars(ctx, entity, groupBy)
}
