package main

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func writeA11yTree(t *testing.T, files map[string]string) string {
	t.Helper()
	root := t.TempDir()
	for rel, body := range files {
		full := filepath.Join(root, rel)
		if err := os.MkdirAll(filepath.Dir(full), 0o755); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(full, []byte(body), 0o644); err != nil {
			t.Fatal(err)
		}
	}
	return root
}

const badScreen = `package app

import "github.com/DonaldMurillo/gofastr/core-ui/html"

func view() any {
	return html.Image(html.ImageConfig{Src: "/x.png"})
}
`

func TestAuditA11yFindsViolations(t *testing.T) {
	root := writeA11yTree(t, map[string]string{
		"app/screen.go": badScreen,
	})
	findings, err := auditA11y(root)
	if err != nil {
		t.Fatalf("auditA11y: %v", err)
	}
	if len(findings) != 1 {
		t.Fatalf("expected 1 finding, got %d: %+v", len(findings), findings)
	}
	f := findings[0]
	if f.File != filepath.Join("app", "screen.go") {
		t.Errorf("file should be root-relative, got %q", f.File)
	}
	if f.Line == 0 {
		t.Errorf("line must be set")
	}
}

func TestAuditA11ySkipsTestsVendorAndGenerated(t *testing.T) {
	root := writeA11yTree(t, map[string]string{
		"app/screen_test.go": badScreen,
		"vendor/dep/x.go":    badScreen,
		"gen/out.go":         "// Code generated by gofastr. DO NOT EDIT.\n" + badScreen,
	})
	findings, err := auditA11y(root)
	if err != nil {
		t.Fatalf("auditA11y: %v", err)
	}
	if len(findings) != 0 {
		t.Errorf("tests/vendor/generated files must be skipped, got %+v", findings)
	}
}

func TestFormatA11yReportGuidesTheFix(t *testing.T) {
	root := writeA11yTree(t, map[string]string{
		"app/screen.go": badScreen,
	})
	findings, err := auditA11y(root)
	if err != nil {
		t.Fatalf("auditA11y: %v", err)
	}
	out := formatA11yReport(findings)
	if !strings.Contains(out, "screen.go:6") {
		t.Errorf("report must carry file:line, got:\n%s", out)
	}
	if !strings.Contains(out, "fix:") {
		t.Errorf("report must include a fix hint per finding, got:\n%s", out)
	}
	if !strings.Contains(strings.ToLower(out), "alt") {
		t.Errorf("report must explain the Alt rule, got:\n%s", out)
	}
}

func TestFormatA11yReportCleanIsQuiet(t *testing.T) {
	out := formatA11yReport(nil)
	if !strings.Contains(strings.ToLower(out), "no accessibility issues") {
		t.Errorf("clean report should say so, got:\n%s", out)
	}
}

func TestBuildA11yGateBlocksOnViolations(t *testing.T) {
	root := writeA11yTree(t, map[string]string{
		"app/screen.go": badScreen,
	})
	if buildA11yGate(root) {
		t.Errorf("gate must block a tree with violations")
	}
}

func TestBuildA11yGatePassesCleanTree(t *testing.T) {
	root := writeA11yTree(t, map[string]string{
		"app/screen.go": `package app

import "github.com/DonaldMurillo/gofastr/core-ui/html"

func view() any {
	return html.Image(html.ImageConfig{Src: "/x.png", Alt: "Launch team photo"})
}
`,
	})
	if !buildA11yGate(root) {
		t.Errorf("gate must pass a clean tree")
	}
}

func TestParseA11yArgsSpaceAndEqualsForms(t *testing.T) {
	for _, args := range [][]string{
		{"--url", "http://localhost:8080", "--pages", "/a,/b"},
		{"--url=http://localhost:8080", "--pages=/a,/b"},
	} {
		root, base, pages, help, bad := parseA11yArgs(args)
		if bad != "" || help {
			t.Fatalf("args %v: unexpected badFlag=%q help=%v", args, bad, help)
		}
		if root != "." || base != "http://localhost:8080" {
			t.Errorf("args %v: root=%q base=%q", args, root, base)
		}
		if len(pages) != 2 || pages[0] != "/a" || pages[1] != "/b" {
			t.Errorf("args %v: pages=%v", args, pages)
		}
	}
}

func TestParseA11yArgsRootAndBadFlag(t *testing.T) {
	root, _, _, _, bad := parseA11yArgs([]string{"./app", "--nope"})
	if root != "./app" {
		t.Errorf("root=%q", root)
	}
	if bad != "--nope" {
		t.Errorf("badFlag=%q", bad)
	}
}
