package main

import (
	"fmt"
	"strings"

	"github.com/gofastr/gofastr/framework"
)

// renderColumns builds entities/columns.go — typed column constants and
// include-name constants for every entity. Codegen-only file; the framework
// itself defines NewStringColumn etc. so the generator just instantiates.
func renderColumns(decls []framework.EntityDeclaration) string {
	var sb strings.Builder
	sb.WriteString(`// Code generated by gofastr. DO NOT EDIT.
package entities

import (
	"github.com/gofastr/gofastr/framework"
)

`)
	for _, decl := range decls {
		struct_ := toCamelCase(decl.Name)
		sb.WriteString("// ====== " + struct_ + " column references ======\n\n")
		sb.WriteString("var (\n")
		// Always emit an ID column (PK) — the framework auto-adds it on Define.
		sb.WriteString(fmt.Sprintf("\t%sID = framework.NewUUIDColumn(\"id\")\n", struct_))
		for _, field := range decl.Fields {
			if field.Name == "id" {
				continue
			}
			sb.WriteString(fmt.Sprintf("\t%s%s = %s(%q)\n",
				struct_, toCamelCase(field.Name),
				columnConstructor(field.Type), field.Name))
		}
		sb.WriteString(")\n\n")

		// Include name constants per relation.
		if len(decl.Relations) > 0 {
			sb.WriteString("// " + struct_ + " include names — pass to framework.TypedQuery.Include or repo.Get(..., includes...).\n")
			sb.WriteString("const (\n")
			for _, rel := range decl.Relations {
				sb.WriteString(fmt.Sprintf("\t%sIncl%s = %q\n",
					struct_, toCamelCase(rel.Name), rel.Name))
			}
			sb.WriteString(")\n\n")
		}
	}
	return sb.String()
}

// columnConstructor maps a schema field type to the framework constructor
// that produces a typed column for it.
func columnConstructor(value string) string {
	switch strings.ToLower(value) {
	case "int", "integer":
		return "framework.NewIntColumn"
	case "float", "number", "decimal":
		return "framework.NewFloatColumn"
	case "bool", "boolean":
		return "framework.NewBoolColumn"
	case "timestamp", "datetime", "date":
		return "framework.NewTimestampColumn"
	case "uuid", "relation":
		return "framework.NewUUIDColumn"
	default:
		// String, Text, Enum, JSON, Image, File all get StringColumn — they're
		// all stored as TEXT and queried by string equality / LIKE.
		return "framework.NewStringColumn"
	}
}

// renderRepos builds entities/repo.go — typed repositories per entity, each
// wrapping a CrudHandler so generated callers get Create/Get/Update/Delete +
// Query + WithTx without re-implementing CRUD plumbing.
func renderRepos(decls []framework.EntityDeclaration) string {
	var sb strings.Builder
	sb.WriteString(`// Code generated by gofastr. DO NOT EDIT.
package entities

import (
	"context"
	"database/sql"

	"github.com/gofastr/gofastr/framework"
)

`)
	for _, decl := range decls {
		struct_ := toCamelCase(decl.Name)
		sb.WriteString(fmt.Sprintf(`// %sRepo is the typed repository for %s rows.
type %sRepo struct {
	handler *framework.CrudHandler
}

// New%sRepo wires a typed repo against the App's %q entity. Panics if the
// entity hasn't been registered yet.
func New%sRepo(app *framework.App) *%sRepo {
	entity, err := app.Registry.Get(%q)
	if err != nil {
		panic("entities: %s not registered: " + err.Error())
	}
	h := framework.NewCrudHandler(entity, app.DB)
	h.JSONCase = app.JSONCasing()
	h.Hooks = app.HookRegistry(%q)
	h.Storage = app.Storage
	h.Events = app.Events()
	h.Registry = app.Registry
	return &%sRepo{handler: h}
}

// Handler returns the underlying CrudHandler — useful for advanced wiring or
// to feed the typed-query primitives directly.
func (r *%sRepo) Handler() *framework.CrudHandler { return r.handler }

// WithTx returns a tx-bound copy of the repo. Calls within a hook can use
// framework.TxFromContext(ctx) and pass the result here to chain typed CRUD
// atomically with the parent operation.
func (r *%sRepo) WithTx(tx *sql.Tx) *%sRepo {
	h := *r.handler
	h.DB = tx
	return &%sRepo{handler: &h}
}

// Create persists row and back-fills server-generated fields onto it.
func (r *%sRepo) Create(ctx context.Context, row *%s) error {
	body, err := framework.MarshalEntity(row)
	if err != nil {
		return err
	}
	out, err := r.handler.CreateOne(ctx, body)
	if err != nil {
		return err
	}
	return framework.UnmarshalEntity(out, row)
}

// Get fetches a row by id with optional eager-loaded includes.
func (r *%sRepo) Get(ctx context.Context, id string, includes ...string) (*%s, error) {
	out, err := r.handler.GetOne(ctx, id, includes)
	if err != nil {
		return nil, err
	}
	var row %s
	if err := framework.UnmarshalEntity(out, &row); err != nil {
		return nil, err
	}
	return &row, nil
}

// Update merges fields from row into the persisted record by id and refreshes
// row with the post-update state.
func (r *%sRepo) Update(ctx context.Context, id string, row *%s) error {
	body, err := framework.MarshalEntity(row)
	if err != nil {
		return err
	}
	delete(body, "id") // id is taken from the path arg, not the body
	out, err := r.handler.UpdateOne(ctx, id, body)
	if err != nil {
		return err
	}
	return framework.UnmarshalEntity(out, row)
}

// Delete removes the row by id (or soft-deletes if SoftDelete is enabled on
// the entity).
func (r *%sRepo) Delete(ctx context.Context, id string) error {
	return r.handler.DeleteOne(ctx, id)
}

// Query starts a typed query for chaining Where/Order/Limit/Include and
// finishing with Find/First/Count.
func (r *%sRepo) Query() *framework.TypedQuery[%s] {
	return framework.NewTypedQuery[%s](r.handler)
}

`,
			// Repo struct doc + type
			struct_, decl.Name,
			struct_,
			// Constructor
			struct_, decl.Name, struct_, struct_, decl.Name, decl.Name, decl.Name, struct_,
			// Handler accessor
			struct_,
			// WithTx
			struct_, struct_, struct_,
			// Create
			struct_, struct_,
			// Get
			struct_, struct_, struct_,
			// Update
			struct_, struct_,
			// Delete
			struct_,
			// Query
			struct_, struct_, struct_,
		))
	}
	return sb.String()
}
