package main

import (
	"context"
	"fmt"
	"go/ast"
	"go/format"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/DonaldMurillo/gofastr/codegen"
	"github.com/DonaldMurillo/gofastr/framework"
	fwentity "github.com/DonaldMurillo/gofastr/framework/entity"
)

func runGenerate(args []string) {
	if len(args) == 0 || strings.HasPrefix(args[0], "--") {
		for _, a := range args {
			if a == "--watch" {
				runGenerateWatch(args)
				return
			}
		}
		generateProject(args)
		return
	}

	resourceType := args[0]
	switch resourceType {
	case "all":
		generateProject(args[1:])
	case "entity":
		generateScaffoldEntity(args[1:])
	case "screen":
		generateScaffoldScreen(args[1:])
	case "cli":
		runGenerateCLI(args[1:])
	case "ts", "typescript":
		fail("TypeScript codegen has been removed. Use gofastr.codegen.yml with a project extension to generate frontend artifacts.")
		info("See framework/docs/content/codegen.md for the extension protocol.")
		osExit(1)
	default:
		fail("Unknown resource type: %s", resourceType)
		info("Supported: all, entity, screen, cli")
		osExit(1)
	}
}

// generateScaffoldEntity is the `gofastr generate entity <name>` quick-stub
// path. It synthesizes a one-entity blueprint fragment — a single placeholder
// "name" field the user renames — and routes it through the SAME additive
// machinery as `--add` (generateBlueprint with add forced on). No yml is
// required; the stub is a starting point the user immediately edits, while a
// blueprint yml remains the way to express real intent. CRUD stays default,
// so the entity also gains a JSON API out of the box.
func generateScaffoldEntity(args []string) {
	name, opts, ok := parseScaffoldArgs(args, "entity")
	if !ok {
		osExit(1)
		return
	}
	bp := Blueprint{
		Entities: []framework.EntityDeclaration{{
			Name:   name,
			Fields: []framework.FieldDeclaration{{Name: "name", Type: "string", Required: true}},
		}},
	}
	opts.add = true
	generateBlueprint(bp, opts)
	if !opts.dryRun && !opts.json {
		info("Next: rename the placeholder field in entities/%s, then run your app.", entityFileName(name))
	}
}

// generateScaffoldScreen is the `gofastr generate screen <name>` quick-stub
// path. It synthesizes a one-screen fragment — route /<kebab-name>, title
// <Title name>, a heading plus a paragraph noting it is a generated stub —
// and routes it through the additive machinery so screen order continuity,
// skip-existing, and the legacy-layout refusal all hold for free.
func generateScaffoldScreen(args []string) {
	name, opts, ok := parseScaffoldArgs(args, "screen")
	if !ok {
		osExit(1)
		return
	}
	title := toDisplayName(name)
	bp := Blueprint{
		Screens: []BlueprintScreen{{
			Name:  name,
			Route: "/" + strings.ReplaceAll(toSnakeCase(name), "_", "-"),
			Title: title,
			Body: []BlueprintBlock{
				{Type: "heading", Level: 1, Text: title},
				{Type: "text", Text: "This screen is a stub generated by `gofastr generate screen`. Edit its Render method to build your UI."},
			},
		}},
	}
	opts.add = true
	generateBlueprint(bp, opts)
	if !opts.dryRun && !opts.json {
		info("Next: edit the Render method in %s to build your UI.", screenFileName(name))
	}
}

// parseScaffoldArgs parses the flags accepted by the `generate entity|screen
// <name>` scaffold subcommands: exactly one positional name plus --out,
// --dry-run, and --json. --force and --add are rejected (scaffolding is
// additive by definition — it never overwrites existing files), and any extra
// positional or unknown flag fails with usage guidance. It returns the parsed
// name and options; ok is false (after printing a failure) when the arguments
// are invalid, so the caller exits non-zero.
func parseScaffoldArgs(args []string, kind string) (name string, opts generateOptions, ok bool) {
	var positionals []string
	for i := 0; i < len(args); i++ {
		arg := args[i]
		switch {
		case arg == "--dry-run":
			opts.dryRun = true
		case arg == "--json":
			opts.json = true
		case strings.HasPrefix(arg, "--out="):
			opts.outputDir = strings.TrimPrefix(arg, "--out=")
			opts.outputSet = true
		case arg == "--out":
			if i+1 >= len(args) || strings.HasPrefix(args[i+1], "--") {
				fail("--out requires a directory argument")
				info("Usage: gofastr generate %s <name> [--out=DIR] [--dry-run] [--json]", kind)
				return "", opts, false
			}
			i++
			opts.outputDir = args[i]
			opts.outputSet = true
		case arg == "--force", arg == "--add":
			fail("%q is not supported on `gofastr generate %s` — scaffolding is additive (it never overwrites existing files)", arg, kind)
			info("Usage: gofastr generate %s <name> [--out=DIR] [--dry-run] [--json]", kind)
			return "", opts, false
		case strings.HasPrefix(arg, "--"):
			fail("Unknown flag %q for `gofastr generate %s`", arg, kind)
			info("Usage: gofastr generate %s <name> [--out=DIR] [--dry-run] [--json]", kind)
			return "", opts, false
		default:
			positionals = append(positionals, arg)
		}
	}
	if len(positionals) != 1 {
		fail("`gofastr generate %s` requires exactly one name argument", kind)
		info("Usage: gofastr generate %s <name> [--out=DIR] [--dry-run] [--json]", kind)
		return "", opts, false
	}
	return positionals[0], opts, true
}

// generateProject is the `gofastr generate` entrypoint. The gofastr.yml
// blueprint is the single declaration format, named explicitly via --from.
// With no blueprint, a gofastr.codegen.yml extension config (the project
// extension protocol) is honored; failing both, we error with guidance.
//
// Auto-discovery of gofastr.yml is deliberately avoided: that filename is
// also used for the isolation config (`gofastr init`), so silently treating
// it as a blueprint would misfire.
func generateProject(args []string) {
	options := parseGenerateOptions(args)
	if options.add && options.force {
		fail("--add and --force are mutually exclusive (--add never overwrites; --force overwrites everything)")
		osExit(1)
	}
	if options.add && options.from == "" {
		fail("--add requires --from=<blueprint> (additive generation only applies to blueprints)")
		osExit(1)
	}
	if options.from != "" {
		generateFromBlueprint(options)
		return
	}
	discovered, err := discoverGenerateConfig(options)
	if err != nil {
		if options.dryRun && options.json {
			printGeneratedErrorsJSON(err)
			osExit(1)
		}
		fail("Failed to load codegen config: %v", err)
		osExit(1)
	}
	if discovered.Found {
		generateFromCodegenConfig(options, discovered)
		return
	}
	fail("Nothing to generate.")
	info("Pass --from=<blueprint.yml> to generate from a blueprint, or add a gofastr.codegen.yml extension config. See `gofastr docs blueprints`.")
	osExit(1)
}

type generateOptions struct {
	outputDir  string
	configPath string
	from       string
	clean      bool
	cleanSet   bool
	dryRun     bool
	json       bool
	outputSet  bool
	force      bool
	add        bool
}

func parseGenerateOptions(args []string) generateOptions {
	options := generateOptions{outputDir: filepath.Join("gen", "entities"), clean: true}
	for i := 0; i < len(args); i++ {
		arg := args[i]
		// Space form for the value-taking flags: `--from x` ≡ `--from=x`.
		// The next arg is consumed only when it is not itself a flag —
		// silently dropping `--from x` used to yield a misleading
		// "Nothing to generate".
		nextValue := func() (string, bool) {
			if i+1 < len(args) && !strings.HasPrefix(args[i+1], "--") {
				i++
				return args[i], true
			}
			return "", false
		}
		switch {
		case arg == "--dry-run":
			options.dryRun = true
		case arg == "--json":
			options.json = true
		case arg == "--clean":
			options.clean = true
			options.cleanSet = true
		case arg == "--no-clean":
			options.clean = false
			options.cleanSet = true
		case arg == "--force":
			options.force = true
		case arg == "--add":
			options.add = true
		case strings.HasPrefix(arg, "--config="):
			options.configPath = strings.TrimPrefix(arg, "--config=")
		case arg == "--config":
			if v, ok := nextValue(); ok {
				options.configPath = v
			}
		case strings.HasPrefix(arg, "--from="):
			options.from = strings.TrimPrefix(arg, "--from=")
		case arg == "--from":
			if v, ok := nextValue(); ok {
				options.from = v
			}
		case strings.HasPrefix(arg, "--out="):
			options.outputDir = strings.TrimPrefix(arg, "--out=")
			options.outputSet = true
		case arg == "--out":
			if v, ok := nextValue(); ok {
				options.outputDir = v
				options.outputSet = true
			}
		}
	}
	return options
}

func discoverGenerateConfig(options generateOptions) (codegen.Discovery, error) {
	if options.configPath != "" {
		configPath, err := filepath.Abs(options.configPath)
		if err != nil {
			return codegen.Discovery{}, err
		}
		cfg, err := codegen.LoadConfig(configPath)
		if err != nil {
			return codegen.Discovery{}, err
		}
		return codegen.Discovery{Path: configPath, ProjectDir: filepath.Dir(configPath), Config: cfg, Found: true}, nil
	}
	return codegen.DiscoverConfig(".")
}

func applyGenerateOverrides(cfg *codegen.Config, options generateOptions) {
	if options.outputSet {
		cfg.Codegen.Output = options.outputDir
	}
	if options.cleanSet {
		cfg.Codegen.Clean = &options.clean
	}
}

func generateFromCodegenConfig(options generateOptions, discovery codegen.Discovery) {
	restore, err := enterCodegenProjectDir(discovery)
	if err != nil {
		if options.dryRun && options.json {
			printGeneratedErrorsJSON(err)
			osExit(1)
		}
		fail("Failed to enter codegen project: %v", err)
		osExit(1)
	}
	defer restore()
	cfg := discovery.Config
	applyGenerateOverrides(&cfg, options)
	if err := validateOutputDir(cfg.Codegen.Output); err != nil {
		if options.dryRun && options.json {
			printGeneratedErrorsJSON(err)
			osExit(1)
		}
		fail("%v", err)
		osExit(1)
	}
	reg := codegen.NewRegistry()
	if err := reg.RegisterCommandExtensions(cfg.Codegen, os.Stderr); err != nil {
		if options.dryRun && options.json {
			printGeneratedErrorsJSON(err)
			osExit(1)
		}
		fail("Code generation setup failed: %v", err)
		osExit(1)
	}
	genCtx, err := reg.Run(context.Background(), ".", cfg)
	if err != nil {
		if options.dryRun && options.json {
			printGeneratedErrorsJSON(err)
			osExit(1)
		}
		fail("Code generation failed: %v", err)
		osExit(1)
	}
	files := genCtx.Files.All()
	if options.dryRun {
		if options.json {
			printCodegenFilesJSON(files)
			return
		}
		info("Would generate %d files in %s:", len(files), cfg.Codegen.Output)
		for _, file := range files {
			fmt.Printf("    %s\n", filepath.Join(cfg.Codegen.Output, file.Path))
		}
		return
	}
	if discovery.Path == "" && codegen.CleanEnabled(cfg.Codegen) {
		if err := safeCleanOutputDir(cfg.Codegen.Output); err != nil {
			fail("Failed to clean %s: %v", cfg.Codegen.Output, err)
			osExit(1)
		}
	}
	if err := codegen.WriteFiles(genCtx.Files, codegen.WriteOptions{OutputRoot: cfg.Codegen.Output, Clean: discovery.Path != "" && codegen.CleanEnabled(cfg.Codegen), SkipManifest: discovery.Path == ""}); err != nil {
		fail("Failed to write generated files: %v", err)
		osExit(1)
	}
	if options.json {
		printCodegenFilesJSON(files)
		return
	}
	success("Generated %d file(s) in %s", len(files), cfg.Codegen.Output)
}

func enterCodegenProjectDir(discovery codegen.Discovery) (func(), error) {
	projectDir := discovery.ProjectDir
	if strings.TrimSpace(projectDir) == "" || projectDir == "." {
		return func() {}, nil
	}
	cwd, err := os.Getwd()
	if err != nil {
		return nil, err
	}
	if err := os.Chdir(projectDir); err != nil {
		return nil, err
	}
	return func() { _ = os.Chdir(cwd) }, nil
}

func generateFromBlueprint(options generateOptions) {
	// Additive mode defers validation: a partial yml may reference entities
	// that live in the target project rather than in the fragment, so the
	// fragment is only validated after the project's entities are unioned in
	// (below, once writeRoot is known).
	var bp Blueprint
	var err error
	if options.add {
		bp, err = loadBlueprintPath(options.from, false)
	} else {
		bp, err = loadBlueprint(options.from)
	}
	if err != nil {
		if options.dryRun && options.json {
			printGeneratedErrorsJSON(err)
			osExit(1)
		}
		fail("Failed to load blueprint: %v", err)
		osExit(1)
	}
	generateBlueprint(bp, options)
}

// generateBlueprint runs the blueprint generation pipeline against an
// already-loaded Blueprint. generateFromBlueprint (the --from / --add yml
// path) and the `generate entity|screen <name>` scaffold subcommands (which
// synthesize a fragment in memory rather than loading yml) both route here,
// so the additive machinery — union, order offsets, skip-existing partition,
// legacy-layout refusal, client.go staleness warn, and the --dry-run/--json
// reporting shapes — has exactly one implementation. options.add selects the
// additive branch; the scaffold subcommands force it on (scaffolding is
// additive by definition — it never overwrites owned files).
func generateBlueprint(bp Blueprint, options generateOptions) {
	// Generated imports are <module>/<output-dir> with the output dir
	// relative to the working directory — so the go.mod that matters is the
	// one enclosing the cwd. Derive app.module from it when omitted; refuse
	// a conflicting declaration (the output would not compile).
	if err := resolveBlueprintModule(&bp, "."); err != nil {
		if options.dryRun && options.json {
			printGeneratedErrorsJSON(err)
			osExit(1)
		}
		fail("%v", err)
		osExit(1)
	}
	// The blueprint is a one-shot generator: it emits ordinary owned app code
	// (flat package main at the module root by default, or a subpackage under
	// --out=DIR / app.output_dir), then gets out of the way. There is no
	// regen/merge workflow — generating into a directory that already holds any
	// target file REFUSES (see below), and --force is the explicit overwrite
	// escape. No quarantined gen/, no clean-wipe.
	outDir := ""
	switch {
	case options.outputSet:
		outDir = options.outputDir
	case bp.App.OutputDir != "":
		outDir = bp.App.OutputDir
	}
	outDir = strings.TrimPrefix(filepath.ToSlash(outDir), "./")
	outDir = strings.TrimSuffix(outDir, "/")
	if outDir == "." {
		outDir = ""
	}
	// Keep the blueprint's view of the output dir in sync so renderBlueprintMain
	// derives the same import base.
	bp.App.OutputDir = outDir
	// Unscoped PII is a warning here (generation proceeds) and an error
	// from `gofastr validate`. Suppressed in --json mode so stdout stays
	// machine-parseable; JSON consumers get the finding from validate.
	if !options.json {
		piiFlagged := map[string]bool{}
		for _, f := range lintUnscopedPII(bp) {
			piiFlagged[f.Entity] = true
			warn("%s", f.Message())
		}
		// Broader net: any unscoped auto-exposed entity lets every OTHER
		// authenticated user read/write its rows — warn even when no
		// field name looks like PII (the token list can't know
		// "journal_entry" is private). Auto-CRUD already requires a
		// session by default (issue #65), so this is cross-user
		// exposure, not anonymous access.
		for _, f := range lintUnscopedEntities(bp) {
			if piiFlagged[f.Entity] {
				continue // already carried the stronger PII warning
			}
			warn("%s", f.Message())
		}
		// public: true is a full, deliberate opt-out of the session
		// requirement — the ACTUAL anonymous-access surface. Always
		// surfaced (never suppressed by the PII/unscoped warnings above)
		// so a generated app's open surface is never silent.
		for _, f := range lintPublicEntities(bp) {
			warn("%s", f.Message())
		}
		// dev_mode defaults to true (plain-HTTP cookies + per-process JWT
		// secret) because a fresh generated app has no HTTPS. Loudly say
		// so on every generate until the blueprint opts out.
		if bp.App.Auth.Enabled && bp.App.Auth.DevMode {
			warn("app.auth runs in dev mode: HTTP-friendly cookies and a per-process JWT secret. Before deploying, set dev_mode: false and jwt_secret under app.auth (requires HTTPS) and regenerate. See `gofastr docs blueprints`.")
		}
	}
	// Only a non-root subdirectory needs the clean-safety validation; the
	// module root is written file-by-file and never wiped.
	if outDir != "" {
		if err := validateOutputDir(outDir); err != nil {
			if options.dryRun && options.json {
				printGeneratedErrorsJSON(err)
				osExit(1)
			}
			fail("%v", err)
			osExit(1)
		}
	}
	// writeRoot is where files land on disk — the output dir, or "." for
	// the module root. Computed early so additive generation can read the
	// existing entities/ before rendering.
	writeRoot := outDir
	if writeRoot == "" {
		writeRoot = "."
	}
	// Additive mode: entity orders must continue after the project's existing
	// set so RegisterAll's declaration order and pack recovery stay coherent.
	entityOffset, screenOffset := 0, 0
	if options.add {
		// A pre-0.15 aggregated entities/register.go holds the app.Entity
		// calls inline and has no registrar seam — a per-entity file dropped
		// next to it references types that don't exist and the project stops
		// compiling. Refuse rather than emit broken output.
		if legacy, lerr := packReadLegacyRegister(filepath.Join(writeRoot, "entities", "register.go")); lerr == nil && len(legacy) > 0 {
			lerr = fmt.Errorf("entities/ uses the pre-0.15 aggregated layout, which --add cannot extend — recover your blueprint with `gofastr pack`, merge the new pieces into it, and regenerate with `gofastr generate --from=<blueprint> --force`")
			if options.dryRun && options.json {
				printGeneratedErrorsJSON(lerr)
				osExit(1)
			}
			fail("%v", lerr)
			osExit(1)
		}
		// Symmetric guard for screens: a pre-per-screen aggregated screens.go
		// holds the screen structs + the app.go registrations inline. A
		// per-screen file dropped next to it self-registers against a seam
		// that doesn't exist, so the project stops compiling. Refuse.
		if packHasAggregatedScreens(writeRoot) {
			serr := fmt.Errorf("screens use the pre-per-screen aggregated layout (screens.go), which --add cannot extend — recover your blueprint with `gofastr pack`, merge the new pieces into it, and regenerate with `gofastr generate --from=<blueprint> --force`")
			if options.dryRun && options.json {
				printGeneratedErrorsJSON(serr)
				osExit(1)
			}
			fail("%v", serr)
			osExit(1)
		}
		// Union the project's existing entities into the fragment so (a) a
		// screens-only fragment may reference an entity that lives in the
		// project, and (b) validation sees the same world rendering will.
		// The recovered entities come first in their authored order; their
		// files already exist so they are skipped at write time — only the
		// fragment's genuinely-new pieces land on disk. On a name collision
		// the project's declaration wins (re-declaring is a documented no-op).
		recovered, rerr := packReadEntities(writeRoot)
		if rerr != nil {
			recovered = nil // unreadable entities dir: validate the fragment alone
		}
		// Key redeclaration detection on the on-disk file name, not the raw
		// entity name: "Posts" and "posts" both render to entities/posts.go
		// and the same Go type, so a case/separator variant IS a
		// redeclaration. Keying on the raw name would let the variant slip
		// past as "new", then get silently skipped when its file collides —
		// dropping the entity the user asked to add.
		have := make(map[string]bool, len(recovered))
		for _, d := range recovered {
			have[entityFileName(d.Name)] = true
		}
		merged := make([]framework.EntityDeclaration, 0, len(recovered)+len(bp.Entities))
		merged = append(merged, recovered...)
		for _, d := range bp.Entities {
			if !have[entityFileName(d.Name)] {
				merged = append(merged, d)
			}
		}
		bp.Entities = merged
		// Screens aren't rendered from the union (only entities are), so
		// validateBlueprint can't see the project's existing screen routes.
		// Reject a fragment screen whose route collides with one already
		// mounted in the project — otherwise two site.Register calls hit the
		// same path and the new screen silently shadows (or is shadowed by)
		// the old. The taken set is scanned from the actual Register calls in
		// the generated source, so it INCLUDES synthesized CRUD form routes
		// (/new, /{id}/edit) that packReadScreens drops — a fragment claiming
		// one of those would otherwise double-register invisibly. A fragment
		// screen whose own file already exists is skipped by the write
		// partition below (idempotent re-add, matching entity redeclaration),
		// so it is exempt from the hard collision error here.
		taken := registeredScreenRoutes(writeRoot)
		for _, s := range bp.Screens {
			if !taken[s.Route] {
				continue
			}
			if fileExistsUnder(writeRoot, screenFileName(s.Name)) {
				continue // same screen being re-added → handled as skip-existing
			}
			cerr := fmt.Errorf("screen %q route %q collides with a route already mounted in the project — pick a different route (--add cannot replace an owned screen; use --force to regenerate the whole app)", s.Name, s.Route)
			if options.dryRun && options.json {
				printGeneratedErrorsJSON(cerr)
				osExit(1)
			}
			fail("Failed to load blueprint: %v", cerr)
			osExit(1)
		}
		if verr := validateBlueprint(bp); verr != nil {
			if options.dryRun && options.json {
				printGeneratedErrorsJSON(verr)
				osExit(1)
			}
			fail("Failed to load blueprint: %v", verr)
			osExit(1)
		}
		// New entities sit at indices len(recovered).. in the union; the
		// offset makes the first of them land at (max existing order)+1.
		// Distinct orders guarantee max+1 >= len(recovered), so this is
		// never negative; clamp anyway against corrupted projects.
		entityOffset = maxExistingEntityOrder(writeRoot) - len(recovered)
		if entityOffset < 0 {
			entityOffset = 0
		}
		screenOffset = maxExistingScreenOrder(writeRoot)
	}
	var files []generatedFile
	var err error
	if options.add {
		files, err = renderBlueprintFilesWithOrder(bp, entityOffset, screenOffset)
	} else {
		files, err = renderBlueprintFiles(bp)
	}
	if err != nil {
		if options.dryRun && options.json {
			printGeneratedErrorsJSON(err)
			osExit(1)
		}
		fail("Blueprint code generation failed: %v", err)
		osExit(1)
	}
	// Self-hosted fonts: if the generate-time fetch couldn't reach the CDN,
	// the app still ships (system fonts render) but the intended type is
	// missing. Say so LOUDLY with the exact files to drop in — the CSP
	// (default-src 'self') blocks the Google CDN at runtime, so the woff2
	// must be self-hosted; there is no silent fallback to a webfont link.
	if !options.json {
		if missing := blueprintMissingFontSlugs(bp, files); len(missing) > 0 {
			warn("could not fetch %d webfont file(s) — the app will fall back to system fonts until you supply them. Drop the matching .woff2 into your project so these paths exist: %s. (The strict CSP blocks the Google Fonts CDN at runtime, so fonts must be self-hosted.)", len(missing), strings.Join(missing, ", "))
		}
	}
	displayDir := outDir
	if displayDir == "" {
		displayDir = "the module root"
	}
	// Additive generation: never overwrite. Partition into written (absent)
	// and skipped (exists), write only the new files, and report loudly.
	if options.add {
		var written, skipped []generatedFile
		for _, file := range files {
			if _, statErr := os.Stat(filepath.Join(writeRoot, file.name)); statErr == nil {
				skipped = append(skipped, file)
			} else {
				written = append(written, file)
			}
		}
		skipNames := make([]string, len(skipped))
		for i, f := range skipped {
			skipNames[i] = f.name
		}
		sort.Strings(skipNames)

		if options.dryRun {
			if options.json {
				printAdditiveFilesJSON(written, skipNames)
				return
			}
			info("Would add %d file(s) in %s:", len(written), displayDir)
			for _, file := range written {
				fmt.Printf("    %s\n", filepath.Join(outDir, file.name))
			}
			if len(skipped) > 0 {
				info("Would skip %d existing:", len(skipped))
				for _, name := range skipNames {
					fmt.Printf("    %s\n", filepath.Join(outDir, name))
				}
			}
			return
		}
		// Write only the new files.
		if len(written) > 0 {
			fileSet, werr := fileSetFromGeneratedFiles(written, "blueprint")
			if werr != nil {
				fail("Blueprint code generation failed: %v", werr)
				osExit(1)
			}
			writeOpts := codegen.WriteOptions{
				OutputRoot:   writeRoot,
				SkipManifest: true,
				Conflict:     codegen.ConflictOverwrite,
			}
			if werr := codegen.WriteFiles(fileSet, writeOpts); werr != nil {
				fail("Failed to write generated files: %v", werr)
				osExit(1)
			}
		}
		// Warn about stale client.go — a silently-stale generated API surface
		// is a trap the other aggregates aren't.
		if !options.json {
			hasNewEntities := false
			for _, f := range written {
				name := filepath.ToSlash(f.name)
				if strings.HasPrefix(name, "entities/") && name != "entities/register.go" && !strings.HasPrefix(name, "entities/client/") {
					hasNewEntities = true
					break
				}
			}
			if hasNewEntities {
				for _, f := range skipped {
					if filepath.ToSlash(f.name) == "entities/client/client.go" {
						warn("entities/client/client.go already exists and was not updated — it does not include the new entities. Regenerate it from a full blueprint with --force, or extend it by hand.")
						break
					}
				}
			}
			// The added pieces self-register against their seam, but the seam
			// only runs if the owned shell calls it. Fresh generates always
			// emit both call sites; if this project's owned file lost (or
			// predates) its call, say exactly which line to add — otherwise
			// the new files compile and then silently never register/mount.
			hasNewScreens := false
			for _, f := range written {
				if strings.HasPrefix(filepath.ToSlash(f.name), "screen_") {
					hasNewScreens = true
					break
				}
			}
			if hasNewEntities && missingCallSite(writeRoot, "main.go", "entities.RegisterAll(") {
				warn("main.go never calls entities.RegisterAll — the added entities will not register. Add `entities.RegisterAll(fwApp)` (importing your module's entities package) to main.go.")
			}
			if hasNewScreens && missingCallSite(writeRoot, "app.go", "mountGenerated(") {
				warn("app.go never calls mountGenerated — the added screens will not mount. Add `mountGenerated(fwApp, site, db)` inside RegisterGenerated in app.go.")
			}
		}
		if options.json {
			printAdditiveFilesJSON(written, skipNames)
			return
		}
		if len(skipped) > 0 {
			success("Added %d file(s) in %s (skipped %d existing)", len(written), displayDir, len(skipped))
			info("Skipped existing files:")
			for _, name := range skipNames {
				fmt.Printf("    %s\n", filepath.Join(outDir, name))
			}
		} else {
			success("Added %d file(s) in %s", len(written), displayDir)
		}
		return
	}
	if options.dryRun {
		if options.json {
			printGeneratedFilesJSON(files)
			return
		}
		info("Would generate %d files in %s:", len(files), displayDir)
		for _, file := range files {
			fmt.Printf("    %s\n", filepath.Join(outDir, file.name))
		}
		return
	}
	fileSet, err := fileSetFromGeneratedFiles(files, "blueprint")
	if err != nil {
		fail("Blueprint code generation failed: %v", err)
		osExit(1)
	}
	// One-shot: the emitted files are ordinary owned app code, not a
	// re-runnable scaffold. Refuse to clobber an existing project — if any
	// target file already exists, list the conflicts and stop. --force is the
	// explicit overwrite escape.
	if !options.force {
		var conflicts []string
		for _, file := range files {
			if _, statErr := os.Stat(filepath.Join(writeRoot, file.name)); statErr == nil {
				conflicts = append(conflicts, filepath.Join(outDir, file.name))
			}
		}
		if len(conflicts) > 0 {
			sort.Strings(conflicts)
			cerr := fmt.Errorf("generate is one-shot and would overwrite existing files: %s — the emitted code is yours to own. To ADD to an existing project (new entities/screens) use `gofastr generate --add --from=<blueprint>`; to overwrite everything, re-run with --force", strings.Join(conflicts, ", "))
			if options.json {
				printGeneratedErrorsJSON(cerr)
				osExit(1)
			}
			fail("%v", cerr)
			osExit(1)
		}
	}
	writeOpts := codegen.WriteOptions{
		OutputRoot:   writeRoot,
		SkipManifest: true,
		Conflict:     codegen.ConflictOverwrite,
	}
	if err := codegen.WriteFiles(fileSet, writeOpts); err != nil {
		fail("Failed to write generated files: %v", err)
		osExit(1)
	}
	if options.json {
		printGeneratedFilesJSON(files)
		return
	}
	success("Generated %d file(s) in %s", len(files), displayDir)
	devCmd := "gofastr dev"
	if outDir != "" && outDir != "." {
		// output_dir blueprints put the app in a subpackage — plain
		// `gofastr dev` would watch/build a root with no main package.
		devCmd = "gofastr dev --dir " + outDir
	}
	fmt.Println()
	fmt.Println("  Next steps:")
	fmt.Println("    go mod tidy          — the generated code pulls new imports")
	fmt.Printf("    %-20s — dev server with hot-reload\n", devCmd)
}

type generatedFile struct {
	name    string
	content string
}

func fileSetFromGeneratedFiles(files []generatedFile, owner string) (*codegen.FileSet, error) {
	fileSet := codegen.NewFileSet()
	for _, file := range files {
		content := file.content
		// gofmt generated Go so the emitted package is clean, readable, and
		// stable across regenerations. On a (bug-induced) parse error, keep
		// the raw output so the failure surfaces in the compiler, not here.
		if strings.HasSuffix(file.name, ".go") {
			if formatted, err := format.Source([]byte(content)); err == nil {
				content = string(formatted)
			}
		}
		if err := fileSet.Add(codegen.GeneratedFile{Path: file.name, Content: content, Owner: owner}); err != nil {
			return nil, err
		}
	}
	return fileSet, nil
}

// renderGeneratedProject emits the entities package for a set of entity
// declarations. Output is ONE FILE PER ENTITY plus a thin registration seam:
//
//   - entities/register.go — the RegisterAll seam. It is byte-identical for
//     every project regardless of entity count; each entity file appends
//     itself to registrars in init(), so adding an entity means adding one
//     new file and never editing an existing one.
//   - entities/<snake_name>.go — everything for one entity: model struct,
//     column constants, typed repo, event helpers, and its registration func.
//   - client/client.go — a standalone typed HTTP client (separate package).
//
// Declaration order is carried by the registrar.order field so RegisterAll
// registers entities in blueprint order and gofastr pack can recover it.
func renderGeneratedProject(decls []framework.EntityDeclaration) ([]generatedFile, error) {
	return renderGeneratedProjectWithOrder(decls, 0)
}

// renderGeneratedProjectWithOrder is the additive-generation variant: the
// order assigned to each entity is orderOffset+i, so entities added via --add
// to a project that already has N entities (orders 0..N-1) continue at N, N+1,
// … keeping RegisterAll's declaration order and pack recovery coherent.
func renderGeneratedProjectWithOrder(decls []framework.EntityDeclaration, orderOffset int) ([]generatedFile, error) {
	// Validate up front so a bad entity fails fast — with its name in the
	// error — before any file is emitted.
	for _, decl := range decls {
		if _, err := decl.Config(); err != nil {
			return nil, err
		}
		if len(decl.Endpoints) > 0 {
			return nil, fmt.Errorf("entity %q: code generation does not support endpoints — endpoints require Go handlers and must be wired in code (use app.Entity with EntityConfig.Endpoints)", decl.Name)
		}
	}
	files := []generatedFile{
		{name: "register.go", content: renderRegisterSeam()},
		// Generated client lives in its own package so consumers can import
		// it without dragging the server-side schema/framework deps along.
		{name: "client/client.go", content: renderClient(decls)},
	}
	// Preserve the caller's entity order (the blueprint's authored order) so
	// scaffolds are reproducible byte-for-byte and gofastr pack round-trips.
	for i, decl := range decls {
		content, err := renderEntityFile(decl, orderOffset+i)
		if err != nil {
			return nil, fmt.Errorf("entity %q: %w", decl.Name, err)
		}
		files = append(files, generatedFile{name: entityFileName(decl.Name), content: content})
	}
	return files, nil
}

// renderRegisterSeam emits entities/register.go — the fixed registration seam.
// It carries no entity-specific text, so its bytes are identical whether the
// project declares one entity or a hundred.
func renderRegisterSeam() string {
	return `package entities

import (
	"sort"

	"github.com/DonaldMurillo/gofastr/framework"
)

// registrar pairs an entity's registration func with its declaration order.
// Each entity file appends one registrar in init(); RegisterAll runs them in
// declaration order, so the package behaves identically regardless of the
// lexical order Go runs each file's init() in. The order field is also how
// gofastr pack recovers the blueprint's authored entity order from source.
type registrar struct {
	order int
	fn    func(app *framework.App)
}

var registrars []registrar

func boolPtr(v bool) *bool        { return &v }
func floatPtr(v float64) *float64 { return &v }

// RegisterAll registers every generated entity declaration with app, in
// declaration order. This file never holds an entity name: add an entity by
// dropping in a new entities/<name>.go that appends to registrars in init().
func RegisterAll(app *framework.App) {
	sort.SliceStable(registrars, func(i, j int) bool {
		return registrars[i].order < registrars[j].order
	})
	for _, r := range registrars {
		r.fn(app)
	}
}
`
}

// renderEntityFile emits the single entities/<snake_name>.go for one entity:
// its model struct, column constants, typed repository, event helpers, and a
// registration func that self-registers via init().
func renderEntityFile(decl framework.EntityDeclaration, order int) (string, error) {
	var sb strings.Builder
	sb.WriteString(`package entities

import (
	"context"
	"database/sql"

	"github.com/DonaldMurillo/gofastr/core/schema"
	"github.com/DonaldMurillo/gofastr/framework"
)

`)
	sb.WriteString(renderEntityModel(decl))
	sb.WriteString(renderEntityColumns(decl))
	sb.WriteString(renderEntityRepo(decl))
	sb.WriteString(renderEntityEvents(decl))
	registration, err := renderEntityRegistrationFunc(decl, order)
	if err != nil {
		return "", err
	}
	sb.WriteString(registration)
	return sb.String(), nil
}

// renderEntityRegistrationFunc wraps an entity's app.Entity(...) call in a
// register<Camel> func and self-registers it via init() so register.go never
// needs editing when an entity is added.
func renderEntityRegistrationFunc(decl framework.EntityDeclaration, order int) (string, error) {
	structName := toCamelCase(decl.Name)
	var sb strings.Builder
	sb.WriteString(fmt.Sprintf("// register%s registers the %q entity with app.\n", structName, decl.Name))
	sb.WriteString(fmt.Sprintf("func register%s(app *framework.App) {\n", structName))
	body, err := renderEntityRegistration(decl)
	if err != nil {
		return "", err
	}
	sb.WriteString(body)
	sb.WriteString("}\n\n")
	sb.WriteString(fmt.Sprintf("func init() {\n\tregistrars = append(registrars, registrar{order: %d, fn: register%s})\n}\n", order, structName))
	return sb.String(), nil
}

func renderEntityRegistration(decl framework.EntityDeclaration) (string, error) {
	var sb strings.Builder
	structName := toCamelCase(decl.Name)
	sb.WriteString(fmt.Sprintf("\tapp.Entity(%q, framework.EntityConfig{\n", decl.Name))
	if decl.Table != "" {
		sb.WriteString(fmt.Sprintf("\t\tTable: %q,\n", decl.Table))
	}
	sb.WriteString("\t\tFields: []schema.Field{\n")
	for _, field := range decl.Fields {
		literal, err := renderFieldLiteral(field)
		if err != nil {
			return "", fmt.Errorf("field %q: %w", field.Name, err)
		}
		sb.WriteString("\t\t\t" + literal + ",\n")
	}
	sb.WriteString("\t\t},\n")
	if len(decl.Relations) > 0 {
		sb.WriteString("\t\tRelations: []framework.Relation{\n")
		for _, rel := range decl.Relations {
			sb.WriteString("\t\t\t" + renderRelationLiteral(rel) + ",\n")
		}
		sb.WriteString("\t\t},\n")
	}
	if decl.SoftDelete {
		sb.WriteString("\t\tSoftDelete: true,\n")
	}
	if decl.MultiTenant {
		sb.WriteString("\t\tMultiTenant: true,\n")
	}
	if decl.OwnerField != "" {
		sb.WriteString(fmt.Sprintf("\t\tOwnerField: %q,\n", decl.OwnerField))
	}
	if decl.CrossOwnerRead != "" {
		sb.WriteString(fmt.Sprintf("\t\tCrossOwnerRead: %q,\n", decl.CrossOwnerRead))
	}
	if len(decl.SearchFields) > 0 {
		sb.WriteString("\t\tSearchFields: []string{")
		for i, sf := range decl.SearchFields {
			if i > 0 {
				sb.WriteString(", ")
			}
			sb.WriteString(fmt.Sprintf("%q", sf))
		}
		sb.WriteString("},\n")
	}
	if literal := renderAccessLiteral(decl.Access); literal != "" {
		sb.WriteString("\t\tAccess: " + literal + ",\n")
	}
	if decl.Public {
		sb.WriteString("\t\tPublic: true,\n")
	}
	if decl.CRUD != nil {
		sb.WriteString(fmt.Sprintf("\t\tCRUD: boolPtr(%t),\n", *decl.CRUD))
	}
	if decl.MCP {
		sb.WriteString("\t\tMCP: true,\n")
	}
	if decl.CursorField != "" {
		sb.WriteString(fmt.Sprintf("\t\tCursorField: %q,\n", decl.CursorField))
	}
	if len(decl.CursorFields) > 0 {
		sb.WriteString("\t\tCursorFields: []string{")
		for i, field := range decl.CursorFields {
			if i > 0 {
				sb.WriteString(", ")
			}
			sb.WriteString(fmt.Sprintf("%q", field))
		}
		sb.WriteString("},\n")
	}
	if len(decl.Indices) > 0 {
		sb.WriteString("\t\tIndices: []framework.Index{\n")
		for _, idx := range decl.Indices {
			sb.WriteString("\t\t\t" + renderIndexLiteral(idx) + ",\n")
		}
		sb.WriteString("\t\t},\n")
	}
	if len(decl.Properties) > 0 {
		literal, err := renderGoLiteral(decl.Properties)
		if err != nil {
			return "", fmt.Errorf("properties: %w", err)
		}
		sb.WriteString("\t\tProperties: " + literal + ",\n")
	}
	sb.WriteString("\t}")
	if decl.Timestamps != nil {
		sb.WriteString(fmt.Sprintf(".WithTimestamps(%t)", *decl.Timestamps))
	}
	sb.WriteString(")\n")
	sb.WriteString(fmt.Sprintf("\t_ = %s{}\n", structName))
	return sb.String(), nil
}

// renderAccessLiteral renders an entity's per-operation RBAC declaration as
// a framework.AccessControl composite literal for the generated register.go.
// Returns "" when access is nil or every operation is un-gated, so the
// generated registration stays byte-identical for blueprints without RBAC.
func renderAccessLiteral(access *fwentity.AccessDeclaration) string {
	if access == nil {
		return ""
	}
	var parts []string
	if access.Read != "" {
		parts = append(parts, fmt.Sprintf("Read: %q", access.Read))
	}
	if access.Create != "" {
		parts = append(parts, fmt.Sprintf("Create: %q", access.Create))
	}
	if access.Update != "" {
		parts = append(parts, fmt.Sprintf("Update: %q", access.Update))
	}
	if access.Delete != "" {
		parts = append(parts, fmt.Sprintf("Delete: %q", access.Delete))
	}
	if len(parts) == 0 {
		return ""
	}
	return "framework.AccessControl{" + strings.Join(parts, ", ") + "}"
}

func renderIndexLiteral(idx framework.Index) string {
	var parts []string
	if idx.Name != "" {
		parts = append(parts, fmt.Sprintf("Name: %q", idx.Name))
	}
	if len(idx.Columns) > 0 {
		quoted := make([]string, len(idx.Columns))
		for i, column := range idx.Columns {
			quoted[i] = fmt.Sprintf("%q", column)
		}
		parts = append(parts, "Columns: []string{"+strings.Join(quoted, ", ")+"}")
	}
	if idx.Unique {
		parts = append(parts, "Unique: true")
	}
	return "{" + strings.Join(parts, ", ") + "}"
}

func renderFieldLiteral(field framework.FieldDeclaration) (string, error) {
	typeConst, err := schemaConstName(field.Type)
	if err != nil {
		return "", err
	}
	autoConst, err := autoGenerateConstName(field.AutoGenerate)
	if err != nil {
		return "", err
	}
	var parts []string
	parts = append(parts, fmt.Sprintf("Name: %q", field.Name))
	parts = append(parts, fmt.Sprintf("Type: schema.%s", typeConst))
	if field.Required {
		parts = append(parts, "Required: true")
	}
	if field.Unique {
		parts = append(parts, "Unique: true")
	}
	if field.ReadOnly {
		parts = append(parts, "ReadOnly: true")
	}
	if field.Hidden {
		parts = append(parts, "Hidden: true")
	}
	if field.Default != nil {
		literal, err := renderGoLiteral(field.Default)
		if err != nil {
			return "", fmt.Errorf("default value: %w", err)
		}
		parts = append(parts, "Default: "+literal)
	}
	if autoConst != "AutoNone" {
		parts = append(parts, "AutoGenerate: schema."+autoConst)
	}
	if field.Max != nil {
		parts = append(parts, fmt.Sprintf("Max: floatPtr(%g)", *field.Max))
	}
	if field.Min != nil {
		parts = append(parts, fmt.Sprintf("Min: floatPtr(%g)", *field.Min))
	}
	if field.Pattern != "" {
		parts = append(parts, fmt.Sprintf("Pattern: %q", field.Pattern))
	}
	if len(field.Values) > 0 {
		quoted := make([]string, len(field.Values))
		for i, value := range field.Values {
			quoted[i] = fmt.Sprintf("%q", value)
		}
		parts = append(parts, "Values: []string{"+strings.Join(quoted, ", ")+"}")
	}
	if field.To != "" {
		parts = append(parts, fmt.Sprintf("To: %q", field.To))
	}
	if field.Many {
		parts = append(parts, "Many: true")
	}
	return "{" + strings.Join(parts, ", ") + "}", nil
}

func renderRelationLiteral(rel framework.Relation) string {
	var parts []string
	parts = append(parts, fmt.Sprintf("Type: framework.%s", relationTypeConst(rel.Type)))
	parts = append(parts, fmt.Sprintf("Name: %q", rel.Name))
	parts = append(parts, fmt.Sprintf("Entity: %q", rel.Entity))
	if rel.ForeignKey != "" {
		parts = append(parts, fmt.Sprintf("ForeignKey: %q", rel.ForeignKey))
	}
	if rel.Through != "" {
		parts = append(parts, fmt.Sprintf("Through: %q", rel.Through))
	}
	if rel.LocalKey != "" {
		parts = append(parts, fmt.Sprintf("LocalKey: %q", rel.LocalKey))
	}
	if rel.ForeignKeyTarget != "" {
		parts = append(parts, fmt.Sprintf("ForeignKeyTarget: %q", rel.ForeignKeyTarget))
	}
	return "{" + strings.Join(parts, ", ") + "}"
}

func relationTypeConst(t framework.RelationType) string {
	switch t {
	case framework.RelHasOne:
		return "RelHasOne"
	case framework.RelHasMany:
		return "RelHasMany"
	case framework.RelManyToOne:
		return "RelManyToOne"
	case framework.RelManyToMany:
		return "RelManyToMany"
	default:
		return "RelManyToOne"
	}
}

func renderGoLiteral(value any) (string, error) {
	switch v := value.(type) {
	case nil:
		return "nil", nil
	case bool:
		return fmt.Sprintf("%t", v), nil
	case string:
		return fmt.Sprintf("%q", v), nil
	case float64:
		if v == float64(int64(v)) {
			return fmt.Sprintf("%d", int64(v)), nil
		}
		return fmt.Sprintf("%g", v), nil
	case int, int32, int64:
		return fmt.Sprintf("%d", v), nil
	case map[string]any:
		keys := make([]string, 0, len(v))
		for key := range v {
			keys = append(keys, key)
		}
		sort.Strings(keys)
		parts := make([]string, 0, len(keys))
		for _, key := range keys {
			literal, err := renderGoLiteral(v[key])
			if err != nil {
				return "", err
			}
			parts = append(parts, fmt.Sprintf("%q: %s", key, literal))
		}
		return "map[string]any{" + strings.Join(parts, ", ") + "}", nil
	case []any:
		parts := make([]string, 0, len(v))
		for _, item := range v {
			literal, err := renderGoLiteral(item)
			if err != nil {
				return "", err
			}
			parts = append(parts, literal)
		}
		return "[]any{" + strings.Join(parts, ", ") + "}", nil
	case []string:
		parts := make([]string, len(v))
		for i, item := range v {
			parts[i] = fmt.Sprintf("%q", item)
		}
		return "[]string{" + strings.Join(parts, ", ") + "}", nil
	default:
		return "", fmt.Errorf("unsupported default literal of type %T", value)
	}
}

func renderEntityModel(decl framework.EntityDeclaration) string {
	structName := toCamelCase(decl.Name)
	var sb strings.Builder
	sb.WriteString(fmt.Sprintf("type %s struct {\n", structName))
	sb.WriteString("\tID string `json:\"id\"`\n")
	for _, field := range decl.Fields {
		if field.Name == "id" {
			continue
		}
		sb.WriteString(fmt.Sprintf("\t%s %s `json:\"%s,omitempty\"`\n", toCamelCase(field.Name), goTypeForField(field.Type), toCamelJSON(field.Name)))
	}
	// Relation fields — populated by TypedQuery.Include() and Repo.Get(...,
	// includes...). Singular relations (HasOne/BelongsTo) get *Target;
	// collections (HasMany/ManyToMany) get []*Target. Pointer so the absent
	// case marshals as null (matches the framework's nil-for-missing
	// contract).
	for _, rel := range decl.Relations {
		targetStruct := toCamelCase(rel.Entity)
		fieldName := toCamelCase(rel.Name)
		jsonTag := toCamelJSON(rel.Name)
		switch rel.Type {
		case framework.RelHasOne, framework.RelManyToOne:
			sb.WriteString(fmt.Sprintf("\t%s *%s `json:\"%s,omitempty\"`\n", fieldName, targetStruct, jsonTag))
		case framework.RelHasMany, framework.RelManyToMany:
			sb.WriteString(fmt.Sprintf("\t%s []*%s `json:\"%s,omitempty\"`\n", fieldName, targetStruct, jsonTag))
		}
	}
	sb.WriteString("}\n\n")
	return sb.String()
}

func schemaConstName(value string) (string, error) {
	switch strings.ToLower(value) {
	case "", "string":
		return "String", nil
	case "text":
		return "Text", nil
	case "int", "integer":
		return "Int", nil
	case "float", "number":
		return "Float", nil
	case "decimal":
		return "Decimal", nil
	case "bool", "boolean":
		return "Bool", nil
	case "enum":
		return "Enum", nil
	case "uuid":
		return "UUID", nil
	case "timestamp", "datetime":
		return "Timestamp", nil
	case "date":
		return "Date", nil
	case "json":
		return "JSON", nil
	case "relation":
		return "Relation", nil
	case "image":
		return "Image", nil
	case "file":
		return "File", nil
	default:
		return "", fmt.Errorf("unknown field type %q", value)
	}
}

func autoGenerateConstName(value string) (string, error) {
	switch strings.ToLower(strings.TrimSpace(value)) {
	case "", "none":
		return "AutoNone", nil
	case "uuid":
		return "AutoUUID", nil
	case "timestamp":
		return "AutoTimestamp", nil
	case "increment", "auto_increment":
		return "AutoIncrement", nil
	default:
		return "", fmt.Errorf("unknown auto_generate %q", value)
	}
}

func goTypeForField(value string) string {
	switch strings.ToLower(value) {
	case "int", "integer":
		return "int"
	case "float", "number":
		return "float64"
	case "bool", "boolean":
		return "bool"
	case "json":
		return "map[string]any"
	default:
		return "string"
	}
}

func toCamelJSON(value string) string {
	camel := toCamelCase(value)
	if camel == "" {
		return ""
	}
	return strings.ToLower(camel[:1]) + camel[1:]
}

// validateOutputDir rejects paths that would be unsafe to clean (the cwd, the
// FS root, absolute paths, parent traversals, or empty input).
func validateOutputDir(dir string) error {
	if strings.TrimSpace(dir) == "" {
		return fmt.Errorf("--out must not be empty")
	}
	clean := filepath.Clean(dir)
	if filepath.IsAbs(clean) {
		return fmt.Errorf("--out must be a relative path inside the project (got %q)", dir)
	}
	if clean == "." || clean == ".." {
		return fmt.Errorf("--out=%q would target the working directory; choose a subdirectory like gen/entities", dir)
	}
	for _, part := range strings.Split(clean, string(filepath.Separator)) {
		if part == ".." {
			return fmt.Errorf("--out=%q must not contain parent directory traversal", dir)
		}
	}
	return nil
}

// safeCleanOutputDir removes only the files this generator owns. It refuses to
// remove the directory if it contains files the generator did not write — this
// prevents accidental data loss when --out points at a populated directory.
func safeCleanOutputDir(dir string) error {
	if err := codegen.EnsureNoSymlinkPath(dir); err != nil {
		return err
	}
	info, err := os.Stat(dir)
	if err != nil {
		if os.IsNotExist(err) {
			return nil
		}
		return err
	}
	if !info.IsDir() {
		return fmt.Errorf("%s exists and is not a directory", dir)
	}
	entries, err := os.ReadDir(dir)
	if err != nil {
		return err
	}
	// Files the blueprint code generator owns at the output root. The current
	// layout is flat package main (main.go + app.go/screens.go/stubs.go/
	// resource.go/resource_test.go/e2e_test.go) plus the entities/ subtree; the
	// legacy "blueprint" dir and the bare register.go/models.go/... names are
	// retained so cleaning an output dir written by an older generator still
	// succeeds.
	owned := map[string]bool{
		".gitkeep": true, codegen.ManifestName: true,
		"main.go": true, "app.go": true, "screens.go": true, "stubs.go": true,
		"resource.go": true, "resource_test.go": true, "e2e_test.go": true,
		".env": true, ".gitignore": true,
		"register.go": true, "models.go": true, "columns.go": true, "repo.go": true, "events.go": true,
		"client": true, "entities": true, "blueprint": true,
	}
	for _, entry := range entries {
		if !owned[entry.Name()] {
			return fmt.Errorf("refusing to clean %s — contains unknown entry %q (move it or use --no-clean)", dir, entry.Name())
		}
	}
	for name := range owned {
		path := filepath.Join(dir, name)
		if name == ".gitkeep" {
			continue
		}
		if err := codegen.EnsureNoSymlinkPath(filepath.Dir(path)); err != nil {
			return err
		}
		if err := os.RemoveAll(path); err != nil && !os.IsNotExist(err) {
			return err
		}
	}
	return nil
}

func printGeneratedFilesJSON(files []generatedFile) {
	fmt.Println(`{"files":[`)
	for i, file := range files {
		comma := ","
		if i == len(files)-1 {
			comma = ""
		}
		fmt.Printf("  {\"path\":%q,\"size\":%d}%s\n", file.name, len(file.content), comma)
	}
	fmt.Println(`]}`)
}

// printAdditiveFilesJSON emits the --add success shape: the written files in
// the same {"path","size"} format as printGeneratedFilesJSON, plus a sorted
// "skipped_existing" array of file names that were not written because they
// already existed. The key is always present in --add mode.
func printAdditiveFilesJSON(written []generatedFile, skipped []string) {
	fmt.Println(`{"files":[`)
	for i, file := range written {
		comma := ","
		if i == len(written)-1 {
			comma = ""
		}
		fmt.Printf("  {\"path\":%q,\"size\":%d}%s\n", file.name, len(file.content), comma)
	}
	if len(skipped) == 0 {
		fmt.Println(`],"skipped_existing":[]}`)
		return
	}
	fmt.Println(`],"skipped_existing":[`)
	for i, name := range skipped {
		comma := ","
		if i == len(skipped)-1 {
			comma = ""
		}
		fmt.Printf("  %q%s\n", name, comma)
	}
	fmt.Println(`]}`)
}

func printCodegenFilesJSON(files []codegen.GeneratedFile) {
	fmt.Println(`{"files":[`)
	for i, file := range files {
		comma := ","
		if i == len(files)-1 {
			comma = ""
		}
		fmt.Printf("  {\"path\":%q,\"size\":%d}%s\n", file.Path, len(file.Content), comma)
	}
	fmt.Println(`]}`)
}

func printGeneratedErrorsJSON(errs ...error) {
	fmt.Println(`{"files":[],"errors":[`)
	for i, err := range errs {
		comma := ","
		if i == len(errs)-1 {
			comma = ""
		}
		fmt.Printf("  {\"message\":%q}%s\n", err.Error(), comma)
	}
	fmt.Println(`]}`)
}

func toCamelCase(s string) string {
	parts := strings.FieldsFunc(s, func(r rune) bool {
		return r == '_' || r == '-' || r == ' '
	})
	var result string
	for _, p := range parts {
		if len(p) > 0 {
			result += strings.ToUpper(p[:1]) + p[1:]
		}
	}
	return result
}

// toSnakeCase converts an entity name to snake_case for generated file names.
// It handles already-snake input ("blog_posts"), CamelCase ("BlogPost"), and
// hyphenated or spaced input, collapsing repeated separators.
func toSnakeCase(s string) string {
	var b strings.Builder
	runes := []rune(s)
	for i, r := range runes {
		isUpper := r >= 'A' && r <= 'Z'
		if i > 0 && isUpper {
			prev := runes[i-1]
			if (prev >= 'a' && prev <= 'z') || (prev >= '0' && prev <= '9') {
				b.WriteByte('_')
			}
		}
		switch {
		case r == '-' || r == ' ':
			b.WriteByte('_')
		case r >= 'A' && r <= 'Z':
			b.WriteRune(r + 'a' - 'A')
		default:
			b.WriteRune(r)
		}
	}
	out := b.String()
	for strings.Contains(out, "__") {
		out = strings.ReplaceAll(out, "__", "_")
	}
	return strings.Trim(out, "_")
}

// entityFileName maps an entity name to its generated file name, guarding
// against collisions with the fixed package files (register.go, shared.go,
// doc.go): a colliding name is prefixed with entity_ so it never shadows the
// seam or shared helpers.
func entityFileName(name string) string {
	snake := toSnakeCase(name)
	switch snake {
	case "register", "shared", "doc":
		return "entity_" + snake + ".go"
	}
	return snake + ".go"
}

// fileExistsUnder reports whether rel exists under writeRoot.
func fileExistsUnder(writeRoot, rel string) bool {
	_, err := os.Stat(filepath.Join(writeRoot, rel))
	return err == nil
}

// registeredScreenRoutes returns the set of routes actually mounted by the
// generated app under writeRoot, scanned from every `site.Register(route, …)`
// and `app.NewScreen(route, …)` (the arg to site.RegisterScreen) call in its
// *.go files. Unlike packReadScreens — which reconstructs only the AUTHORED
// screens and deliberately drops synthesized CRUD form screens — this sees the
// full mounted set, including the /new and /{id}/edit routes those forms add,
// so the --add collision guard can't be fooled into double-registering one.
func registeredScreenRoutes(writeRoot string) map[string]bool {
	routes := map[string]bool{}
	entries, err := os.ReadDir(writeRoot)
	if err != nil {
		return routes
	}
	for _, e := range entries {
		name := e.Name()
		if e.IsDir() || !strings.HasSuffix(name, ".go") || strings.HasSuffix(name, "_test.go") {
			continue
		}
		file, perr := packParseFile(filepath.Join(writeRoot, name))
		if perr != nil {
			continue
		}
		ast.Inspect(file, func(n ast.Node) bool {
			call, ok := n.(*ast.CallExpr)
			if !ok {
				return true
			}
			sel, ok := call.Fun.(*ast.SelectorExpr)
			if !ok || len(call.Args) == 0 {
				return true
			}
			// site.Register("/route", …) and app.NewScreen("/route", …) both
			// carry the route as their first arg; RegisterScreen wraps a
			// NewScreen so scanning NewScreen covers it.
			if sel.Sel.Name == "Register" || sel.Sel.Name == "NewScreen" {
				if r := astString(call.Args[0]); strings.HasPrefix(r, "/") {
					routes[r] = true
				}
			}
			return true
		})
	}
	return routes
}

// missingCallSite reports whether the named owned file exists under
// writeRoot yet nowhere mentions the given call — the additive trap where
// freshly added seam-registered files compile but are never invoked. A file
// that doesn't exist is NOT missing the call (it will be written this run).
func missingCallSite(writeRoot, rel, call string) bool {
	data, err := os.ReadFile(filepath.Join(writeRoot, rel))
	if err != nil {
		return false
	}
	return !strings.Contains(string(data), call)
}

// maxExistingEntityOrder reads the existing entities/ directory under
// writeRoot and returns the order the NEXT entity should use (max existing
// order + 1, or 0 when there are no entities). It reuses the pack machinery
// (packParseFile + packFindEntityCall + packEntityOrder) so declaration order
// stays coherent between additive generation and `gofastr pack`.
func maxExistingEntityOrder(writeRoot string) int {
	entDir := filepath.Join(writeRoot, "entities")
	entries, err := os.ReadDir(entDir)
	if err != nil {
		return 0 // no entities dir yet
	}
	skip := map[string]bool{"register.go": true, "shared.go": true, "doc.go": true}
	maxOrder := -1
	for _, entry := range entries {
		if entry.IsDir() || !strings.HasSuffix(entry.Name(), ".go") || skip[entry.Name()] {
			continue
		}
		path := filepath.Join(entDir, entry.Name())
		file, err := packParseFile(path)
		if err != nil {
			continue
		}
		if _, ok := packFindEntityCall(file); !ok {
			continue // not an entity file (e.g. a shared helper)
		}
		if order := packEntityOrder(file); order > maxOrder {
			maxOrder = order
		}
	}
	if maxOrder < 0 {
		return 0
	}
	return maxOrder + 1
}

// maxExistingScreenOrder reads the existing screen_*.go files under writeRoot
// and returns the order the NEXT screen should use (max existing screen
// registrar order + 1, or 0 when there are none). It reuses the pack
// machinery (packParseFile + packScreenFileOrders) so screen declaration
// order stays coherent between additive generation and `gofastr pack`.
func maxExistingScreenOrder(writeRoot string) int {
	entries, err := os.ReadDir(writeRoot)
	if err != nil {
		return 0 // no output dir yet
	}
	maxOrder := -1
	for _, entry := range entries {
		name := entry.Name()
		if entry.IsDir() || !strings.HasSuffix(name, ".go") || strings.HasSuffix(name, "_test.go") {
			continue
		}
		if name == "screen_shared.go" || name == "screens_register.go" || !strings.HasPrefix(name, "screen_") {
			continue
		}
		path := filepath.Join(writeRoot, name)
		file, err := packParseFile(path)
		if err != nil {
			continue
		}
		for _, o := range packScreenFileOrders(file) {
			if o > maxOrder {
				maxOrder = o
			}
		}
	}
	if maxOrder < 0 {
		return 0
	}
	return maxOrder + 1
}
