package main

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/gofastr/gofastr/framework"
)

// runGenerateTS implements `gofastr generate ts [--entities=...] [--out=...]`.
// Emits a single entities.ts file with one exported interface per entity.
// Field shapes match the Go model: ID is required, every other field carries
// `?:` (omitempty). Relation fields are typed against the target entity's
// interface name. JSON columns become `unknown` since the contents are
// not introspectable from a schema declaration.
func runGenerateTS(args []string) {
	opts := parseTSOptions(args)
	decls, err := framework.LoadEntityDeclarations(opts.entitiesDir)
	if err != nil {
		fail("Failed to load entity declarations: %v", err)
		os.Exit(1)
	}
	if len(decls) == 0 {
		fail("No entity declarations found in %s.", opts.entitiesDir)
		os.Exit(1)
	}

	source := renderTypeScript(decls)
	if err := os.MkdirAll(filepath.Dir(opts.outFile), 0o755); err != nil {
		fail("mkdir %s: %v", filepath.Dir(opts.outFile), err)
		os.Exit(1)
	}
	if err := os.WriteFile(opts.outFile, []byte(source), 0o644); err != nil {
		fail("write %s: %v", opts.outFile, err)
		os.Exit(1)
	}
	success("Generated %s (%d entities, %d bytes)", opts.outFile, len(decls), len(source))
}

type tsOptions struct {
	entitiesDir string
	outFile     string
}

func parseTSOptions(args []string) tsOptions {
	opts := tsOptions{
		entitiesDir: "entities",
		outFile:     filepath.Join(".gofastr", "entities.ts"),
	}
	for _, arg := range args {
		switch {
		case strings.HasPrefix(arg, "--entities="):
			opts.entitiesDir = strings.TrimPrefix(arg, "--entities=")
		case strings.HasPrefix(arg, "--out="):
			opts.outFile = strings.TrimPrefix(arg, "--out=")
		}
	}
	return opts
}

// renderTypeScript emits one interface per entity. Sorted by name so output
// is deterministic regardless of declaration directory order.
func renderTypeScript(decls []framework.EntityDeclaration) string {
	sort.Slice(decls, func(i, j int) bool { return decls[i].Name < decls[j].Name })

	var sb strings.Builder
	sb.WriteString("// Code generated by gofastr. DO NOT EDIT.\n")
	sb.WriteString("// TypeScript types for entities — keep in sync with .gofastr/entities/models.go.\n\n")

	for _, decl := range decls {
		ifaceName := toCamelCase(decl.Name)
		sb.WriteString(fmt.Sprintf("export interface %s {\n", ifaceName))
		sb.WriteString("\tid: string;\n")
		for _, field := range decl.Fields {
			if field.Name == "id" {
				continue
			}
			sb.WriteString(fmt.Sprintf("\t%s?: %s;\n", toCamelJSON(field.Name), tsTypeForField(field.Type)))
		}
		// Relation fields — match the Go model's pointer / slice shape.
		for _, rel := range decl.Relations {
			targetIface := toCamelCase(rel.Entity)
			jsonName := toCamelJSON(rel.Name)
			switch rel.Type {
			case framework.RelHasOne, framework.RelManyToOne:
				sb.WriteString(fmt.Sprintf("\t%s?: %s;\n", jsonName, targetIface))
			case framework.RelHasMany, framework.RelManyToMany:
				sb.WriteString(fmt.Sprintf("\t%s?: %s[];\n", jsonName, targetIface))
			}
		}
		sb.WriteString("}\n\n")
	}

	// List + cursor + batch envelopes. Generic so callers can reuse them
	// across every endpoint without re-declaring.
	sb.WriteString(`// API envelopes shared by every entity's REST routes.

export interface ListResponse<T> {
	data: T[];
	total: number;
	page: number;
	perPage: number;
	totalPages: number;
}

export interface CursorPage<T> {
	data: T[];
	cursor: string;
	hasMore: boolean;
	total?: number;
}

export interface BatchResult<T> {
	index: number;
	data?: T;
	error?: string;
	fields?: Record<string, string[]>;
	skipped?: boolean;
}

export interface BatchResponse<T> {
	committed: boolean;
	results: BatchResult<T>[];
}

export interface ApiError {
	error: string;
	success: false;
	code: number;
	fields?: Record<string, string[]>;
}
`)
	return sb.String()
}

// tsTypeForField maps a schema field type to a TypeScript primitive (or
// "unknown" when the contents aren't introspectable).
func tsTypeForField(value string) string {
	switch strings.ToLower(value) {
	case "int", "integer", "float", "number", "decimal":
		return "number"
	case "bool", "boolean":
		return "boolean"
	case "json":
		return "unknown"
	default:
		// String, Text, Enum, UUID, Timestamp, Date, Image, File, Relation —
		// all wire-shape strings.
		return "string"
	}
}
