package main

import (
	"archive/zip"
	"bytes"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"
	"testing/fstest"

	"github.com/DonaldMurillo/gofastr/framework"
	"github.com/DonaldMurillo/gofastr/framework/sdk"
)

// sdkFixtureDecls covers the shapes the SDK emitters must handle: a plain
// entity with an enum and a HIDDEN field (which must never surface in any
// generated file — the SDKs are downloadable), and a search + soft-delete
// entity with a custom table name.
func sdkFixtureDecls() []framework.EntityDeclaration {
	return []framework.EntityDeclaration{
		{
			Name:  "posts",
			Table: "posts",
			Fields: []framework.FieldDeclaration{
				{Name: "title", Type: "string", Required: true},
				{Name: "views", Type: "int"},
				{Name: "published", Type: "bool"},
				{Name: "status", Type: "enum", Values: []string{"draft", "live"}},
				{Name: "secret_note", Type: "string", Hidden: true},
			},
		},
		{
			Name:         "documents",
			Table:        "doc_files",
			SoftDelete:   true,
			SearchFields: []string{"title"},
			Fields: []framework.FieldDeclaration{
				{Name: "title", Type: "string", Required: true},
				{Name: "body", Type: "text"},
			},
		},
	}
}

func sdkFixtureSpec(t *testing.T) sdkSpec {
	t.Helper()
	opts := sdkOptions{name: "myapp", sdkVersion: "1.2.3", baseURL: "https://api.example.com"}
	spec, err := buildSDKSpec(sdkFixtureDecls(), &opts)
	if err != nil {
		t.Fatalf("buildSDKSpec: %v", err)
	}
	return spec
}

func renderedSDK(t *testing.T) map[string]string {
	t.Helper()
	files, err := renderSDKFiles(sdkFixtureSpec(t), []string{"go", "js"}, true)
	if err != nil {
		t.Fatalf("renderSDKFiles: %v", err)
	}
	out := map[string]string{}
	for _, f := range files {
		out[f.name] = f.content
	}
	return out
}

func TestRenderSDKFiles_Layout(t *testing.T) {
	got := renderedSDK(t)
	for _, want := range []string{
		"go/client.go", "go/go.mod", "go/README.md",
		"js/client.js", "js/client.d.ts", "js/README.md",
		"dist/" + sdk.GoArtifact, "dist/" + sdk.JSArtifact,
		"dist/" + sdk.JSTypesArtifact, "dist/" + sdk.ManifestFile,
	} {
		if _, ok := got[want]; !ok {
			t.Errorf("missing generated file %s (have %d files)", want, len(got))
		}
	}
}

func TestSDKNeverEmitsHiddenFields(t *testing.T) {
	for name, content := range renderedSDK(t) {
		if strings.HasSuffix(name, ".zip") {
			continue // binary; its inputs are the go/ files checked here
		}
		if strings.Contains(content, "secret_note") || strings.Contains(content, "secretNote") || strings.Contains(content, "SecretNote") {
			t.Errorf("%s leaks the hidden field", name)
		}
	}
}

func TestSDKGoModule(t *testing.T) {
	got := renderedSDK(t)
	if want := "module local/myapp-sdk"; !strings.Contains(got["go/go.mod"], want) {
		t.Errorf("go.mod missing %q:\n%s", want, got["go/go.mod"])
	}
	for _, want := range []string{
		"Code generated by gofastr", "DO NOT EDIT",
		"package client",
		"func (c *Client) ListPosts(",
		"func (c *Client) WatchDocuments(",
		`"/doc_files"`,
	} {
		if !strings.Contains(got["go/client.go"], want) {
			t.Errorf("go/client.go missing %q", want)
		}
	}
	if !strings.Contains(got["go/README.md"], "https://api.example.com") {
		t.Error("go README should bake in the configured base URL")
	}
	if !strings.Contains(got["go/README.md"], "snake_case") {
		t.Error("go README must document the query-param casing contract")
	}
}

func TestSDKJSTypedSurface(t *testing.T) {
	got := renderedSDK(t)
	js, dts := got["js/client.js"], got["js/client.d.ts"]

	for _, want := range []string{
		"export class Client", "export class ApiError",
		"this.posts = new Resource(this, \"posts\")",
		"this.docFiles = new Resource(this, \"doc_files\")",
		"export const postsFields",
		"watch(onEvent, opts)",
		"_batch",
	} {
		if !strings.Contains(js, want) {
			t.Errorf("client.js missing %q", want)
		}
	}
	for _, want := range []string{
		"export interface Posts {",
		"export interface PostsInput {",
		"  title: string;",  // required → non-optional in Input
		"  views?: number;", // optional camelCase
		`"draft" | "live"`,  // enum literal union
		"export type PostsPatch = Partial<PostsInput>;",
		"readonly posts: Resource<Posts, PostsInput, PostsPatch>;",
		"readonly docFiles: Resource<Documents, DocumentsInput, DocumentsPatch>;",
		"ListResponse<T>",
	} {
		if !strings.Contains(dts, want) {
			t.Errorf("client.d.ts missing %q", want)
		}
	}
}

// Every resource property assigned in client.js must be declared in
// client.d.ts — the twin-walk guarantee.
func TestSDKJSDeclarationsInSync(t *testing.T) {
	got := renderedSDK(t)
	js, dts := got["js/client.js"], got["js/client.d.ts"]
	for _, line := range strings.Split(js, "\n") {
		line = strings.TrimSpace(line)
		if !strings.HasPrefix(line, "this.") || !strings.Contains(line, "new Resource(") {
			continue
		}
		prop := strings.TrimPrefix(line[:strings.Index(line, " =")], "this.")
		if !strings.Contains(dts, "readonly "+prop+": Resource<") {
			t.Errorf("resource %q assigned in client.js but not declared in client.d.ts", prop)
		}
	}
	for _, constLine := range []string{"postsFields", "docFilesFields"} {
		if !strings.Contains(js, "export const "+constLine) {
			t.Errorf("client.js missing %s constant", constLine)
		}
		if !strings.Contains(dts, "export declare const "+constLine) {
			t.Errorf("client.d.ts missing %s declaration", constLine)
		}
	}
}

func TestSDKManifest(t *testing.T) {
	got := renderedSDK(t)
	m, err := sdk.ReadManifest(fstest.MapFS{
		sdk.ManifestFile: {Data: []byte(got["dist/"+sdk.ManifestFile])},
	})
	if err != nil {
		t.Fatalf("manifest: %v", err)
	}
	if m.App != "myapp" || m.SDKVersion != "1.2.3" {
		t.Fatalf("manifest stamping wrong: %+v", m)
	}
	if len(m.Entities) != 2 || m.Entities[0] != "documents" || m.Entities[1] != "posts" {
		t.Fatalf("manifest entities: %+v", m.Entities)
	}
	for _, key := range []string{"go", "js", "js-types"} {
		if _, ok := m.Artifacts[key]; !ok {
			t.Errorf("manifest missing artifact %q", key)
		}
	}
	wantHash, err := sdkSchemaHash(sdkFixtureDecls())
	if err != nil {
		t.Fatal(err)
	}
	if m.SchemaHash != wantHash {
		t.Fatalf("manifest hash %s != live hash %s", m.SchemaHash, wantHash)
	}
	if int64(len(got["dist/"+sdk.JSArtifact])) != m.Artifacts["js"].Bytes {
		t.Error("manifest byte count disagrees with the artifact")
	}
}

func TestSDKZipDeterministic(t *testing.T) {
	a := renderedSDK(t)["dist/"+sdk.GoArtifact]
	b := renderedSDK(t)["dist/"+sdk.GoArtifact]
	if a != b {
		t.Fatal("two generations of an unchanged schema produced different archives")
	}
	zr, err := zip.NewReader(bytes.NewReader([]byte(a)), int64(len(a)))
	if err != nil {
		t.Fatal(err)
	}
	var names []string
	for _, f := range zr.File {
		names = append(names, f.Name)
	}
	want := []string{"myapp-sdk/README.md", "myapp-sdk/client.go", "myapp-sdk/go.mod"}
	if strings.Join(names, ",") != strings.Join(want, ",") {
		t.Fatalf("zip entries %v, want %v", names, want)
	}
}

func TestParseSDKOptionsRejectsUnknown(t *testing.T) {
	if _, err := parseSDKOptions([]string{"--target=rust"}); err == nil {
		t.Error("unknown target accepted")
	}
	if _, err := parseSDKOptions([]string{"--frobnicate"}); err == nil {
		t.Error("unknown flag accepted")
	}
}

func TestBuildSDKSpecRejectsUnknownEntity(t *testing.T) {
	opts := sdkOptions{name: "x", only: []string{"nope"}}
	if _, err := buildSDKSpec(sdkFixtureDecls(), &opts); err == nil {
		t.Error("typo'd --only accepted")
	}
}

func TestBuildSDKSpecSelection(t *testing.T) {
	opts := sdkOptions{name: "x", exclude: []string{"documents"}}
	spec, err := buildSDKSpec(sdkFixtureDecls(), &opts)
	if err != nil {
		t.Fatal(err)
	}
	if len(spec.Entities) != 1 || spec.Entities[0].Table != "posts" {
		t.Fatalf("selection wrong: %+v", spec.Entities)
	}
}

// End-to-end: real temp project → generate the app → generate the SDK →
// unzip the downloadable Go artifact → `go build` it standalone. This is
// the artifact a stranger downloads; it must compile with no replace
// directives and no non-stdlib imports.
func TestGenerateSDK_E2EDownloadedZipBuilds(t *testing.T) {
	repoRoot, err := filepath.Abs(filepath.Join("..", ".."))
	if err != nil {
		t.Fatal(err)
	}
	dir := t.TempDir()
	goVersion, err := repoGoVersion(repoRoot)
	if err != nil {
		t.Fatalf("repoGoVersion: %v", err)
	}
	goMod := "module example.com/sdkapp\n\ngo " + goVersion + "\n\nrequire github.com/DonaldMurillo/gofastr v0.0.0\n\nreplace github.com/DonaldMurillo/gofastr => " + repoRoot + "\n"
	if err := os.WriteFile(filepath.Join(dir, "go.mod"), []byte(goMod), 0o644); err != nil {
		t.Fatal(err)
	}
	if err := copyGoSum(repoRoot, dir); err != nil {
		t.Fatalf("copy go.sum: %v", err)
	}
	if err := os.WriteFile(filepath.Join(dir, "gofastr.yml"), []byte(`app:
  name: sdkapp
entities:
  - name: posts
    crud: true
    public: true
    fields:
      - name: title
        type: string
        required: true
      - name: views
        type: int
`), 0o644); err != nil {
		t.Fatal(err)
	}

	oldWD, err := os.Getwd()
	if err != nil {
		t.Fatal(err)
	}
	defer os.Chdir(oldWD)
	if err := os.Chdir(dir); err != nil {
		t.Fatal(err)
	}
	generateProject([]string{"--from=gofastr.yml"})
	runGenerateSDK(nil)

	// Regenerating in place must succeed — drift refresh is the whole point.
	runGenerateSDK(nil)

	zipPath := filepath.Join(dir, "gen", "sdk", "dist", sdk.GoArtifact)
	raw, err := os.ReadFile(zipPath)
	if err != nil {
		t.Fatalf("zip not written: %v", err)
	}
	zr, err := zip.NewReader(bytes.NewReader(raw), int64(len(raw)))
	if err != nil {
		t.Fatal(err)
	}
	extract := filepath.Join(dir, "extracted")
	for _, f := range zr.File {
		rc, err := f.Open()
		if err != nil {
			t.Fatal(err)
		}
		var buf bytes.Buffer
		if _, err := buf.ReadFrom(rc); err != nil {
			t.Fatal(err)
		}
		rc.Close()
		dest := filepath.Join(extract, f.Name)
		if err := os.MkdirAll(filepath.Dir(dest), 0o755); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(dest, buf.Bytes(), 0o644); err != nil {
			t.Fatal(err)
		}
	}

	moduleDir := filepath.Join(extract, "sdkapp-sdk")
	cmd := exec.Command("go", "build", "./...")
	cmd.Dir = moduleDir
	out, err := cmd.CombinedOutput()
	if err != nil {
		t.Fatalf("downloaded Go SDK does not build standalone: %v\n%s", err, out)
	}

	// The manifest the app will serve must validate and match the entities.
	m, err := sdk.ReadManifest(os.DirFS(filepath.Join(dir, "gen", "sdk", "dist")))
	if err != nil {
		t.Fatal(err)
	}
	if len(m.Entities) != 1 || m.Entities[0] != "posts" {
		t.Fatalf("manifest entities: %+v", m.Entities)
	}
}

// A codegen config entry named "sdk" supplies defaults for the direct
// command and drives `gofastr generate --config` via the registered
// in-process generator.
func TestGenerateSDK_CodegenConfigEntry(t *testing.T) {
	repoRoot, err := filepath.Abs(filepath.Join("..", ".."))
	if err != nil {
		t.Fatal(err)
	}
	dir := t.TempDir()
	goVersion, err := repoGoVersion(repoRoot)
	if err != nil {
		t.Fatal(err)
	}
	goMod := "module example.com/sdkapp\n\ngo " + goVersion + "\n\nrequire github.com/DonaldMurillo/gofastr v0.0.0\n\nreplace github.com/DonaldMurillo/gofastr => " + repoRoot + "\n"
	if err := os.WriteFile(filepath.Join(dir, "go.mod"), []byte(goMod), 0o644); err != nil {
		t.Fatal(err)
	}
	if err := copyGoSum(repoRoot, dir); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(dir, "gofastr.yml"), []byte(`app:
  name: sdkapp
entities:
  - name: posts
    crud: true
    public: true
    fields:
      - name: title
        type: string
        required: true
`), 0o644); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(dir, "gofastr.codegen.yml"), []byte(`codegen:
  output: gen
  generators:
    - name: sdk
      output: sdk
      config:
        targets: [js]
        name: configapp
        base_url: "https://cfg.example.com"
`), 0o644); err != nil {
		t.Fatal(err)
	}

	oldWD, err := os.Getwd()
	if err != nil {
		t.Fatal(err)
	}
	defer os.Chdir(oldWD)
	if err := os.Chdir(dir); err != nil {
		t.Fatal(err)
	}
	generateProject([]string{"--from=gofastr.yml"})
	runGenerateSDK(nil)

	// Config-supplied name, target, and base URL took effect.
	readme, err := os.ReadFile(filepath.Join(dir, "gen", "sdk", "js", "README.md"))
	if err != nil {
		t.Fatalf("js README not written: %v", err)
	}
	if !strings.Contains(string(readme), "https://cfg.example.com") {
		t.Error("config base_url ignored")
	}
	if !strings.Contains(string(readme), "configapp") {
		t.Error("config name ignored")
	}
	if _, err := os.Stat(filepath.Join(dir, "gen", "sdk", "go")); !os.IsNotExist(err) {
		t.Error("targets: [js] should skip the go tree")
	}
	m, err := sdk.ReadManifest(os.DirFS(filepath.Join(dir, "gen", "sdk", "dist")))
	if err != nil {
		t.Fatal(err)
	}
	if _, ok := m.Artifacts["go"]; ok {
		t.Error("manifest lists a go artifact that was not generated")
	}

	// The same entry must also run under `gofastr generate --config` via
	// the registered in-process generator (the runner errors on
	// unregistered names otherwise).
	if err := os.RemoveAll(filepath.Join(dir, "gen", "sdk")); err != nil {
		t.Fatal(err)
	}
	generateProject([]string{"--config=gofastr.codegen.yml"})
	if _, err := os.Stat(filepath.Join(dir, "gen", "sdk", "js", "client.js")); err != nil {
		t.Fatalf("registry path did not emit client.js: %v", err)
	}
	if _, err := sdk.ReadManifest(os.DirFS(filepath.Join(dir, "gen", "sdk", "dist"))); err != nil {
		t.Fatalf("registry path did not emit a valid manifest: %v", err)
	}
}
