package main

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/DonaldMurillo/gofastr/core/schema"
	"github.com/DonaldMurillo/gofastr/framework"
)

func runGenerate(args []string) {
	if len(args) == 0 || strings.HasPrefix(args[0], "--") {
		for _, a := range args {
			if a == "--watch" {
				runGenerateWatch(args)
				return
			}
		}
		generateProject(args)
		return
	}

	resourceType := args[0]
	switch resourceType {
	case "entity":
		generateEntity(args[1:])
	case "all":
		generateProject(args[1:])
	case "ts", "typescript":
		runGenerateTS(args[1:])
	default:
		fail("Unknown resource type: %s", resourceType)
		info("Supported: all, entity")
		os.Exit(1)
	}
}

func generateProject(args []string) {
	options := parseGenerateOptions(args)
	decls, err := framework.LoadEntityDeclarations(options.entitiesDir)
	if err != nil {
		if os.IsNotExist(err) {
			fail("Directory %q not found.", options.entitiesDir)
			info("Create JSON declarations in entities/ or run: gofastr generate entity post title:string")
			os.Exit(1)
		}
		fail("Failed to load entity declarations: %v", err)
		os.Exit(1)
	}
	if len(decls) == 0 {
		fail("No entity declarations found in %s.", options.entitiesDir)
		info("Add files like entities/posts.json or run: gofastr generate entity post title:string")
		os.Exit(1)
	}

	files, err := renderGeneratedProject(decls)
	if err != nil {
		fail("Code generation failed: %v", err)
		os.Exit(1)
	}

	if options.dryRun {
		if options.json {
			printGeneratedFilesJSON(files)
			return
		}
		info("Would generate %d files in %s:", len(files), options.outputDir)
		for _, file := range files {
			fmt.Printf("    %s\n", filepath.Join(options.outputDir, file.name))
		}
		return
	}

	if err := validateOutputDir(options.outputDir); err != nil {
		fail("%v", err)
		os.Exit(1)
	}
	if options.clean {
		if err := safeCleanOutputDir(options.outputDir); err != nil {
			fail("Failed to clean %s: %v", options.outputDir, err)
			os.Exit(1)
		}
	}
	if err := os.MkdirAll(options.outputDir, 0o755); err != nil {
		fail("Failed to create %s: %v", options.outputDir, err)
		os.Exit(1)
	}
	for _, file := range files {
		path := filepath.Join(options.outputDir, file.name)
		// file.name may contain subdirectories (e.g. "client/client.go") so
		// ensure the parent directory exists before writing.
		if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
			fail("Failed to create %s: %v", filepath.Dir(path), err)
			os.Exit(1)
		}
		if err := os.WriteFile(path, []byte(file.content), 0o644); err != nil {
			fail("Failed to write %s: %v", path, err)
			os.Exit(1)
		}
	}
	if options.json {
		printGeneratedFilesJSON(files)
		return
	}
	success("Generated %d file(s) in %s", len(files), options.outputDir)
}

type generateOptions struct {
	entitiesDir string
	outputDir   string
	clean       bool
	dryRun      bool
	json        bool
}

func parseGenerateOptions(args []string) generateOptions {
	options := generateOptions{entitiesDir: "entities", outputDir: filepath.Join(".gofastr", "entities"), clean: true}
	for _, arg := range args {
		switch {
		case arg == "--dry-run":
			options.dryRun = true
		case arg == "--json":
			options.json = true
		case arg == "--clean":
			options.clean = true
		case arg == "--no-clean":
			options.clean = false
		case strings.HasPrefix(arg, "--entities="):
			options.entitiesDir = strings.TrimPrefix(arg, "--entities=")
		case strings.HasPrefix(arg, "--out="):
			options.outputDir = strings.TrimPrefix(arg, "--out=")
		}
	}
	return options
}

type generatedFile struct {
	name    string
	content string
}

func renderGeneratedProject(decls []framework.EntityDeclaration) ([]generatedFile, error) {
	sort.Slice(decls, func(i, j int) bool { return decls[i].Name < decls[j].Name })
	var register strings.Builder
	register.WriteString(`// Code generated by gofastr. DO NOT EDIT.
package entities

import (
	"github.com/DonaldMurillo/gofastr/core/schema"
	"github.com/DonaldMurillo/gofastr/framework"
)

func boolPtr(v bool) *bool { return &v }
func floatPtr(v float64) *float64 { return &v }

// RegisterAll registers every generated entity declaration with app.
func RegisterAll(app *framework.App) {
`)
	for _, decl := range decls {
		if _, err := decl.Config(); err != nil {
			return nil, err
		}
		if len(decl.Endpoints) > 0 {
			return nil, fmt.Errorf("entity %q: code generation does not support endpoints — endpoints require Go handlers and must be wired in code (use app.Entity with EntityConfig.Endpoints)", decl.Name)
		}
		fragment, err := renderEntityRegistration(decl)
		if err != nil {
			return nil, fmt.Errorf("entity %q: %w", decl.Name, err)
		}
		register.WriteString(fragment)
	}
	register.WriteString("}\n")

	var models strings.Builder
	models.WriteString("// Code generated by gofastr. DO NOT EDIT.\npackage entities\n\n")
	for _, decl := range decls {
		models.WriteString(renderEntityModel(decl))
	}
	return []generatedFile{
		{name: "register.go", content: register.String()},
		{name: "models.go", content: models.String()},
		{name: "columns.go", content: renderColumns(decls)},
		{name: "repo.go", content: renderRepos(decls)},
		{name: "events.go", content: renderEvents(decls)},
		// Generated client lives in its own package so consumers can import
		// it without dragging the server-side schema/framework deps along.
		{name: "client/client.go", content: renderClient(decls)},
	}, nil
}

func renderEntityRegistration(decl framework.EntityDeclaration) (string, error) {
	var sb strings.Builder
	structName := toCamelCase(decl.Name)
	sb.WriteString(fmt.Sprintf("\tapp.Entity(%q, framework.EntityConfig{\n", decl.Name))
	if decl.Table != "" {
		sb.WriteString(fmt.Sprintf("\t\tTable: %q,\n", decl.Table))
	}
	sb.WriteString("\t\tFields: []schema.Field{\n")
	for _, field := range decl.Fields {
		literal, err := renderFieldLiteral(field)
		if err != nil {
			return "", fmt.Errorf("field %q: %w", field.Name, err)
		}
		sb.WriteString("\t\t\t" + literal + ",\n")
	}
	sb.WriteString("\t\t},\n")
	if len(decl.Relations) > 0 {
		sb.WriteString("\t\tRelations: []framework.Relation{\n")
		for _, rel := range decl.Relations {
			sb.WriteString("\t\t\t" + renderRelationLiteral(rel) + ",\n")
		}
		sb.WriteString("\t\t},\n")
	}
	if decl.SoftDelete {
		sb.WriteString("\t\tSoftDelete: true,\n")
	}
	if decl.MultiTenant {
		sb.WriteString("\t\tMultiTenant: true,\n")
	}
	if decl.CRUD != nil {
		sb.WriteString(fmt.Sprintf("\t\tCRUD: boolPtr(%t),\n", *decl.CRUD))
	}
	if decl.MCP {
		sb.WriteString("\t\tMCP: true,\n")
	}
	sb.WriteString("\t}")
	if decl.Timestamps != nil {
		sb.WriteString(fmt.Sprintf(".WithTimestamps(%t)", *decl.Timestamps))
	}
	sb.WriteString(")\n")
	sb.WriteString(fmt.Sprintf("\t_ = %s{}\n", structName))
	return sb.String(), nil
}

func renderFieldLiteral(field framework.FieldDeclaration) (string, error) {
	typeConst, err := schemaConstName(field.Type)
	if err != nil {
		return "", err
	}
	autoConst, err := autoGenerateConstName(field.AutoGenerate)
	if err != nil {
		return "", err
	}
	var parts []string
	parts = append(parts, fmt.Sprintf("Name: %q", field.Name))
	parts = append(parts, fmt.Sprintf("Type: schema.%s", typeConst))
	if field.Required {
		parts = append(parts, "Required: true")
	}
	if field.Unique {
		parts = append(parts, "Unique: true")
	}
	if field.ReadOnly {
		parts = append(parts, "ReadOnly: true")
	}
	if field.Hidden {
		parts = append(parts, "Hidden: true")
	}
	if field.Default != nil {
		literal, err := renderGoLiteral(field.Default)
		if err != nil {
			return "", fmt.Errorf("default value: %w", err)
		}
		parts = append(parts, "Default: "+literal)
	}
	if autoConst != "AutoNone" {
		parts = append(parts, "AutoGenerate: schema."+autoConst)
	}
	if field.Max != nil {
		parts = append(parts, fmt.Sprintf("Max: floatPtr(%g)", *field.Max))
	}
	if field.Min != nil {
		parts = append(parts, fmt.Sprintf("Min: floatPtr(%g)", *field.Min))
	}
	if field.Pattern != "" {
		parts = append(parts, fmt.Sprintf("Pattern: %q", field.Pattern))
	}
	if len(field.Values) > 0 {
		quoted := make([]string, len(field.Values))
		for i, value := range field.Values {
			quoted[i] = fmt.Sprintf("%q", value)
		}
		parts = append(parts, "Values: []string{"+strings.Join(quoted, ", ")+"}")
	}
	if field.To != "" {
		parts = append(parts, fmt.Sprintf("To: %q", field.To))
	}
	if field.Many {
		parts = append(parts, "Many: true")
	}
	return "{" + strings.Join(parts, ", ") + "}", nil
}

func renderRelationLiteral(rel framework.Relation) string {
	var parts []string
	parts = append(parts, fmt.Sprintf("Type: framework.%s", relationTypeConst(rel.Type)))
	parts = append(parts, fmt.Sprintf("Name: %q", rel.Name))
	parts = append(parts, fmt.Sprintf("Entity: %q", rel.Entity))
	if rel.ForeignKey != "" {
		parts = append(parts, fmt.Sprintf("ForeignKey: %q", rel.ForeignKey))
	}
	if rel.Through != "" {
		parts = append(parts, fmt.Sprintf("Through: %q", rel.Through))
	}
	if rel.LocalKey != "" {
		parts = append(parts, fmt.Sprintf("LocalKey: %q", rel.LocalKey))
	}
	if rel.ForeignKeyTarget != "" {
		parts = append(parts, fmt.Sprintf("ForeignKeyTarget: %q", rel.ForeignKeyTarget))
	}
	return "{" + strings.Join(parts, ", ") + "}"
}

func relationTypeConst(t framework.RelationType) string {
	switch t {
	case framework.RelHasOne:
		return "RelHasOne"
	case framework.RelHasMany:
		return "RelHasMany"
	case framework.RelManyToOne:
		return "RelManyToOne"
	case framework.RelManyToMany:
		return "RelManyToMany"
	default:
		return "RelManyToOne"
	}
}

func renderGoLiteral(value any) (string, error) {
	switch v := value.(type) {
	case nil:
		return "nil", nil
	case bool:
		return fmt.Sprintf("%t", v), nil
	case string:
		return fmt.Sprintf("%q", v), nil
	case float64:
		if v == float64(int64(v)) {
			return fmt.Sprintf("%d", int64(v)), nil
		}
		return fmt.Sprintf("%g", v), nil
	case int, int32, int64:
		return fmt.Sprintf("%d", v), nil
	default:
		return "", fmt.Errorf("unsupported default literal of type %T", value)
	}
}

func renderEntityModel(decl framework.EntityDeclaration) string {
	structName := toCamelCase(decl.Name)
	var sb strings.Builder
	sb.WriteString(fmt.Sprintf("type %s struct {\n", structName))
	sb.WriteString("\tID string `json:\"id\"`\n")
	for _, field := range decl.Fields {
		if field.Name == "id" {
			continue
		}
		sb.WriteString(fmt.Sprintf("\t%s %s `json:\"%s,omitempty\"`\n", toCamelCase(field.Name), goTypeForField(field.Type), toCamelJSON(field.Name)))
	}
	// Relation fields — populated by TypedQuery.Include() and Repo.Get(...,
	// includes...). Singular relations (HasOne/BelongsTo) get *Target;
	// collections (HasMany/ManyToMany) get []*Target. Pointer so the absent
	// case marshals as null (matches the framework's nil-for-missing
	// contract).
	for _, rel := range decl.Relations {
		targetStruct := toCamelCase(rel.Entity)
		fieldName := toCamelCase(rel.Name)
		jsonTag := toCamelJSON(rel.Name)
		switch rel.Type {
		case framework.RelHasOne, framework.RelManyToOne:
			sb.WriteString(fmt.Sprintf("\t%s *%s `json:\"%s,omitempty\"`\n", fieldName, targetStruct, jsonTag))
		case framework.RelHasMany, framework.RelManyToMany:
			sb.WriteString(fmt.Sprintf("\t%s []*%s `json:\"%s,omitempty\"`\n", fieldName, targetStruct, jsonTag))
		}
	}
	sb.WriteString("}\n\n")
	return sb.String()
}

func schemaConstName(value string) (string, error) {
	switch strings.ToLower(value) {
	case "", "string":
		return "String", nil
	case "text":
		return "Text", nil
	case "int", "integer":
		return "Int", nil
	case "float", "number":
		return "Float", nil
	case "decimal":
		return "Decimal", nil
	case "bool", "boolean":
		return "Bool", nil
	case "enum":
		return "Enum", nil
	case "uuid":
		return "UUID", nil
	case "timestamp", "datetime":
		return "Timestamp", nil
	case "date":
		return "Date", nil
	case "json":
		return "JSON", nil
	case "relation":
		return "Relation", nil
	case "image":
		return "Image", nil
	case "file":
		return "File", nil
	default:
		return "", fmt.Errorf("unknown field type %q", value)
	}
}

func autoGenerateConstName(value string) (string, error) {
	switch strings.ToLower(strings.TrimSpace(value)) {
	case "", "none":
		return "AutoNone", nil
	case "uuid":
		return "AutoUUID", nil
	case "timestamp":
		return "AutoTimestamp", nil
	case "increment", "auto_increment":
		return "AutoIncrement", nil
	default:
		return "", fmt.Errorf("unknown auto_generate %q", value)
	}
}

func goTypeForField(value string) string {
	switch strings.ToLower(value) {
	case "int", "integer":
		return "int"
	case "float", "number":
		return "float64"
	case "bool", "boolean":
		return "bool"
	case "json":
		return "map[string]any"
	default:
		return "string"
	}
}

func toCamelJSON(value string) string {
	camel := toCamelCase(value)
	if camel == "" {
		return ""
	}
	return strings.ToLower(camel[:1]) + camel[1:]
}

// validateOutputDir rejects paths that would be unsafe to clean (the cwd, the
// FS root, absolute paths, parent traversals, or empty input).
func validateOutputDir(dir string) error {
	if strings.TrimSpace(dir) == "" {
		return fmt.Errorf("--out must not be empty")
	}
	clean := filepath.Clean(dir)
	if filepath.IsAbs(clean) {
		return fmt.Errorf("--out must be a relative path inside the project (got %q)", dir)
	}
	if clean == "." || clean == ".." {
		return fmt.Errorf("--out=%q would target the working directory; choose a subdirectory like .gofastr/entities", dir)
	}
	for _, part := range strings.Split(clean, string(filepath.Separator)) {
		if part == ".." {
			return fmt.Errorf("--out=%q must not contain parent directory traversal", dir)
		}
	}
	return nil
}

// safeCleanOutputDir removes only the files this generator owns. It refuses to
// remove the directory if it contains files the generator did not write — this
// prevents accidental data loss when --out points at a populated directory.
func safeCleanOutputDir(dir string) error {
	info, err := os.Stat(dir)
	if err != nil {
		if os.IsNotExist(err) {
			return nil
		}
		return err
	}
	if !info.IsDir() {
		return fmt.Errorf("%s exists and is not a directory", dir)
	}
	entries, err := os.ReadDir(dir)
	if err != nil {
		return err
	}
	owned := map[string]bool{"register.go": true, "models.go": true}
	for _, entry := range entries {
		if entry.IsDir() || !owned[entry.Name()] {
			return fmt.Errorf("refusing to clean %s — contains unknown entry %q (move it or use --no-clean)", dir, entry.Name())
		}
	}
	for name := range owned {
		path := filepath.Join(dir, name)
		if err := os.Remove(path); err != nil && !os.IsNotExist(err) {
			return err
		}
	}
	return nil
}

func printGeneratedFilesJSON(files []generatedFile) {
	fmt.Println(`{"files":[`)
	for i, file := range files {
		comma := ","
		if i == len(files)-1 {
			comma = ""
		}
		fmt.Printf("  {\"path\":%q,\"size\":%d}%s\n", file.name, len(file.content), comma)
	}
	fmt.Println(`]}`)
}

func generateEntity(args []string) {
	if len(args) == 0 {
		fail("Entity name required.")
		info("Usage: gofastr generate entity <name> [field:definitions...]")
		os.Exit(1)
	}

	entityName := args[0]
	fieldDefs := args[1:]

	if len(fieldDefs) == 0 {
		fieldDefs = []string{"name:string"}
		info("No fields specified, using default: name:string")
	}

	// Parse field definitions: "name:type:flags"
	type fieldInfo struct {
		Name     string
		Type     schema.FieldType
		Required bool
		Unique   bool
	}
	var fields []fieldInfo

	for _, def := range fieldDefs {
		parts := strings.Split(def, ":")
		if len(parts) < 2 {
			fail("Invalid field definition: %s (expected name:type)", def)
			os.Exit(1)
		}

		fName := parts[0]
		fTypeStr := strings.ToLower(parts[1])
		required := false
		unique := false

		for _, flag := range parts[2:] {
			switch strings.ToLower(flag) {
			case "required":
				required = true
			case "unique":
				unique = true
			}
		}

		var fType schema.FieldType
		switch fTypeStr {
		case "string", "text":
			fType = schema.String
		case "int", "integer":
			fType = schema.Int
		case "float", "number":
			fType = schema.Float
		case "bool", "boolean":
			fType = schema.Bool
		case "date", "datetime", "timestamp":
			fType = schema.String // timestamps handled as strings for now
		case "enum":
			fType = schema.Enum
		default:
			fType = schema.String
			info("Unknown type %q, defaulting to string", fTypeStr)
		}

		fields = append(fields, fieldInfo{
			Name:     fName,
			Type:     fType,
			Required: required,
			Unique:   unique,
		})
	}

	// Generate Go file
	tableName := toSnakeCase(entityName)
	structName := toCamelCase(entityName)

	var sb strings.Builder
	sb.WriteString(fmt.Sprintf(`package entities

import (
	"github.com/DonaldMurillo/gofastr/core/schema"
	"github.com/DonaldMurillo/gofastr/framework"
)

// %s is auto-generated. Edit freely.
func register%s(app *framework.App) {
	app.Entity("%s", framework.EntityConfig{
		Table: "%s",
		Fields: []schema.Field{
`, structName, structName, entityName, tableName))

	for _, f := range fields {
		sb.WriteString(fmt.Sprintf("\t\t\t{Name: %q, Type: schema.%s", f.Name, fieldTypeConst(f.Type)))
		if f.Required {
			sb.WriteString(", Required: true")
		}
		if f.Unique {
			sb.WriteString(", Unique: true")
		}
		sb.WriteString("},\n")
	}

	sb.WriteString(`		},
	})
}
`)

	// Ensure entities directory exists
	entitiesDir := "entities"
	if _, err := os.Stat(entitiesDir); os.IsNotExist(err) {
		if err := os.MkdirAll(entitiesDir, 0o755); err != nil {
			fail("Failed to create entities directory: %v", err)
			os.Exit(1)
		}
	}

	filename := filepath.Join(entitiesDir, tableName+".go")
	if _, err := os.Stat(filename); err == nil {
		fail("File %s already exists. Remove it first or use a different name.", filename)
		os.Exit(1)
	}

	if err := os.WriteFile(filename, []byte(sb.String()), 0o644); err != nil {
		fail("Failed to write %s: %v", filename, err)
		os.Exit(1)
	}

	success("Generated entity %s → %s", bold(entityName), filename)
	info("Don't forget to call register%s(app) in your entities.go", structName)
}

func fieldTypeConst(ft schema.FieldType) string {
	switch ft {
	case schema.String:
		return "String"
	case schema.Int:
		return "Int"
	case schema.Float:
		return "Float"
	case schema.Bool:
		return "Bool"
	case schema.Enum:
		return "Enum"
	default:
		return "String"
	}
}

func toSnakeCase(s string) string {
	var result []byte
	for i, r := range s {
		if i > 0 && r >= 'A' && r <= 'Z' {
			result = append(result, '_')
		}
		result = append(result, byte(strings.ToLower(string(r))[0]))
	}
	return string(result)
}

func toCamelCase(s string) string {
	parts := strings.FieldsFunc(s, func(r rune) bool {
		return r == '_' || r == '-' || r == ' '
	})
	var result string
	for _, p := range parts {
		if len(p) > 0 {
			result += strings.ToUpper(p[:1]) + p[1:]
		}
	}
	return result
}
