package main

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"

	"github.com/gofastr/gofastr/framework"
)

func TestRenderGeneratedProjectFromDeclarations(t *testing.T) {
	crud := true
	timestamps := false
	files, err := renderGeneratedProject([]framework.EntityDeclaration{
		{
			Name:       "posts",
			Table:      "posts",
			CRUD:       &crud,
			MCP:        true,
			Timestamps: &timestamps,
			Fields: []framework.FieldDeclaration{
				{Name: "title", Type: "string", Required: true, Max: floatPtrTest(120)},
				{Name: "published", Type: "bool"},
			},
		},
	})
	if err != nil {
		t.Fatalf("renderGeneratedProject: %v", err)
	}
	if len(files) != 5 {
		t.Fatalf("files len = %d, want 5 (register, models, columns, repo, events)", len(files))
	}
	byName := map[string]string{}
	for _, f := range files {
		byName[f.name] = f.content
	}

	for _, want := range []string{
		"// Code generated by gofastr. DO NOT EDIT.",
		"func RegisterAll(app *framework.App)",
		`app.Entity("posts", framework.EntityConfig{`,
		`Type: schema.String`,
		`CRUD: boolPtr(true)`,
		`MCP: true`,
		`.WithTimestamps(false))`,
	} {
		if !strings.Contains(byName["register.go"], want) {
			t.Fatalf("register.go missing %q:\n%s", want, byName["register.go"])
		}
	}
	if !strings.Contains(byName["models.go"], "type Posts struct") {
		t.Fatalf("models.go missing model:\n%s", byName["models.go"])
	}
	for _, want := range []string{
		"PostsTitle = framework.NewStringColumn(\"title\")",
		"PostsPublished = framework.NewBoolColumn(\"published\")",
	} {
		if !strings.Contains(byName["columns.go"], want) {
			t.Fatalf("columns.go missing %q:\n%s", want, byName["columns.go"])
		}
	}
	for _, want := range []string{
		"type PostsRepo struct {",
		"func NewPostsRepo(app *framework.App) *PostsRepo",
		"func (r *PostsRepo) Create(ctx context.Context, row *Posts) error",
		"func (r *PostsRepo) Query() *framework.TypedQuery[Posts]",
		"WithTx(tx *sql.Tx) *PostsRepo",
	} {
		if !strings.Contains(byName["repo.go"], want) {
			t.Fatalf("repo.go missing %q:\n%s", want, byName["repo.go"])
		}
	}
}

func TestLoadEntityDeclarationsForGenerator(t *testing.T) {
	dir := t.TempDir()
	if err := os.WriteFile(filepath.Join(dir, "posts.json"), []byte(`{
		"name":"posts",
		"fields":[{"name":"title","type":"string","required":true}],
		"crud":true
	}`), 0o644); err != nil {
		t.Fatal(err)
	}
	decls, err := framework.LoadEntityDeclarations(dir)
	if err != nil {
		t.Fatalf("LoadEntityDeclarations: %v", err)
	}
	files, err := renderGeneratedProject(decls)
	if err != nil {
		t.Fatalf("renderGeneratedProject: %v", err)
	}
	if !strings.Contains(files[0].content, `Name: "title"`) {
		t.Fatalf("generated content missing title field:\n%s", files[0].content)
	}
}

func TestGenerateProjectE2EGeneratedPackageBuilds(t *testing.T) {
	repoRoot, err := filepath.Abs(filepath.Join("..", ".."))
	if err != nil {
		t.Fatal(err)
	}
	dir := t.TempDir()
	goVersion, err := repoGoVersion(repoRoot)
	if err != nil {
		t.Fatalf("repoGoVersion: %v", err)
	}
	goMod := "module example.com/generated\n\ngo " + goVersion + "\n\nrequire github.com/gofastr/gofastr v0.0.0\n\nreplace github.com/gofastr/gofastr => " + repoRoot + "\n"
	if err := os.WriteFile(filepath.Join(dir, "go.mod"), []byte(goMod), 0o644); err != nil {
		t.Fatal(err)
	}
	if err := os.Mkdir(filepath.Join(dir, "entities"), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(dir, "entities", "posts.json"), []byte(`{
		"name":"posts",
		"fields":[{"name":"title","type":"string","required":true},{"name":"views","type":"int"}],
		"crud":true,
		"mcp":true
	}`), 0o644); err != nil {
		t.Fatal(err)
	}

	oldWD, err := os.Getwd()
	if err != nil {
		t.Fatal(err)
	}
	defer os.Chdir(oldWD)
	if err := os.Chdir(dir); err != nil {
		t.Fatal(err)
	}
	generateProject(nil)

	cmd := exec.Command("go", "test", "./.gofastr/entities")
	cmd.Dir = dir
	output, err := cmd.CombinedOutput()
	if err != nil {
		t.Fatalf("generated package did not build: %v\n%s", err, output)
	}
}

func floatPtrTest(v float64) *float64 {
	return &v
}

func repoGoVersion(repoRoot string) (string, error) {
	data, err := os.ReadFile(filepath.Join(repoRoot, "go.mod"))
	if err != nil {
		return "", err
	}
	for _, line := range strings.Split(string(data), "\n") {
		fields := strings.Fields(line)
		if len(fields) >= 2 && fields[0] == "go" {
			return fields[1], nil
		}
	}
	return "", fmt.Errorf("go directive not found in %s/go.mod", repoRoot)
}
