package main

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// runTheme dispatches `gofastr theme <subcommand>`.
func runTheme(args []string) {
	if len(args) == 0 {
		printThemeHelp()
		return
	}
	switch args[0] {
	case "init":
		runThemeInit(args[1:])
	case "--help", "-h", "help":
		printThemeHelp()
	default:
		fmt.Printf("%s Unknown theme subcommand: %s\n\n", red("✗"), args[0])
		printThemeHelp()
		osExit(1)
	}
}

func printThemeHelp() {
	fmt.Println("Usage: gofastr theme <subcommand>")
	fmt.Println()
	fmt.Println("Subcommands:")
	fmt.Println("  init     Scaffold a starter theme.go in the current project.")
}

// runThemeInit writes a starter theme.go to the user's project. The
// generated file is the full DefaultTheme inlined as a Go file the
// user owns forever — edit values to customize, the framework never
// touches it again.
//
// Refuses to overwrite an existing file; pass --force to opt in.
func runThemeInit(args []string) {
	dest := "theme/theme.go"
	force := false
	for _, a := range args {
		switch {
		case a == "--force" || a == "-f":
			force = true
		case strings.HasPrefix(a, "--out=") || strings.HasPrefix(a, "-o="):
			dest = strings.SplitN(a, "=", 2)[1]
		case a == "--help" || a == "-h":
			fmt.Println("Usage: gofastr theme init [--out=path] [--force]")
			fmt.Println()
			fmt.Println("Writes a starter theme.go to ./theme/theme.go (override via --out).")
			fmt.Println("Refuses to overwrite an existing file unless --force is set.")
			return
		default:
			fmt.Printf("%s Unknown flag: %s\n", red("✗"), a)
			osExit(1)
		}
	}

	if _, err := os.Stat(dest); err == nil && !force {
		fmt.Printf("%s %s already exists. Pass --force to overwrite.\n", red("✗"), dest)
		osExit(1)
	}

	if err := os.MkdirAll(filepath.Dir(dest), 0o755); err != nil {
		fmt.Printf("%s mkdir %s: %v\n", red("✗"), filepath.Dir(dest), err)
		osExit(1)
	}

	if err := os.WriteFile(dest, []byte(themeStarter), 0o644); err != nil {
		fmt.Printf("%s write %s: %v\n", red("✗"), dest, err)
		osExit(1)
	}

	fmt.Printf("%s wrote %s — edit values to customize your theme.\n", green("✓"), dest)
	fmt.Println()
	fmt.Println("Next — wire it into main.go:")
	fmt.Println()
	fmt.Println("    import (")
	fmt.Println("        \"github.com/DonaldMurillo/gofastr/core-ui/app\"")
	fmt.Println("        \"github.com/DonaldMurillo/gofastr/framework\"")
	fmt.Println("        \"github.com/DonaldMurillo/gofastr/framework/uihost\"")
	fmt.Println("        \"<your-module>/theme\"")
	fmt.Println("    )")
	fmt.Println()
	fmt.Println("    func main() {")
	fmt.Println("        site := app.NewApp(\"MyApp\").WithTheme(theme.App)")
	fmt.Println("        site.Register(\"/\", &HomeScreen{}, nil) // HomeScreen implements component.Component + ScreenSpec")
	fmt.Println()
	fmt.Println("        host := uihost.New(site)")
	fmt.Println("        fw := framework.NewApp()")
	fmt.Println("        fw.Mount(host)              // fwApp owns the listener; host attaches its routes")
	fmt.Println("        fw.Start(\":8080\")")
	fmt.Println("    }")
	fmt.Println()
	fmt.Println("Then `go mod tidy && go run .`. Reference tokens in components")
	fmt.Println("via theme.App.Colors.Primary.CSS() (or {colors.primary} in")
	fmt.Println("StyleSheet builders). See examples/site/main.go for a full setup.")
}

// themeStarter is the file the scaffold writes. The framework
// auto-derives token Names from the struct field path, so the user
// writes only Values. The CSS variable for Colors.Primary is
// `--color-primary` (lowercase + kebab) — no second source of truth.
const themeStarter = `// Package theme defines this app's typed design system.
//
// Every field of style.Theme is required — the framework needs
// every primitive token to render correctly. This file was
// generated by ` + "`gofastr theme init`" + ` with the framework's
// defaults; edit values to match your brand. The framework never
// regenerates this file.
//
// Reference tokens at render sites:
//   theme.App.Colors.Primary.CSS()  → "var(--color-primary)"
//   theme.App.Colors.Primary.Value  → "#4F46E5" (literal)
//
// Token names auto-derive from struct field paths
// (Colors.PrimaryFg → --color-primary-fg) so you only write Value.
package theme

import (
	"time"

	"github.com/DonaldMurillo/gofastr/core-ui/style"
)

// App is the app's design system. Pass it to the host:
//
//	app.WithTheme(theme.App)
//
// ── Brand: edit these first ─────────────────────────────────────────
var App = style.Theme{
	Name: "app",
	Colors: style.ColorSet{
		// Primary brand colors — the most-edited values.
		Primary:   style.Color{Value: "#4F46E5"},
		PrimaryFg: style.Color{Value: "#FFFFFF"},
		Accent:    style.Color{Value: "#7C3AED"},

		// Status colors — WCAG-AA against white text.
		Danger:  style.Color{Value: "#DC2626"},
		Success: style.Color{Value: "#15803D"},
		Warning: style.Color{Value: "#A16207"},
		Info:    style.Color{Value: "#2563EB"},

		// Surfaces + text — usually leave alone.
		Secondary:    style.Color{Value: "#6B7280"},
		SecondaryFg:  style.Color{Value: "#FFFFFF"},
		Background:   style.Color{Value: "#F9FAFB"},
		Surface:      style.Color{Value: "#FFFFFF"},
		SurfaceSoft:  style.Color{Value: "#F4F4F5"},
		Text:         style.Color{Value: "#18181B"},
		TextMuted:    style.Color{Value: "#52525B"},
		TextSubtle:   style.Color{Value: "#71717A"},
		Border:       style.Color{Value: "#E4E4E7"},
		BorderStrong: style.Color{Value: "#A1A1AA"},
	},

	// ── Scales: rarely edited ──────────────────────────────────────
	Spacing: style.SpacingScale{
		XS: style.Spacing{Value: 2}, SM: style.Spacing{Value: 4}, MD: style.Spacing{Value: 8},
		LG: style.Spacing{Value: 16}, XL: style.Spacing{Value: 24},
		XXL: style.Spacing{Value: 32}, XXXL: style.Spacing{Value: 48},
	},
	Radii: style.RadiusSet{
		None: style.Radius{Name: "none"}, // sentinel: name explicit so zero passes Validate
		SM:   style.Radius{Value: 4}, MD: style.Radius{Value: 8},
		LG: style.Radius{Value: 12}, XL: style.Radius{Value: 16}, Full: style.Radius{Value: 9999},
	},
	Fonts: style.FontSet{
		Body:    style.Font{Value: "'Inter', system-ui, sans-serif"},
		Heading: style.Font{Value: "'Inter', system-ui, sans-serif"},
		Mono:    style.Font{Value: "'JetBrains Mono', monospace"},
	},
	Breakpoints: style.BreakpointSet{
		SM: style.Breakpoint{Value: 640}, MD: style.Breakpoint{Value: 768},
		LG: style.Breakpoint{Value: 1024}, XL: style.Breakpoint{Value: 1280},
		XXL: style.Breakpoint{Value: 1536},
	},
	Shadows: style.ShadowSet{
		None: style.Shadow{Value: "none"},
		SM:   style.Shadow{Value: "0 1px 2px 0 rgba(0,0,0,0.05)"},
		MD:   style.Shadow{Value: "0 4px 6px -1px rgba(0,0,0,0.10), 0 2px 4px -1px rgba(0,0,0,0.06)"},
		LG:   style.Shadow{Value: "0 10px 15px -3px rgba(0,0,0,0.10), 0 4px 6px -2px rgba(0,0,0,0.05)"},
		XL:   style.Shadow{Value: "0 20px 25px -5px rgba(0,0,0,0.10), 0 10px 10px -5px rgba(0,0,0,0.04)"},
	},
	ZIndex: style.ZIndexSet{
		Dropdown: style.ZIndexValue{Value: 100},
		Sticky:   style.ZIndexValue{Value: 200},
		Modal:    style.ZIndexValue{Value: 300},
		Popover:  style.ZIndexValue{Value: 400},
		Toast:    style.ZIndexValue{Value: 500},
	},
	Durations: style.DurationSet{
		Fast:   style.Duration{Value: 150 * time.Millisecond},
		Normal: style.Duration{Value: 250 * time.Millisecond},
		Slow:   style.Duration{Value: 400 * time.Millisecond},
	},
	Typography: style.FontSizeSet{
		XS: style.FontSize{Value: "0.75rem"}, SM: style.FontSize{Value: "0.875rem"},
		Base: style.FontSize{Value: "1rem"}, LG: style.FontSize{Value: "1.125rem"},
		XL: style.FontSize{Value: "1.25rem"}, XXL: style.FontSize{Value: "1.5rem"},
		XXXL: style.FontSize{Value: "1.875rem"},
	},

	// Layout: the WCAG 2.5.5 tap-target floor. ui-button, pagination,
	// inputs, and the mobile hamburger summary all scale to this token.
	Layout: style.LayoutSet{
		TouchTarget: style.Spacing{Value: 44},
	},
}

// init fills in Names that weren't specified explicitly, deriving
// them from struct-field paths in kebab-case. After this runs,
// theme.App.Colors.Primary.Name == "primary".
//
// app.WithTheme also calls AutoFillNames defensively, so this init
// is for users who access App fields directly before host setup
// (rare, but cheap to support).
func init() {
	style.AutoFillNames(&App)
}
`
