package main

import (
	"fmt"
	"go/format"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"time"

	"github.com/DonaldMurillo/gofastr/core-ui/style"
)

// emitThemeGoSource renders t as a complete, gofmt'd theme.go source file
// the user owns forever, the same shape `gofastr theme init` writes, but
// with the edited values.
//
// # Security: every string value is emitted with %q
//
// Theme values are free-form CSS: oklch() expressions, font stacks with
// embedded quotes, shadow lists. A raw backtick literal has no escape
// mechanism, so a single backtick in a value closes it: the same class
// of injection blueprint_emitter_injection_test.go pins for the IR
// emitters. %q produces a Go double-quoted literal that escapes every
// breaking byte (backtick, quote, newline, backslash), so no theme
// value can leave its literal and become syntax. The companion
// TestThemeEditWritebackInjectionSafety drives literal-breaking payloads
// through this emitter and asserts they stay data.
//
// Names are intentionally omitted from every token field: the file ends
// with `func init() { style.AutoFillNames(&App) }`, which derives every
// Name from the Go struct-field path, the same contract `gofastr theme
// init` ships. Emitting Names here would only duplicate what AutoFillNames
// already produces and give a malicious value one more surface to reach.
func emitThemeGoSource(t style.Theme, pkgName string) ([]byte, error) {
	if pkgName == "" {
		pkgName = "theme"
	}
	var b strings.Builder
	b.WriteString("// Package " + pkgName + " defines this app's typed design system.\n")
	b.WriteString("//\n")
	b.WriteString("// Generated by `gofastr theme edit`. Edit values to customise the\n")
	b.WriteString("// brand; the framework never regenerates this file. Token names\n")
	b.WriteString("// auto-derive from struct field paths via style.AutoFillNames.\n")
	b.WriteString("package " + pkgName + "\n\n")
	b.WriteString("import (\n")
	b.WriteString("\t\"time\"\n")
	b.WriteString("\n")
	b.WriteString("\t\"github.com/DonaldMurillo/gofastr/core-ui/style\"\n")
	b.WriteString(")\n\n")
	b.WriteString("// App is this app's design system. Pass it to the host:\n")
	b.WriteString("//\n")
	b.WriteString("//\tapp.WithTheme(theme.App)\n")
	b.WriteString("var App = style.Theme{\n")
	fmt.Fprintf(&b, "\tName: %q,\n", t.Name)

	// DarkColors: sorted for byte-stable output.
	b.WriteString("\tDarkColors: map[string]string{\n")
	for _, k := range sortedStringKeys(t.DarkColors) {
		fmt.Fprintf(&b, "\t\t%q: %q,\n", k, t.DarkColors[k])
	}
	b.WriteString("\t},\n")

	// DarkCode: only emitted when non-empty (the optional code palette).
	if len(t.DarkCode) > 0 {
		b.WriteString("\tDarkCode: map[string]string{\n")
		for _, k := range sortedStringKeys(t.DarkCode) {
			fmt.Fprintf(&b, "\t\t%q: %q,\n", k, t.DarkCode[k])
		}
		b.WriteString("\t},\n")
	}

	emitColorSet(&b, &t.Colors)
	emitSpacingScale(&b, &t.Spacing)
	emitRadiusSet(&b, &t.Radii)
	emitFontSet(&b, &t.Fonts)
	emitBreakpointSet(&b, &t.Breakpoints)
	emitShadowSet(&b, &t.Shadows)
	emitZIndexSet(&b, &t.ZIndex)
	emitDurationSet(&b, &t.Durations)
	emitEasingSet(&b, &t.Easings)
	emitFontSizeSet(&b, &t.Typography)
	emitLayoutSet(&b, &t.Layout)
	emitCodeSet(&b, &t.Code)

	b.WriteString("}\n\n")
	b.WriteString("// init fills in token Names from struct-field paths. After this\n")
	b.WriteString("// runs, theme.App.Colors.Primary.Name == \"primary\".\n")
	b.WriteString("func init() {\n")
	b.WriteString("\tstyle.AutoFillNames(&App)\n")
	b.WriteString("}\n")

	formatted, err := format.Source([]byte(b.String()))
	if err != nil {
		return nil, fmt.Errorf("theme edit: generated source does not parse: %w\n--- source ---\n%s", err, b.String())
	}
	return formatted, nil
}

func emitColorSet(b *strings.Builder, c *style.ColorSet) {
	b.WriteString("\tColors: style.ColorSet{\n")
	emitColor(b, "Primary", c.Primary)
	emitColor(b, "PrimaryFg", c.PrimaryFg)
	emitColor(b, "Secondary", c.Secondary)
	emitColor(b, "SecondaryFg", c.SecondaryFg)
	emitColor(b, "Background", c.Background)
	emitColor(b, "Surface", c.Surface)
	emitColor(b, "SurfaceSoft", c.SurfaceSoft)
	emitColor(b, "Text", c.Text)
	emitColor(b, "TextMuted", c.TextMuted)
	emitColor(b, "TextSubtle", c.TextSubtle)
	emitColor(b, "Border", c.Border)
	emitColor(b, "BorderStrong", c.BorderStrong)
	emitColor(b, "Danger", c.Danger)
	emitColor(b, "Success", c.Success)
	emitColor(b, "Warning", c.Warning)
	emitColor(b, "Info", c.Info)
	emitColor(b, "Accent", c.Accent)
	emitColor(b, "CodeSurface", c.CodeSurface)
	emitColor(b, "CodeText", c.CodeText)
	emitColor(b, "CodeBorder", c.CodeBorder)
	b.WriteString("\t},\n")
}

func emitColor(b *strings.Builder, field string, c style.Color) {
	fmt.Fprintf(b, "\t\t%s: style.Color{Value: %q},\n", field, c.Value)
}

func emitSpacingScale(b *strings.Builder, s *style.SpacingScale) {
	b.WriteString("\tSpacing: style.SpacingScale{\n")
	emitSpacing(b, "XS", s.XS)
	emitSpacing(b, "SM", s.SM)
	emitSpacing(b, "MD", s.MD)
	emitSpacing(b, "LG", s.LG)
	emitSpacing(b, "XL", s.XL)
	emitSpacing(b, "XXL", s.XXL)
	emitSpacing(b, "XXXL", s.XXXL)
	b.WriteString("\t},\n")
}

func emitSpacing(b *strings.Builder, field string, s style.Spacing) {
	fmt.Fprintf(b, "\t\t%s: style.Spacing{Value: %d},\n", field, s.Value)
}

func emitRadiusSet(b *strings.Builder, r *style.RadiusSet) {
	b.WriteString("\tRadii: style.RadiusSet{\n")
	fmt.Fprintf(b, "\t\tNone: style.Radius{Name: %q, Value: %d},\n", "none", r.None.Value)
	fmt.Fprintf(b, "\t\tSM:   style.Radius{Value: %d},\n", r.SM.Value)
	fmt.Fprintf(b, "\t\tMD:   style.Radius{Value: %d},\n", r.MD.Value)
	fmt.Fprintf(b, "\t\tLG:   style.Radius{Value: %d},\n", r.LG.Value)
	fmt.Fprintf(b, "\t\tXL:   style.Radius{Value: %d},\n", r.XL.Value)
	fmt.Fprintf(b, "\t\tFull: style.Radius{Value: %d},\n", r.Full.Value)
	b.WriteString("\t},\n")
}

func emitFontSet(b *strings.Builder, f *style.FontSet) {
	b.WriteString("\tFonts: style.FontSet{\n")
	emitFont(b, "Body", f.Body)
	emitFont(b, "Heading", f.Heading)
	emitFont(b, "Mono", f.Mono)
	b.WriteString("\t},\n")
}

func emitFont(b *strings.Builder, field string, f style.Font) {
	fmt.Fprintf(b, "\t\t%s: style.Font{Value: %q},\n", field, f.Value)
}

func emitBreakpointSet(b *strings.Builder, bp *style.BreakpointSet) {
	b.WriteString("\tBreakpoints: style.BreakpointSet{\n")
	fmt.Fprintf(b, "\t\tSM:  style.Breakpoint{Value: %d},\n", bp.SM.Value)
	fmt.Fprintf(b, "\t\tMD:  style.Breakpoint{Value: %d},\n", bp.MD.Value)
	fmt.Fprintf(b, "\t\tLG:  style.Breakpoint{Value: %d},\n", bp.LG.Value)
	fmt.Fprintf(b, "\t\tXL:  style.Breakpoint{Value: %d},\n", bp.XL.Value)
	fmt.Fprintf(b, "\t\tXXL: style.Breakpoint{Value: %d},\n", bp.XXL.Value)
	b.WriteString("\t},\n")
}

func emitShadowSet(b *strings.Builder, s *style.ShadowSet) {
	b.WriteString("\tShadows: style.ShadowSet{\n")
	emitShadow(b, "None", s.None)
	emitShadow(b, "SM", s.SM)
	emitShadow(b, "MD", s.MD)
	emitShadow(b, "LG", s.LG)
	emitShadow(b, "XL", s.XL)
	b.WriteString("\t},\n")
}

func emitShadow(b *strings.Builder, field string, s style.Shadow) {
	fmt.Fprintf(b, "\t\t%s: style.Shadow{Value: %q},\n", field, s.Value)
}

func emitZIndexSet(b *strings.Builder, z *style.ZIndexSet) {
	b.WriteString("\tZIndex: style.ZIndexSet{\n")
	fmt.Fprintf(b, "\t\tDropdown: style.ZIndexValue{Value: %d},\n", z.Dropdown.Value)
	fmt.Fprintf(b, "\t\tSticky:   style.ZIndexValue{Value: %d},\n", z.Sticky.Value)
	fmt.Fprintf(b, "\t\tModal:    style.ZIndexValue{Value: %d},\n", z.Modal.Value)
	fmt.Fprintf(b, "\t\tPopover:  style.ZIndexValue{Value: %d},\n", z.Popover.Value)
	fmt.Fprintf(b, "\t\tToast:    style.ZIndexValue{Value: %d},\n", z.Toast.Value)
	b.WriteString("\t},\n")
}

func emitDurationSet(b *strings.Builder, d *style.DurationSet) {
	b.WriteString("\tDurations: style.DurationSet{\n")
	emitDuration(b, "Fast", d.Fast)
	emitDuration(b, "Normal", d.Normal)
	emitDuration(b, "Slow", d.Slow)
	emitDuration(b, "OverlayEnter", d.OverlayEnter)
	emitDuration(b, "OverlayExit", d.OverlayExit)
	emitDuration(b, "ToastEnter", d.ToastEnter)
	emitDuration(b, "ToastExit", d.ToastExit)
	emitDuration(b, "DropdownEnter", d.DropdownEnter)
	b.WriteString("\t},\n")
}

func emitDuration(b *strings.Builder, field string, d style.Duration) {
	fmt.Fprintf(b, "\t\t%s: style.Duration{Value: %s},\n", field, durationLiteral(d.Value))
}

// durationLiteral renders a time.Duration as the most readable Go literal
// that reproduces it: whole milliseconds as `N * time.Millisecond`,
// whole microseconds as `N * time.Microsecond`, and anything else as an
// explicit `time.Duration(nanos)` cast. Every form compiles and
// round-trips exactly.
func durationLiteral(d time.Duration) string {
	if d > 0 && d%time.Millisecond == 0 {
		return fmt.Sprintf("%d * time.Millisecond", d/time.Millisecond)
	}
	if d > 0 && d%time.Microsecond == 0 {
		return fmt.Sprintf("%d * time.Microsecond", d/time.Microsecond)
	}
	return fmt.Sprintf("time.Duration(%d)", int64(d))
}

func emitEasingSet(b *strings.Builder, e *style.EasingSet) {
	b.WriteString("\tEasings: style.EasingSet{\n")
	emitEasing(b, "EaseOut", e.EaseOut)
	emitEasing(b, "EaseIn", e.EaseIn)
	emitEasing(b, "EaseInOut", e.EaseInOut)
	emitEasing(b, "Spring", e.Spring)
	b.WriteString("\t},\n")
}

func emitEasing(b *strings.Builder, field string, e style.Easing) {
	fmt.Fprintf(b, "\t\t%s: style.Easing{Value: %q},\n", field, e.Value)
}

func emitFontSizeSet(b *strings.Builder, f *style.FontSizeSet) {
	b.WriteString("\tTypography: style.FontSizeSet{\n")
	emitFontSize(b, "XS", f.XS)
	emitFontSize(b, "SM", f.SM)
	emitFontSize(b, "Base", f.Base)
	emitFontSize(b, "LG", f.LG)
	emitFontSize(b, "XL", f.XL)
	emitFontSize(b, "XXL", f.XXL)
	emitFontSize(b, "XXXL", f.XXXL)
	b.WriteString("\t},\n")
}

func emitFontSize(b *strings.Builder, field string, f style.FontSize) {
	fmt.Fprintf(b, "\t\t%s: style.FontSize{Value: %q},\n", field, f.Value)
}

func emitLayoutSet(b *strings.Builder, l *style.LayoutSet) {
	b.WriteString("\tLayout: style.LayoutSet{\n")
	fmt.Fprintf(b, "\t\tTouchTarget: style.Spacing{Value: %d},\n", l.TouchTarget.Value)
	b.WriteString("\t},\n")
}

func emitCodeSet(b *strings.Builder, c *style.CodeSet) {
	b.WriteString("\tCode: style.CodeSet{\n")
	emitCodeColor(b, "KW", c.KW)
	emitCodeColor(b, "FN", c.FN)
	emitCodeColor(b, "Str", c.Str)
	emitCodeColor(b, "Num", c.Num)
	emitCodeColor(b, "Com", c.Com)
	emitCodeColor(b, "Type", c.Type)
	emitCodeColor(b, "PN", c.PN)
	b.WriteString("\t},\n")
}

func emitCodeColor(b *strings.Builder, field string, c style.CodeColor) {
	fmt.Fprintf(b, "\t\t%s: style.CodeColor{Value: %q},\n", field, c.Value)
}

// sortedStringKeys returns the keys of m in sorted order, or nil for an
// empty/nil map. Used so the emitted DarkColors/DarkCode blocks are
// byte-stable across runs.
func sortedStringKeys(m map[string]string) []string {
	if len(m) == 0 {
		return nil
	}
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}

// packageNameForPath adopts the package clause from another Go file in the
// destination directory. A new directory falls back to its sanitized basename.
func packageNameForPath(p string) string {
	dir := filepath.Dir(p)
	entries, err := os.ReadDir(dir)
	if err == nil {
		target := filepath.Base(p)
		for _, includeTests := range []bool{false, true} {
			for _, entry := range entries {
				name := entry.Name()
				if entry.IsDir() || name == target || !strings.HasSuffix(name, ".go") {
					continue
				}
				isTest := strings.HasSuffix(name, "_test.go")
				if isTest != includeTests {
					continue
				}
				file, err := parser.ParseFile(token.NewFileSet(), filepath.Join(dir, name), nil, parser.PackageClauseOnly)
				if err != nil || file.Name == nil {
					continue
				}
				pkg := file.Name.Name
				if isTest {
					pkg = strings.TrimSuffix(pkg, "_test")
				}
				return pkg
			}
		}
	}

	name := filepath.Base(dir)
	if name == "." || name == string(filepath.Separator) || name == "" {
		return "theme"
	}
	return sanitizePackageName(name)
}

// sanitizePackageName turns a directory name into a legal Go package clause.
//
// The package clause is the ONE string in the emitted file that does not go
// through %q, because it is an identifier rather than a literal. A directory
// called "design-system" therefore produced `package design-system`, which does
// not parse, so Write failed on every attempt with a 500 carrying the whole
// generated file, and nothing was ever written. Same for a leading digit, a
// dot, or a Go keyword.
func sanitizePackageName(name string) string {
	var b strings.Builder
	for _, r := range name {
		switch {
		case r >= 'a' && r <= 'z', r >= 'A' && r <= 'Z', r >= '0' && r <= '9':
			b.WriteRune(r)
		case r == '_':
			b.WriteRune(r)
		default:
			// '-', '.', ' ' and friends become '_' rather than vanishing, so
			// "design-system" reads as "design_system" instead of
			// "designsystem".
			b.WriteRune('_')
		}
	}
	out := b.String()
	out = strings.Trim(out, "_")
	if out == "" {
		return "theme"
	}
	if out[0] >= '0' && out[0] <= '9' {
		out = "_" + out
	}
	if token.Lookup(out).IsKeyword() {
		out += "_"
	}
	return out
}
