package main

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	uitheme "github.com/DonaldMurillo/gofastr/framework/ui/theme"
)

// runTheme dispatches `gofastr theme <subcommand>`.
func runTheme(args []string) {
	if len(args) == 0 {
		printThemeHelp()
		return
	}
	switch args[0] {
	case "init":
		runThemeInit(args[1:])
	case "edit":
		runThemeEdit(args[1:])
	case "--help", "-h", "help":
		printThemeHelp()
	default:
		fmt.Printf("%s Unknown theme subcommand: %s\n\n", red("✗"), args[0])
		printThemeHelp()
		osExit(1)
	}
}

func printThemeHelp() {
	fmt.Println("Usage: gofastr theme <subcommand>")
	fmt.Println()
	fmt.Println("Subcommands:")
	fmt.Println("  init     Scaffold a starter theme.go in the current project.")
	fmt.Println("  edit     Launch a local theme configurator with a live preview.")
}

// runThemeInit writes a starter theme.go to the user's project. The
// generated file is the full DefaultTheme inlined as a Go file the
// user owns forever: edit values to customize, the framework never
// touches it again.
//
// Refuses to overwrite an existing file; pass --force to opt in.
func runThemeInit(args []string) {
	dest := "theme/theme.go"
	force := false
	for _, a := range args {
		switch {
		case a == "--force" || a == "-f":
			force = true
		case strings.HasPrefix(a, "--out=") || strings.HasPrefix(a, "-o="):
			dest = strings.SplitN(a, "=", 2)[1]
		case a == "--help" || a == "-h":
			fmt.Println("Usage: gofastr theme init [--out=path] [--force]")
			fmt.Println()
			fmt.Println("Writes a starter theme.go to ./theme/theme.go (override via --out).")
			fmt.Println("Refuses to overwrite an existing file unless --force is set.")
			return
		default:
			fmt.Printf("%s Unknown flag: %s\n", red("✗"), a)
			osExit(1)
		}
	}

	if _, err := os.Stat(dest); err == nil && !force {
		fmt.Printf("%s %s already exists. Pass --force to overwrite.\n", red("✗"), dest)
		osExit(1)
	}

	if err := os.MkdirAll(filepath.Dir(dest), 0o755); err != nil {
		fmt.Printf("%s mkdir %s: %v\n", red("✗"), filepath.Dir(dest), err)
		osExit(1)
	}

	if err := os.WriteFile(dest, []byte(themeStarter), 0o644); err != nil {
		fmt.Printf("%s write %s: %v\n", red("✗"), dest, err)
		osExit(1)
	}

	fmt.Printf("%s wrote %s: edit values to customize your theme.\n", green("✓"), dest)
	fmt.Println()
	fmt.Println("Next: wire it into main.go:")
	fmt.Println()
	fmt.Println("    import (")
	fmt.Println("        \"github.com/DonaldMurillo/gofastr/core-ui/app\"")
	fmt.Println("        \"github.com/DonaldMurillo/gofastr/framework\"")
	fmt.Println("        \"github.com/DonaldMurillo/gofastr/framework/uihost\"")
	fmt.Println("        \"<your-module>/theme\"")
	fmt.Println("    )")
	fmt.Println()
	fmt.Println("    func main() {")
	fmt.Println("        site := app.NewApp(\"MyApp\").WithTheme(theme.App)")
	fmt.Println("        site.Register(\"/\", &HomeScreen{}, nil) // HomeScreen implements component.Component + ScreenSpec")
	fmt.Println()
	fmt.Println("        host := uihost.New(site)")
	fmt.Println("        fw := framework.NewApp()")
	fmt.Println("        fw.Mount(host)              // fwApp owns the listener; host attaches its routes")
	fmt.Println("        fw.Start(\":8080\")")
	fmt.Println("    }")
	fmt.Println()
	fmt.Println("Then `go mod tidy && go run .`. Reference tokens in components")
	fmt.Println("via theme.App.Colors.Primary.CSS() (or {colors.primary} in")
	fmt.Println("StyleSheet builders). See examples/site/main.go for a full setup.")
}

// themeStarter is the file the scaffold writes: the canonical
// framework theme (framework/ui/theme.Default) through the same
// emitter `gofastr theme edit` writes back with, under the starter's
// orientation header. One source: the emitter writes every field of
// style.Theme by construction, and AutoFillNames (the emitted init)
// derives every token Name from the struct-field path, so the user
// writes only Values. The previous hand-maintained template omitted
// required fields (Colors.CodeSurface, the overlay/toast/dropdown
// durations, the easings) and a fresh scaffold panicked at boot.
var themeStarter = themeStarterSource()

// starterDoc is the explanatory header `gofastr theme init` writes
// above the emitted theme.
var starterDoc = []string{
	"Every field of style.Theme is required: the framework needs",
	"every primitive token to render correctly. This file was",
	"generated by `gofastr theme init` with the framework's",
	"defaults; edit values to match your brand. The framework never",
	"regenerates this file.",
	"",
	"Reference tokens at render sites:",
	"  theme.App.Colors.Primary.CSS()  → \"var(--color-primary)\"",
	"  theme.App.Colors.Primary.Value  → \"#4F46E5\" (literal)",
	"",
	"Token names auto-derive from struct field paths",
	"(Colors.PrimaryFg → --color-primary-fg) so you only write Value.",
}

func themeStarterSource() string {
	t := uitheme.Default()
	// The app's own name, and no component options: the framework's
	// complete default set is compiled into :root anyway, so a host
	// declares Components only to deviate from it.
	t.Name = "app"
	t.Components = nil
	src, err := emitThemeGoSourceWithDoc(t, "theme", starterDoc)
	if err != nil {
		panic("gofastr: theme starter does not parse: " + err.Error())
	}
	return string(src)
}
