// Pins, found by the 2026-09-04 red-probe round, that the additive-
// generation read helpers under writeRoot (fileExistsUnder,
// missingCallSite) joined paths lexically only, so a symlinked file or
// directory inside the project root let those helpers see (and read)
// content outside it; fixed by routing both through an *os.Root, which
// refuses symlink escapes in the kernel.
//
// Property: stats and reads under the generator's writeRoot must stay
// under the root even when a path component is a symlink pointing
// outside it. A real file under the root still reads.
//
// Surfaces: fileExistsUnder, missingCallSite.
package main

import (
	"os"
	"path/filepath"
	"testing"
)

func TestWriteRootSymlinkReadRefused(t *testing.T) {
	writeRoot := t.TempDir()
	outside := t.TempDir()

	if err := os.WriteFile(filepath.Join(outside, "screen_x.go"), []byte("package main"), 0o644); err != nil {
		t.Fatal(err)
	}
	// A main.go outside the root reachable through a leaf symlink, plus
	// a whole directory reachable through a symlinked component.
	if err := os.WriteFile(filepath.Join(outside, "main.go"), []byte("entities.RegisterAll("), 0o644); err != nil {
		t.Fatal(err)
	}
	if err := os.Symlink(filepath.Join(outside, "main.go"), filepath.Join(writeRoot, "main.go")); err != nil {
		t.Fatal(err)
	}
	if err := os.Symlink(outside, filepath.Join(writeRoot, "linked")); err != nil {
		t.Fatal(err)
	}
	// Control: a real file under the root.
	if err := os.WriteFile(filepath.Join(writeRoot, "real.go"), []byte("entities.RegisterAll("), 0o644); err != nil {
		t.Fatal(err)
	}

	if fileExistsUnder(writeRoot, "main.go") {
		t.Error("SECURITY: [generate-rootread] fileExistsUnder saw through a symlinked file out of writeRoot")
	}
	if fileExistsUnder(writeRoot, "linked/screen_x.go") {
		t.Error("SECURITY: [generate-rootread] fileExistsUnder saw through a symlinked directory out of writeRoot")
	}
	if missingCallSite(writeRoot, "main.go", "mountGenerated(") {
		t.Error("SECURITY: [generate-rootread] missingCallSite read through a symlinked file out of writeRoot")
	}
	if missingCallSite(writeRoot, "linked/main.go", "mountGenerated(") {
		t.Error("SECURITY: [generate-rootread] missingCallSite read through a symlinked directory out of writeRoot")
	}

	// Siblings of the same invariant: the --force edited-target compare
	// and the retired-file cleaner must not read through the symlinks.
	if edited := editedTargets([]generatedFile{{name: "main.go", content: "package main"}}, writeRoot, writeRoot); len(edited) != 0 {
		t.Errorf("SECURITY: [generate-rootread] editedTargets read through a symlinked file out of writeRoot: %v", edited)
	}
	retiredOutside := filepath.Join(outside, "retired.go")
	if err := os.WriteFile(retiredOutside, []byte("Code generated by gofastr. DO NOT EDIT."), 0o644); err != nil {
		t.Fatal(err)
	}
	retired := filepath.Join(writeRoot, "resource_test.go")
	if err := os.Symlink(retiredOutside, retired); err != nil {
		t.Fatal(err)
	}
	if err := removeRetiredBlueprintFiles(writeRoot); err == nil {
		if _, lerr := os.Lstat(retired); lerr != nil {
			t.Error("SECURITY: [generate-rootread] removeRetiredBlueprintFiles acted on a symlinked file out of writeRoot")
		}
	}
	if missingCallSite(writeRoot, "real.go", "entities.RegisterAll(") {
		t.Error("control: missingCallSite says real.go lacks the call it contains")
	}
	if !missingCallSite(writeRoot, "real.go", "mountGenerated(") {
		t.Error("control: missingCallSite says real.go contains a call it does not")
	}
}
