package ownstyle

import (
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"go/format"
	"go/token"
	"reflect"
	"strings"
)

// The generated-file header. `gofastr gen styles` writes these two
// lines first; GOFASTR1814 (gofastr verify) finds the hash line and
// compares it against the CSS bytes, so the spellings here are the one
// contract between the generator and the check. They are exported so
// cmd/gofastr and framework/contracts never re-type them.
const (
	// GeneratedByHeader is the conventional generated-code marker
	// naming the CSS file this Go was generated from.
	GeneratedByHeader = `// Code generated by "gofastr gen styles" from `
	// SourceHashHeader prefixes the sha256 of the CSS bytes.
	SourceHashHeader = `// Source hash: sha256:`
)

// StyleFileName returns the CSS file name of an owner: "issuecard" →
// "issuecard.style.css".
func StyleFileName(name string) string { return name + ".style.css" }

// GeneratedFileName returns the Go file name gen styles writes for an
// owner: "issuecard" → "issuecard_style.gen.go". GOFASTR1814 looks for
// exactly this sibling.
func GeneratedFileName(name string) string { return name + "_style.gen.go" }

// SourceHash is the sha256 of the CSS bytes, hex-encoded: the value in
// the generated file's Source hash line and the value GOFASTR1814
// recomputes from the live CSS.
func SourceHash(css string) string {
	sum := sha256.Sum256([]byte(css))
	return hex.EncodeToString(sum[:])
}

// GenerateFile renders the Go source for one owned style: the checked
// CSS embedded as a constant, the registration (a handle wrapping
// ownstyle.Must), and the class vocabulary of m as typed methods.
//
// name is the owner name ("issuecard", "app"); kind its Kind; css the
// exact bytes of <name>.style.css (the hash is computed from it); pkg
// the Go package of the directory the CSS sits in; sharedPkg is true
// when that package holds more than one style file, in which case the
// exported var is <Owner>Style instead of Style.
//
// Every Go identifier is derived (kebab → Camel) and then VALIDATED,
// not trusted: an identifier that is invalid Go, collides with another
// identifier the file declares, or shadows the embedded Sheet's
// methods (Name, Kind, Scope) is an error, never a mangled name.
//
// The output is deterministic: the same CSS bytes, owner name and
// model produce the same bytes (the model's slices are already in
// first-appearance order; nothing here iterates a map).
func GenerateFile(name string, kind Kind, css string, m *SheetModel, pkg string, sharedPkg bool) (string, error) {
	g := &fileGen{
		name:      name,
		kind:      kind,
		css:       css,
		model:     m,
		pkg:       pkg,
		sharedPkg: sharedPkg,
		decls:     map[string]string{},
		methods:   map[string]string{},
	}
	if err := g.declareIdentifiers(); err != nil {
		return "", err
	}
	src := g.render()
	formatted, ferr := format.Source([]byte(src))
	if ferr != nil {
		// The emitter produced something gofmt refuses: a bug in this
		// file, not in the user's CSS. Fail loudly rather than ship it.
		return "", fmt.Errorf("ownstyle: generate %s: emitted Go does not format: %w", StyleFileName(name), ferr)
	}
	return string(formatted), nil
}

// fileGen carries one generated file's naming decisions.
type fileGen struct {
	name      string
	kind      Kind
	css       string
	model     *SheetModel
	pkg       string
	sharedPkg bool

	// handle is the unexported handle type ("issuecardStyle"), varName
	// the exported var ("Style" or "IssuecardStyle"), cssConst the
	// embedded CSS constant's name.
	handle   string
	varName  string
	cssConst string

	// decls maps every package-scope identifier the file declares to a
	// human name of its source, for collision messages; methods does
	// the same for the handle's method set.
	decls   map[string]string
	methods map[string]string
	withAny bool // any <Base>With method (gates the strings import)
}

// declareIdentifiers derives and validates every identifier the file
// will declare — package scope, the handle's method set, and each
// Variants struct's fields — so collisions surface as errors before
// any code is written.
func (g *fileGen) declareIdentifiers() error {
	reserve := func(ident, source string) error {
		if !token.IsIdentifier(ident) {
			return fmt.Errorf("gofastr gen styles: %s: %q becomes the invalid Go identifier %q; rename it",
				StyleFileName(g.name), source, ident)
		}
		if prev, taken := g.decls[ident]; taken {
			return fmt.Errorf("gofastr gen styles: %s: %q and %q both become the Go identifier %q; rename one",
				StyleFileName(g.name), prev, source, ident)
		}
		g.decls[ident] = source
		return nil
	}

	owner := camelIdent(g.name)
	g.handle = owner + "Style"
	g.cssConst = owner + "CSS"
	if g.sharedPkg {
		g.varName = camelUpper(g.name) + "Style"
	} else {
		g.varName = "Style"
	}
	for _, id := range []struct{ ident, source string }{
		{g.handle, fmt.Sprintf("the handle type for owner %q", g.name)},
		{g.cssConst, fmt.Sprintf("the CSS constant for owner %q", g.name)},
		{g.varName, fmt.Sprintf("the exported style var for owner %q", g.name)},
	} {
		if err := reserve(id.ident, id.source); err != nil {
			return err
		}
	}

	// A class method may not shadow the embedded *ownstyle.Sheet's
	// exported methods: Style.Scope, Style.Name and Style.Kind are the
	// registration's public surface, OwnedSheet is the method
	// app.StyleSheet requires, and an outer method of the same name
	// would silently replace them. The names come from the method set,
	// so a method added to Sheet is reserved without a list to update.
	sheetType := reflect.TypeFor[*Sheet]()
	for i := range sheetType.NumMethod() {
		shadow := sheetType.Method(i).Name
		g.methods[shadow] = "the embedded *ownstyle.Sheet's " + shadow + " method"
	}
	// method reserves one method name on the handle.
	method := func(ident, source string) error {
		if !token.IsIdentifier(ident) {
			return fmt.Errorf("gofastr gen styles: %s: %q becomes the invalid Go identifier %q; rename it",
				StyleFileName(g.name), source, ident)
		}
		if prev, taken := g.methods[ident]; taken {
			return fmt.Errorf("gofastr gen styles: %s: %q and %q both become the method %s.%s; rename one",
				StyleFileName(g.name), prev, source, g.handle, ident)
		}
		g.methods[ident] = source
		return nil
	}
	// fields reserves one Variants struct's field names: a flag and a
	// group of one base can collapse onto the same field (".x.over"
	// and ".x.over--fast" both want Over).
	fields := func(base string, flags []FlagModel, groups []string) error {
		seen := map[string]string{}
		take := func(ident, source string) error {
			if !token.IsIdentifier(ident) {
				return fmt.Errorf("gofastr gen styles: %s: %q becomes the invalid Go identifier %q; rename it",
					StyleFileName(g.name), source, ident)
			}
			if prev, taken := seen[ident]; taken {
				return fmt.Errorf("gofastr gen styles: %s: variants %q and %q of %s both become the field %s; rename one",
					StyleFileName(g.name), prev, source, base, ident)
			}
			seen[ident] = source
			return nil
		}
		for _, f := range flags {
			if err := take(camelUpper(f.Name), fmt.Sprintf("the flag %q", f.Name)); err != nil {
				return err
			}
		}
		for _, name := range groups {
			if err := take(camelUpper(name), fmt.Sprintf("the group %q", name)); err != nil {
				return err
			}
		}
		return nil
	}

	if g.model.Root != nil {
		g.withAny = true
		if err := method("Root", `the ":scope" base`); err != nil {
			return err
		}
		if err := method("RootWith", `the ":scope" variant selector`); err != nil {
			return err
		}
		if err := reserve("RootVariants", `the ":scope" variant struct`); err != nil {
			return err
		}
		if err := fields(`":scope"`, g.model.Root.Flags, g.model.Root.Groups); err != nil {
			return err
		}
	}
	for _, grp := range g.model.Groups {
		typeName := camelUpper(grp.Name)
		if err := reserve(typeName, fmt.Sprintf("the group %q", grp.Name)); err != nil {
			return err
		}
		if err := reserve("Parse"+typeName, fmt.Sprintf("the parser for group %q", grp.Name)); err != nil {
			return err
		}
		for _, val := range grp.Values {
			if err := reserve(typeName+camelUpper(val.Value), fmt.Sprintf("the group value \".%s--%s\"", grp.Name, val.Value)); err != nil {
				return err
			}
		}
	}
	for _, cls := range g.model.Classes {
		if err := method(camelUpper(cls.Name), fmt.Sprintf("the class %q", cls.Name)); err != nil {
			return err
		}
		if len(cls.Flags) > 0 || len(cls.Groups) > 0 {
			g.withAny = true
			if err := method(camelUpper(cls.Name)+"With", fmt.Sprintf("the variant selector for class %q", cls.Name)); err != nil {
				return err
			}
			if err := reserve(camelUpper(cls.Name)+"Variants", fmt.Sprintf("the variant struct for class %q", cls.Name)); err != nil {
				return err
			}
			if err := fields(fmt.Sprintf("the class %q", cls.Name), cls.Flags, cls.Groups); err != nil {
				return err
			}
		}
	}
	return nil
}

// ident re-asserts the identifier gate at the emit site. Every name
// was validated in declareIdentifiers before render ran; this checks
// again where the declaration is actually written, so a name that
// ever bypasses the declare pass (a future emitter edit) cannot reach
// emitted code.
func (g *fileGen) ident(name string) string {
	if !token.IsIdentifier(name) {
		panic(fmt.Sprintf("ownstyle: gen styles %s: %q did not pass identifier validation", StyleFileName(g.name), name))
	}
	return name
}

// render writes the file. Every identifier was validated in
// declareIdentifiers; this only spells them.
func (g *fileGen) render() string {
	var b strings.Builder
	fmt.Fprintf(&b, "%s%s. DO NOT EDIT.\n", GeneratedByHeader, StyleFileName(g.name))
	fmt.Fprintf(&b, "%s%s\n\n", SourceHashHeader, SourceHash(g.css))
	fmt.Fprintf(&b, "package %s\n\n", g.pkg)

	if g.withAny {
		b.WriteString("import (\n\t\"strings\"\n\n\t\"github.com/DonaldMurillo/gofastr/core-ui/ownstyle\"\n)\n\n")

	} else {
		b.WriteString("import \"github.com/DonaldMurillo/gofastr/core-ui/ownstyle\"\n\n")
	}

	kindConst := "ownstyle.KindScoped"
	if g.kind == KindApp {
		kindConst = "ownstyle.KindApp"
	}

	fmt.Fprintf(&b, "// %s is the checked source of the %s owned style.\nconst %s = %s\n\n",
		g.ident(g.cssConst), g.name, g.ident(g.cssConst), goRawString(g.css))

	fmt.Fprintf(&b, "// %s carries the %s owned style: the registered sheet (Name, Kind and\n// Scope come from the embedded *ownstyle.Sheet) plus its class\n// vocabulary as methods returning local class names.\ntype %s struct {\n\t*ownstyle.Sheet\n}\n\n",
		g.ident(g.handle), g.name, g.ident(g.handle))

	fmt.Fprintf(&b, "// %s is the %s owned style, registered at init.\n", g.varName, g.name)
	if g.sharedPkg {
		b.WriteString("// This package holds more than one style file, so the handle is\n// exported as <Owner>Style; a package with exactly one exports it\n// as Style.\n")
	} else {
		b.WriteString("// This package holds exactly one style file, so the handle is\n// exported as Style; a package holding several exports each as\n// <Owner>Style.\n")
	}
	fmt.Fprintf(&b, "var %s = %s{ownstyle.Must(%q, %s, %s)}\n\n",
		g.ident(g.varName), g.ident(g.handle), g.name, kindConst, g.ident(g.cssConst))

	if g.model.Root != nil {
		g.renderRoot(&b)
	}
	for _, grp := range g.model.Groups {
		g.renderGroup(&b, grp)
	}
	for _, cls := range g.model.Classes {
		g.renderClass(&b, cls)
	}
	return b.String()
}

// renderRoot emits the :scope pseudo-base: Root, RootVariants and
// RootWith.
func (g *fileGen) renderRoot(b *strings.Builder) {
	r := g.model.Root
	writeDoc(b,
		"Root returns the :scope base class: the empty string. The scoped\nroot carries data-cui-scope, not a class; RootWith returns its\nvariants.",
		r.Doc)
	fmt.Fprintf(b, "func (s %s) Root() string { return \"\" }\n\n", g.handle)

	b.WriteString("// RootVariants selects the variants of the :scope root.\ntype RootVariants struct {\n")
	g.renderVariantFields(b, r.Flags, r.Groups)
	b.WriteString("}\n\n")

	writeDoc(b,
		"RootWith returns the :scope root's selected variant classes,\nspace-separated. There is no base class: the root is the scoped\nelement itself.",
		r.Doc)
	fmt.Fprintf(b, "func (s %s) RootWith(v RootVariants) string {\n\tvar classes []string\n", g.handle)
	g.renderWithBody(b, r.Flags, r.Groups)
	b.WriteString("}\n\n")
}

// renderGroup emits one group's string type, its value constants, and
// its Parse helper.
func (g *fileGen) renderGroup(b *strings.Builder, grp *GroupModel) {
	typeName := camelUpper(grp.Name)
	writeDoc(b,
		fmt.Sprintf("%s is one value of the %q variant group. The zero value\nselects none; the constants carry the full local class name.",
			typeName, grp.Name),
		grp.Doc)
	fmt.Fprintf(b, "type %s string\n\n", g.ident(typeName))

	fmt.Fprintf(b, "// %s values.\nconst (\n", typeName)
	for _, val := range grp.Values {
		constName := typeName + camelUpper(val.Value)
		writeDoc(b,
			fmt.Sprintf("%s is the %q value of %s: the local class %q.",
				constName, val.Value, typeName, grp.Name+"--"+val.Value),
			val.Doc, "\t")
		fmt.Fprintf(b, "\t%s %s = %q\n", constName, typeName, grp.Name+"--"+val.Value)
	}
	b.WriteString(")\n\n")

	fmt.Fprintf(b, "// Parse%s parses a %s VALUE (\"%s\"), not the class name, into its\n// constant. ok is false for any other string; the zero %s selects none.\nfunc Parse%s(s string) (%s, bool) {\n\tswitch s {\n",
		g.ident(typeName), grp.Name, grp.Values[0].Value, typeName, g.ident(typeName), typeName)
	for _, val := range grp.Values {
		fmt.Fprintf(b, "\tcase %q:\n\t\treturn %s, true\n", val.Value, typeName+camelUpper(val.Value))
	}
	b.WriteString("\t}\n\treturn \"\", false\n}\n\n")
}

// renderClass emits one class's method and, when it carries variants,
// its Variants struct and With method.
func (g *fileGen) renderClass(b *strings.Builder, cls *ClassModel) {
	methodName := camelUpper(cls.Name)
	writeDoc(b,
		fmt.Sprintf("%s returns the local class name %q.", methodName, cls.Name),
		cls.Doc)
	fmt.Fprintf(b, "func (s %s) %s() string { return %q }\n\n", g.handle, methodName, cls.Name)

	if len(cls.Flags) == 0 && len(cls.Groups) == 0 {
		return
	}
	variantsType := methodName + "Variants"
	fmt.Fprintf(b, "// %s selects the variants of the %s base class.\ntype %s struct {\n",
		g.ident(variantsType), cls.Name, g.ident(variantsType))
	g.renderVariantFields(b, cls.Flags, cls.Groups)
	b.WriteString("}\n\n")

	writeDoc(b,
		fmt.Sprintf("%sWith returns the %s base class plus the selected\nvariants, space-separated in declaration order.", methodName, cls.Name),
		cls.Doc)
	fmt.Fprintf(b, "func (s %s) %sWith(v %s) string {\n\tclasses := []string{s.%s()}\n",
		g.handle, methodName, variantsType, methodName)
	g.renderWithBody(b, cls.Flags, cls.Groups)
	b.WriteString("}\n\n")
}

// groupDoc returns the doc comment of a named group ("" when unknown),
// for the group-typed fields of Variants structs.
func (g *fileGen) groupDoc(name string) string {
	for _, grp := range g.model.Groups {
		if grp.Name == name {
			return grp.Doc
		}
	}
	return ""
}

// renderVariantFields emits a Variants struct's body: one bool field
// per flag, one group-typed field per group, each with its CSS doc
// comment. Every field name was validated in declareIdentifiers.
func (g *fileGen) renderVariantFields(b *strings.Builder, flags []FlagModel, groups []string) {
	for _, f := range flags {
		writeDoc(b,
			fmt.Sprintf("%s reports whether the %q flag class is set.", camelUpper(f.Name), f.Name),
			f.Doc, "\t")
		fmt.Fprintf(b, "\t%s bool\n", camelUpper(f.Name))
	}
	for _, name := range groups {
		writeDoc(b,
			fmt.Sprintf("%s selects one %q group value.", camelUpper(name), name),
			g.groupDoc(name), "\t")
		fmt.Fprintf(b, "\t%s %s\n", camelUpper(name), camelUpper(name))
	}
}

// renderWithBody emits the variant-append statements of a With method.
func (g *fileGen) renderWithBody(b *strings.Builder, flags []FlagModel, groups []string) {
	for _, f := range flags {
		fmt.Fprintf(b, "\tif v.%s {\n\t\tclasses = append(classes, %q)\n\t}\n", camelUpper(f.Name), f.Name)
	}
	for _, name := range groups {
		fmt.Fprintf(b, "\tif v.%s != \"\" {\n\t\tclasses = append(classes, string(v.%s))\n\t}\n", camelUpper(name), camelUpper(name))
	}
	b.WriteString("\treturn strings.Join(classes, \" \")\n")
}

// writeDoc writes a doc comment: the fixed sentence(s), then the CSS
// doc comment (when present) after a blank comment line. indent is
// prepended to each line (constants inside a const block use "\t").
func writeDoc(b *strings.Builder, fixed, cssDoc string, indent ...string) {
	pre := ""
	if len(indent) > 0 {
		pre = indent[0]
	}
	for _, line := range strings.Split(fixed, "\n") {
		fmt.Fprintf(b, "%s// %s\n", pre, strings.TrimRight(line, " "))
	}
	if cssDoc != "" {
		fmt.Fprintf(b, "%s//\n", pre)
		for _, line := range strings.Split(cssDoc, "\n") {
			fmt.Fprintf(b, "%s// %s\n", pre, strings.TrimRight(line, " "))
		}
	}
}

// camelUpper converts a kebab-case CSS name to an exported Go
// identifier segment: "over-limit" → "OverLimit". A name that becomes
// invalid Go ("2xl" → "2Xl") is an error at its use site; the
// transform itself never validates, validation is the discipline.
func camelUpper(s string) string { return camel(s, true) }

// camelIdent converts an owner name to its unexported identifier stem:
// "issue-card" → "issueCard".
func camelIdent(s string) string { return camel(s, false) }

// camel is the one kebab→Camel transform.
func camel(s string, export bool) string {
	var b strings.Builder
	up := export
	for _, r := range s {
		if r == '-' || r == '_' {
			up = true
			continue
		}
		if up {
			b.WriteRune(toUpperASCII(r))
			up = false
		} else {
			b.WriteRune(r)
		}
	}
	return b.String()
}

func toUpperASCII(r rune) rune {
	if r >= 'a' && r <= 'z' {
		return r - 'a' + 'A'
	}
	return r
}

// goRawString emits s as a Go raw string literal, splitting around any
// backtick and splicing it back as an interpreted literal: a + "`" + b.
func goRawString(s string) string {
	if !strings.Contains(s, "`") {
		return "`" + s + "`"
	}
	parts := strings.Split(s, "`")
	var b strings.Builder
	for i, p := range parts {
		if i > 0 {
			b.WriteString(" + \"`\" + ")
		}
		b.WriteString("`" + p + "`")
	}
	return b.String()
}
