// Code generated by gofastr. Owned — safe to edit.
package main

import (
	"context"
	"io"
	"net/http"
	"net/url"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"runtime"
	"strings"
	"testing"
	"time"

	"github.com/chromedp/chromedp"

	"github.com/DonaldMurillo/gofastr/framework/testkit/axetest"
)

// axeExtraPages lists concrete URLs the sitemap cannot discover —
// instances of dynamic routes ("/orders/42"). Owned: append entries as
// you add dynamic screens; they are scanned with the authenticated
// browser when one exists, so gated instances work too.
var axeExtraPages []string

// axeGatedPages are the access-gated static screen routes; they are
// scanned with an authenticated browser — an anonymous scan would
// only ever cover the login redirect, never the real screen.
var axeGatedPages = []string{}

// axeGatedPatterns are the access-gated DYNAMIC route patterns; any
// concrete sitemap page matching one (via StaticPaths expansion) is
// routed through the authenticated pass instead of bouncing.
var axeGatedPatterns = []string{}

// TestAxeEveryScreen is the runtime accessibility gate AND the strict-mode
// axe-coverage source: every page it scans is recorded into the
// axe-coverage manifest, which uihost.WithStrict checks on dev boot.
// Public pages come from /sitemap.xml, so a new static screen is picked
// up automatically on the next run; dynamic screens need StaticPaths
// (sitemap + strict demand) or an entry in axeExtraPages.
func TestAxeEveryScreen(t *testing.T) {
	// allow-skip: chromedp suite — boots the app + headless Chrome; runs in the full (non-short) pass.
	if testing.Short() {
		t.Skip("boots the app + headless Chrome")
	}
	dir := t.TempDir()
	bin := filepath.Join(dir, "app")
	if runtime.GOOS == "windows" {
		bin += ".exe"
	}
	build := exec.Command("go", "build", "-o", bin, ".")
	build.Stderr = os.Stderr
	if err := build.Run(); err != nil {
		t.Fatalf("build: %v", err)
	}
	addr := e2eFreeAddr(t)
	srv := exec.Command(bin)
	srv.Dir = dir
	srv.Env = append(os.Environ(), "PORT="+addr, "DATABASE_URL=file:"+filepath.Join(dir, "axe.db"))
	srv.Stdout, srv.Stderr = io.Discard, io.Discard
	if err := srv.Start(); err != nil {
		t.Fatalf("start: %v", err)
	}
	t.Cleanup(func() { _ = srv.Process.Kill(); _, _ = srv.Process.Wait() })
	base := "http://" + addr
	e2eWaitReady(t, base)

	gated := map[string]bool{}
	for _, p := range axeGatedPages {
		gated[p] = true
	}

	// Anonymous pass: every public (and guest-only) page. Pages that
	// are gated — directly or by matching a gated dynamic pattern —
	// are queued for the authenticated pass instead.
	var needsAuth []string
	anon := axetest.NewBrowser(t)
	for _, page := range axePagesFromSitemap(t, base) {
		if gated[page] || axeMatchesGatedPattern(page) {
			needsAuth = append(needsAuth, page)
			continue
		}
		for _, scheme := range axetest.Schemes {
			axeScanOne(t, anon, base, page, scheme)
		}
	}

	needsAuth = append(needsAuth, axeGatedPages...)
	if len(needsAuth) > 0 {
		t.Errorf("gated screens %v cannot be scanned: no seeded admin — set app.admin.seed_email/seed_password (or extend this test with your own login) so the gate can cover them; unscanned gated screens fail strict dev boot", needsAuth)
	}
	for _, page := range axeExtraPages {
		for _, scheme := range axetest.Schemes {
			axeScanOne(t, anon, base, page, scheme)
		}
	}
}

// axeMatchesGatedPattern reports whether a concrete page path matches
// one of the gated dynamic route patterns (segment-wise; ":" and "{"
// segments are wildcards).
func axeMatchesGatedPattern(page string) bool {
	for _, pattern := range axeGatedPatterns {
		ps := strings.Split(pattern, "/")
		gs := strings.Split(page, "/")
		if len(ps) != len(gs) {
			continue
		}
		match := true
		for i := range ps {
			if strings.HasPrefix(ps[i], ":") || strings.HasPrefix(ps[i], "{") {
				continue
			}
			if ps[i] != gs[i] {
				match = false
				break
			}
		}
		if match {
			return true
		}
	}
	return false
}

func axeScanOne(t *testing.T, browser context.Context, base, page, scheme string) {
	t.Helper()
	tab, done := axetest.NewTab(t, browser)
	defer done()
	var loc string
	if err := chromedp.Run(tab,
		chromedp.Navigate(base+page),
		chromedp.Sleep(400*time.Millisecond), // hydration settle
		chromedp.Location(&loc),
	); err != nil {
		t.Fatalf("navigate %s (%s): %v", page, scheme, err)
	}
	// A redirect means axe would audit — and the coverage manifest would
	// record — a DIFFERENT screen. Fail loudly instead of silently
	// covering the wrong page: the page either needs the authenticated
	// pass (axeGatedPages / axeGatedPatterns) or the route changed.
	if u, err := url.Parse(loc); err != nil || u.Path != page {
		t.Errorf("%s redirected to %s — page not scanned", page, loc)
		return
	}
	if err := chromedp.Run(tab, axetest.Prepare(scheme)); err != nil {
		t.Fatalf("prepare %s (%s): %v", page, scheme, err)
	}
	violations, err := axetest.Scan(tab, scheme, nil)
	if err != nil {
		t.Fatalf("axe scan %s (%s): %v", page, scheme, err)
	}
	for _, v := range violations {
		t.Errorf("%s (%s scheme): [%s] %s — %s (%s)", page, scheme, v.Impact, v.ID, v.Help, v.HelpURL)
	}
}

// axePagesFromSitemap derives the public scan list from the app's own
// sitemap — the same registry the router serves — so a new static
// screen can never drift out of the gate.
func axePagesFromSitemap(t *testing.T, base string) []string {
	t.Helper()
	resp, err := http.Get(base + "/sitemap.xml")
	if err != nil {
		t.Fatalf("sitemap: %v", err)
	}
	defer resp.Body.Close()
	body, err := io.ReadAll(io.LimitReader(resp.Body, 4<<20))
	if err != nil {
		t.Fatalf("sitemap read: %v", err)
	}
	locs := regexp.MustCompile(`<loc>([^<]+)</loc>`).FindAllStringSubmatch(string(body), -1)
	var pages []string
	seen := map[string]bool{}
	for _, m := range locs {
		u, err := url.Parse(strings.TrimSpace(m[1]))
		if err != nil {
			continue
		}
		p := u.Path
		if p == "" {
			p = "/"
		}
		if !seen[p] {
			seen[p] = true
			pages = append(pages, p)
		}
	}
	if len(pages) == 0 {
		t.Fatal("sitemap listed no pages — is uihost.WithSitemap configured?")
	}
	return pages
}
