// Code generated by gofastr. Owned: safe to edit.
package main

import (
	"io"
	"net"
	"net/http"
	"os"
	"os/exec"
	"path/filepath"
	"runtime"
	"strings"
	"testing"
	"time"

	"github.com/DonaldMurillo/gofastr/core/dotenv"
	"github.com/DonaldMurillo/gofastr/framework"
)

func TestE2E(t *testing.T) {
	if testing.Short() {
		t.Skip("builds + boots the binary")
	}
	// The seeded admin's password lives in the generated .env, not in
	// committed source. Load it before the server child inherits the
	// environment: the app refuses to boot on a fresh database when
	// ADMIN_SEED_PASSWORD is missing, whether or not this test logs in.
	_ = dotenv.LoadAndApply(framework.DefaultDotEnvPaths()...)
	if os.Getenv("ADMIN_SEED_PASSWORD") == "" {
		t.Setenv("ADMIN_SEED_PASSWORD", "e2e-seed-admin-pw")
	}
	dir := t.TempDir()
	bin := filepath.Join(dir, "app")
	if runtime.GOOS == "windows" {
		bin += ".exe"
	}
	build := exec.Command("go", "build", "-o", bin, ".")
	build.Stderr = os.Stderr
	if err := build.Run(); err != nil {
		t.Fatalf("build: %v", err)
	}
	addr := e2eFreeAddr(t)
	srv := exec.Command(bin)
	srv.Dir = dir
	srv.Env = append(os.Environ(), "PORT="+addr, "GOFASTR_SEMANTIC_COVERAGE=1", "DATABASE_URL=file:"+filepath.Join(dir, "e2e.db"))
	srv.Stdout, srv.Stderr = io.Discard, io.Discard
	if err := srv.Start(); err != nil {
		t.Fatalf("start: %v", err)
	}
	t.Cleanup(func() { _ = srv.Process.Kill(); _, _ = srv.Process.Wait() })
	base := "http://" + addr
	e2eWaitReady(t, base)

	if code, body := e2eDo(t, http.DefaultClient, "GET", base+"/", ""); code != http.StatusOK || !strings.Contains(body, "ShopFront") {
		t.Errorf("home page = %d, missing brand? %v", code, !strings.Contains(body, "ShopFront"))
	}

	// Public screens render for anonymous visitors.
	for _, p := range []string{"/", "/products", "/categories", "/orders", "/reviews", "/new-product"} {
		if code, body := e2eDo(t, http.DefaultClient, "GET", base+p, ""); code != http.StatusOK {
			t.Errorf("public screen %s = %d, want 200", p, code)
		} else if len(body) < 120 {
			t.Errorf("public screen %s body suspiciously short (%d bytes)", p, len(body))
		}
	}
}

func e2eFreeAddr(t *testing.T) string {
	t.Helper()
	l, err := net.Listen("tcp", "127.0.0.1:0")
	if err != nil {
		t.Fatal(err)
	}
	defer l.Close()
	return l.Addr().String()
}

func e2eWaitReady(t *testing.T, base string) {
	t.Helper()
	for range 100 {
		if r, err := http.Get(base + "/"); err == nil {
			r.Body.Close()
			return
		}
		time.Sleep(100 * time.Millisecond)
	}
	t.Fatal("server did not become ready")
}

// e2eDo runs one request and returns the status code + body. A non-empty
// body is sent as JSON. Network errors fail the test.
func e2eDo(t *testing.T, client *http.Client, method, u, body string) (int, string) {
	t.Helper()
	var rdr io.Reader
	if body != "" {
		rdr = strings.NewReader(body)
	}
	req, err := http.NewRequest(method, u, rdr)
	if err != nil {
		t.Fatalf("%s %s: %v", method, u, err)
	}
	if body != "" {
		req.Header.Set("Content-Type", "application/json")
	}
	r, err := client.Do(req)
	if err != nil {
		t.Fatalf("%s %s: %v", method, u, err)
	}
	defer r.Body.Close()
	bb, _ := io.ReadAll(r.Body)
	return r.StatusCode, string(bb)
}
