// Code generated by gofastr. Owned: safe to edit.
package main

import (
	"context"

	appui "github.com/DonaldMurillo/gofastr/core-ui/app"
	"github.com/DonaldMurillo/gofastr/core/render"
	"github.com/DonaldMurillo/gofastr/framework/ui/resource"
)

// appResources holds the app's resource configs. Per-entity generated files
// populate it without changing this owned seam, so generate --add stays
// additive.
var appResources = resource.Registry{}

// authError maps auth redirect codes to the alert rendered by generated auth
// screens. Edit this hook when the app needs different copy or extra codes.
func authError(ctx context.Context) render.HTML {
	switch appui.QueryFromContext(ctx).Get("error") {
	case "":
		return ""
	case "invalid_credentials":
		return render.Text("Invalid email or password.")
	case "credentials_required":
		return render.Text("Enter your email and password.")
	case "rate_limit":
		return render.Text("Too many attempts. Please wait a moment and try again.")
	case "email_taken", "user_exists", "duplicate":
		return render.Text("That email is already registered.")
	default:
		return render.Text("Sorry, something went wrong. Please try again.")
	}
}
