// Code generated by gofastr. Owned — safe to edit.
package main

import (
	"strings"
	"testing"
)

func TestResMoney(t *testing.T) {
	for in, want := range map[string]string{"1234.5": "$1,234.50", "99": "$99.00", "0": "$0.00", "1000000": "$1,000,000.00"} {
		if got := resMoney(in); got != want {
			t.Errorf("resMoney(%q) = %q, want %q", in, got, want)
		}
	}
}

func TestResTitle(t *testing.T) {
	if got := resTitle("past_due"); got != "Past Due" {
		t.Errorf("resTitle(past_due) = %q", got)
	}
}

func TestResCamel(t *testing.T) {
	if got := resCamel("generic_name"); got != "genericName" {
		t.Errorf("resCamel(generic_name) = %q", got)
	}
}

func TestResTruthy(t *testing.T) {
	if !resTruthy("true") || !resTruthy("1") || resTruthy("false") || resTruthy("") {
		t.Error("resTruthy mismatch")
	}
}

func TestResInputType(t *testing.T) {
	for in, want := range map[string]string{
		"decimal": "number", "int": "number", "date": "date",
		"timestamp": "datetime-local", "email": "email", "string": "text",
	} {
		if got := resInputType(in); got != want {
			t.Errorf("resInputType(%q) = %q, want %q", in, got, want)
		}
	}
}

func TestResDate(t *testing.T) {
	if got := resDate(nil, "2025-01-02", "Jan 2, 2006"); got != "Jan 2, 2025" {
		t.Errorf("resDate = %q, want Jan 2, 2025", got)
	}
}

func TestResFormatEnum(t *testing.T) {
	// enum cells render as a status badge containing the humanized value.
	h := resFormat(ResField{Key: "status", Type: "enum"}, "past_due", nil)
	if !strings.Contains(string(h), "Past Due") {
		t.Errorf("enum cell missing humanized label: %s", string(h))
	}
}
