package framework

import (
	"context"
	"database/sql"
	"encoding/json"
	"fmt"
	"net/http"
	"testing"

	"github.com/DonaldMurillo/gofastr/core/schema"
	"github.com/DonaldMurillo/gofastr/framework/crud"
	"github.com/DonaldMurillo/gofastr/framework/entity"
	"github.com/DonaldMurillo/gofastr/framework/event"
	"github.com/DonaldMurillo/gofastr/framework/hook"
	_ "github.com/mattn/go-sqlite3"
)

// setupTestDB returns a database for the given dialect. Uses the dual-dialect
// harness so each test fans out to both engines.
func setupTestDB(t *testing.T, dialect Dialect) *sql.DB {
	t.Helper()
	return openTestDB(t, dialect)
}

// createPostsTable creates the posts table on the given DB. DDL is portable:
// TEXT, TIMESTAMP, and CURRENT_TIMESTAMP are accepted by both engines (PG
// rejects the older DATETIME alias which was used before the dual-dialect
// migration).
func createPostsTable(t *testing.T, db *sql.DB) {
	t.Helper()
	_, err := db.Exec(`CREATE TABLE IF NOT EXISTS posts (
		id TEXT PRIMARY KEY,
		title TEXT NOT NULL,
		body TEXT DEFAULT '',
		status TEXT DEFAULT 'draft',
		author_id TEXT DEFAULT '',
		created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
		updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
	)`)
	if err != nil {
		t.Fatalf("create posts table: %v", err)
	}
}

// createCommentsTable creates the comments table on the given DB.
func createCommentsTable(t *testing.T, db *sql.DB) {
	t.Helper()
	_, err := db.Exec(`CREATE TABLE IF NOT EXISTS comments (
		id TEXT PRIMARY KEY,
		body TEXT NOT NULL,
		post_id TEXT NOT NULL,
		author_id TEXT DEFAULT '',
		created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
		updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
	)`)
	if err != nil {
		t.Fatalf("create comments table: %v", err)
	}
}

// seedPosts inserts test data and returns the IDs.
func seedPosts(t *testing.T, db *sql.DB, posts ...map[string]string) []string {
	t.Helper()
	var ids []string
	for i, p := range posts {
		id := p["id"]
		if id == "" {
			id = fmt.Sprintf("post-%d", i+1)
		}
		title := p["title"]
		body := p["body"]
		status := p["status"]
		if status == "" {
			status = "draft"
		}
		authorID := p["authorId"]
		_, err := db.Exec("INSERT INTO posts (id, title, body, status, author_id) VALUES ($1, $2, $3, $4, $5)",
			id, title, body, status, authorID)
		if err != nil {
			t.Fatalf("seed post %d: %v", i, err)
		}
		ids = append(ids, id)
	}
	return ids
}

// ============================================================================
// E2E: Full CRUD Round-Trip with Real Database
// ============================================================================

func TestE2E_CRUD_CreateAndGet(t *testing.T) {
	forEachDialect(t, func(t *testing.T, db *sql.DB, dialect Dialect) {
		createPostsTable(t, db)

		app := NewApp(WithDB(db))
		ent := entity.Define("posts", entity.EntityConfig{
			Table: "posts",
			Fields: []schema.Field{
				{Name: "title", Type: schema.String, Required: true},
				{Name: "body", Type: schema.Text},
				{Name: "status", Type: schema.String, Default: "draft"},
				{Name: "author_id", Type: schema.String},
			},
		})
		app.Registry.Register(ent)

		ch := crud.NewCrudHandler(ent, db)
		crud.RegisterCrudRoutes(app.Router(), ch, "/posts")

		ta := TestHarness(t, app)
		defer ta.Close()

		// CREATE a post (server auto-generates ID)
		resp := ta.Post("/posts", map[string]string{
			"title": "Hello World",
			"body":  "My first post",
		})
		resp.AssertStatus(t, http.StatusCreated)
		resp.AssertBodyContains(t, "Hello World")

		// Capture the auto-generated ID
		var createResult map[string]any
		if err := resp.JSON(&createResult); err != nil {
			t.Fatalf("decode create response: %v", err)
		}
		id := createResult["id"].(string)
		if id == "" {
			t.Fatalf("expected auto-generated ID, got empty")
		}

		// GET the same post back
		resp = ta.Get("/posts/" + id)
		resp.AssertStatus(t, http.StatusOK)
		resp.AssertBodyContains(t, "Hello World")

		var getResult map[string]any
		if err := resp.JSON(&getResult); err != nil {
			t.Fatalf("decode get response: %v", err)
		}
		if getResult["title"] != "Hello World" {
			t.Errorf("expected title=Hello World, got %v", getResult["title"])
		}

		// Verify data in database directly
		var title string
		err := db.QueryRow("SELECT title FROM posts WHERE id = $1", id).Scan(&title)
		if err != nil {
			t.Fatalf("direct DB query: %v", err)
		}
		if title != "Hello World" {
			t.Errorf("expected DB title=Hello World, got %s", title)
		}
	})
}

func TestE2E_CRUD_AutoGeneratedID(t *testing.T) {
	forEachDialect(t, func(t *testing.T, db *sql.DB, dialect Dialect) {
		createPostsTable(t, db)

		ent := entity.Define("posts", entity.EntityConfig{
			Table: "posts",
			Fields: []schema.Field{
				{Name: "title", Type: schema.String, Required: true},
				{Name: "body", Type: schema.Text},
			},
		})

		app := NewApp(WithDB(db))
		app.Registry.Register(ent)
		crud.RegisterCrudRoutes(app.Router(), crud.NewCrudHandler(ent, db), "/posts")

		ta := TestHarness(t, app)
		defer ta.Close()

		// Create WITHOUT sending an ID
		resp := ta.Post("/posts", map[string]string{
			"title": "Auto ID Post",
			"body":  "No ID sent",
		})
		resp.AssertStatus(t, http.StatusCreated)

		var created map[string]any
		if err := resp.JSON(&created); err != nil {
			t.Fatalf("decode: %v", err)
		}

		id, ok := created["id"].(string)
		if !ok || id == "" {
			t.Fatalf("expected auto-generated ID, got %v", created["id"])
		}
		if len(id) != 36 { // UUID format: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
			t.Errorf("expected UUID format, got %q (len=%d)", id, len(id))
		}

		// GET it back using the auto-generated ID
		resp = ta.Get("/posts/" + id)
		resp.AssertStatus(t, http.StatusOK)
		resp.AssertBodyContains(t, "Auto ID Post")

		// Verify in DB
		var title string
		err := db.QueryRow("SELECT title FROM posts WHERE id = $1", id).Scan(&title)
		if err != nil {
			t.Fatalf("DB query: %v", err)
		}
		assertEqual(t, "db title", "Auto ID Post", title)
	})
}

func TestE2E_CRUD_SnakeCase(t *testing.T) {
	forEachDialect(t, func(t *testing.T, db *sql.DB, dialect Dialect) {
		createPostsTable(t, db)

		ent := entity.Define("posts", entity.EntityConfig{
			Table: "posts",
			Fields: []schema.Field{
				{Name: "title", Type: schema.String, Required: true},
				{Name: "body", Type: schema.Text},
			},
		})

		app := NewApp(WithDB(db))
		app.Registry.Register(ent)

		ch := crud.NewCrudHandler(ent, db).WithJSONCase(crud.CaseSnake)
		crud.RegisterCrudRoutes(app.Router(), ch, "/posts")

		ta := TestHarness(t, app)
		defer ta.Close()

		// Create
		resp := ta.Post("/posts", map[string]string{
			"title": "Snake Case",
			"body":  "Keys stay snake_case",
		})
		resp.AssertStatus(t, http.StatusCreated)

		var created map[string]any
		if err := resp.JSON(&created); err != nil {
			t.Fatalf("decode: %v", err)
		}

		// Keys should be snake_case, not camelCase
		if _, ok := created["title"]; !ok {
			t.Errorf("expected snake_case key 'title', got keys: %v", mapKeys(created))
		}
		if _, ok := created["body"]; !ok {
			t.Errorf("expected snake_case key 'body', got keys: %v", mapKeys(created))
		}
		// Verify no camelCase keys leaked through
		if _, ok := created["createdAt"]; ok {
			t.Error("should NOT have camelCase key 'createdAt' in snake_case mode")
		}

		id := created["id"].(string)

		// GET
		resp = ta.Get("/posts/" + id)
		resp.AssertStatus(t, http.StatusOK)
		var fetched map[string]any
		if err := resp.JSON(&fetched); err != nil {
			t.Fatalf("decode get: %v", err)
		}
		if fetched["title"] != "Snake Case" {
			t.Error("GET response should have snake_case 'title' with correct value")
		}

		// List
		resp = ta.Get("/posts")
		resp.AssertStatus(t, http.StatusOK)

		// Update
		resp = ta.Put("/posts/"+id, map[string]string{"title": "Updated"})
		resp.AssertStatus(t, http.StatusOK)
		var updated map[string]any
		if err := resp.JSON(&updated); err != nil {
			t.Fatalf("decode update: %v", err)
		}
		if updated["title"] != "Updated" {
			t.Errorf("expected title=Updated, got %v", updated["title"])
		}
	})
}

func TestE2E_CRUD_List(t *testing.T) {
	forEachDialect(t, func(t *testing.T, db *sql.DB, dialect Dialect) {
		createPostsTable(t, db)

		// Seed 3 posts
		seedPosts(t, db,
			map[string]string{"id": "p1", "title": "Post One", "status": "published"},
			map[string]string{"id": "p2", "title": "Post Two", "status": "draft"},
			map[string]string{"id": "p3", "title": "Post Three", "status": "published"},
		)

		app := NewApp(WithDB(db))
		ent := entity.Define("posts", entity.EntityConfig{
			Table: "posts",
			Fields: []schema.Field{
				{Name: "title", Type: schema.String},
				{Name: "body", Type: schema.Text},
				{Name: "status", Type: schema.String},
				{Name: "author_id", Type: schema.String},
			},
		})
		app.Registry.Register(ent)

		ch := crud.NewCrudHandler(ent, db)
		crud.RegisterCrudRoutes(app.Router(), ch, "/posts")

		ta := TestHarness(t, app)
		defer ta.Close()

		// LIST all posts
		resp := ta.Get("/posts")
		resp.AssertStatus(t, http.StatusOK)
		resp.AssertBodyContains(t, "Post One")
		resp.AssertBodyContains(t, "Post Three")

		var listResult crud.ListResponse
		if err := resp.JSON(&listResult); err != nil {
			t.Fatalf("decode list response: %v", err)
		}
		if listResult.Total != 3 {
			t.Errorf("expected total=3, got %d", listResult.Total)
		}
		if len(listResult.Data) != 3 {
			t.Errorf("expected 3 data items, got %d", len(listResult.Data))
		}
	})
}

func TestE2E_CRUD_Update(t *testing.T) {
	forEachDialect(t, func(t *testing.T, db *sql.DB, dialect Dialect) {
		createPostsTable(t, db)

		seedPosts(t, db, map[string]string{"id": "p1", "title": "Original Title"})

		app := NewApp(WithDB(db))
		ent := entity.Define("posts", entity.EntityConfig{
			Table: "posts",
			Fields: []schema.Field{
				{Name: "title", Type: schema.String},
				{Name: "body", Type: schema.Text},
				{Name: "status", Type: schema.String},
				{Name: "author_id", Type: schema.String},
			},
		})
		app.Registry.Register(ent)

		ch := crud.NewCrudHandler(ent, db)
		crud.RegisterCrudRoutes(app.Router(), ch, "/posts")

		ta := TestHarness(t, app)
		defer ta.Close()

		// UPDATE
		resp := ta.Put("/posts/p1", map[string]string{
			"title": "Updated Title",
		})
		resp.AssertStatus(t, http.StatusOK)
		resp.AssertBodyContains(t, "Updated Title")

		// Verify in DB
		var title string
		err := db.QueryRow("SELECT title FROM posts WHERE id = $1", "p1").Scan(&title)
		if err != nil {
			t.Fatalf("DB query after update: %v", err)
		}
		if title != "Updated Title" {
			t.Errorf("expected updated title in DB, got %s", title)
		}
	})
}

func TestE2E_CRUD_Delete(t *testing.T) {
	forEachDialect(t, func(t *testing.T, db *sql.DB, dialect Dialect) {
		createPostsTable(t, db)

		seedPosts(t, db,
			map[string]string{"id": "p1", "title": "To Delete"},
			map[string]string{"id": "p2", "title": "To Keep"},
		)

		app := NewApp(WithDB(db))
		ent := entity.Define("posts", entity.EntityConfig{
			Table: "posts",
			Fields: []schema.Field{
				{Name: "title", Type: schema.String},
				{Name: "body", Type: schema.Text},
				{Name: "status", Type: schema.String},
				{Name: "author_id", Type: schema.String},
			},
		})
		app.Registry.Register(ent)

		ch := crud.NewCrudHandler(ent, db)
		crud.RegisterCrudRoutes(app.Router(), ch, "/posts")

		ta := TestHarness(t, app)
		defer ta.Close()

		// DELETE
		resp := ta.Delete("/posts/p1")
		resp.AssertStatus(t, http.StatusNoContent)

		// Verify p1 is gone from DB
		var count int
		err := db.QueryRow("SELECT COUNT(*) FROM posts WHERE id = $1", "p1").Scan(&count)
		if err != nil {
			t.Fatalf("DB count after delete: %v", err)
		}
		if count != 0 {
			t.Errorf("expected p1 to be deleted, but count=%d", count)
		}

		// Verify p2 still exists
		err = db.QueryRow("SELECT COUNT(*) FROM posts WHERE id = $1", "p2").Scan(&count)
		if err != nil {
			t.Fatalf("DB count for p2: %v", err)
		}
		if count != 1 {
			t.Errorf("expected p2 to still exist, but count=%d", count)
		}

		// GET deleted post → 404
		resp = ta.Get("/posts/p1")
		resp.AssertStatus(t, http.StatusNotFound)
	})
}

func TestE2E_CRUD_GetNotFound(t *testing.T) {
	forEachDialect(t, func(t *testing.T, db *sql.DB, dialect Dialect) {
		createPostsTable(t, db)

		app := NewApp(WithDB(db))
		ent := entity.Define("posts", entity.EntityConfig{
			Table: "posts",
			Fields: []schema.Field{
				{Name: "title", Type: schema.String},
				{Name: "body", Type: schema.Text},
				{Name: "status", Type: schema.String},
				{Name: "author_id", Type: schema.String},
			},
		})
		app.Registry.Register(ent)

		ch := crud.NewCrudHandler(ent, db)
		crud.RegisterCrudRoutes(app.Router(), ch, "/posts")

		ta := TestHarness(t, app)
		defer ta.Close()

		resp := ta.Get("/posts/nonexistent")
		resp.AssertStatus(t, http.StatusNotFound)
		resp.AssertBodyContains(t, "not found")
	})
}

// ============================================================================
// E2E: Validation
// ============================================================================

func TestE2E_Validation_CreateMissingRequired(t *testing.T) {
	forEachDialect(t, func(t *testing.T, db *sql.DB, dialect Dialect) {
		createPostsTable(t, db)

		app := NewApp(WithDB(db))
		ent := entity.Define("posts", entity.EntityConfig{
			Table: "posts",
			Fields: []schema.Field{
				{Name: "title", Type: schema.String, Required: true},
				{Name: "body", Type: schema.Text},
			},
		})
		app.Registry.Register(ent)

		ch := crud.NewCrudHandler(ent, db)
		crud.RegisterCrudRoutes(app.Router(), ch, "/posts")

		ta := TestHarness(t, app)
		defer ta.Close()

		// Missing required "title" field
		resp := ta.Post("/posts", map[string]string{
			"id": "post-1",
		})
		resp.AssertStatus(t, http.StatusBadRequest)
		resp.AssertBodyContains(t, "validation failed")
	})
}

// ============================================================================
// E2E: Hooks
// ============================================================================

func TestE2E_Hooks_BeforeCreate(t *testing.T) {
	forEachDialect(t, func(t *testing.T, db *sql.DB, dialect Dialect) {
		createPostsTable(t, db)

		app := NewApp(WithDB(db))
		ent := entity.Define("posts", entity.EntityConfig{
			Table: "posts",
			Fields: []schema.Field{
				{Name: "title", Type: schema.String, Required: true},
				{Name: "body", Type: schema.Text},
				{Name: "status", Type: schema.String},
				{Name: "author_id", Type: schema.String},
			},
		})
		app.Registry.Register(ent)

		// Register a before-create hook that records it was called
		hookCalled := false
		hooks := app.HookRegistry("posts")
		hooks.RegisterHook(hook.BeforeCreate, func(ctx context.Context, data any) error {
			hookCalled = true
			return nil
		})

		ch := crud.NewCrudHandler(ent, db)
		crud.RegisterCrudRoutes(app.Router(), ch, "/posts")

		ta := TestHarness(t, app)
		defer ta.Close()

		// Note: CrudHandler.Create doesn't call hooks directly —
		// hooks are called when using the App's entity operations.
		// For this E2E test, we verify the hook registry works
		err := hooks.ExecuteHooks(context.Background(), hook.BeforeCreate, map[string]any{"title": "test"})
		if err != nil {
			t.Fatalf("execute hooks: %v", err)
		}
		if !hookCalled {
			t.Error("expected before-create hook to be called")
		}
	})
}

// ============================================================================
// E2E: Events
// ============================================================================

func TestE2E_Events_EntityCreated(t *testing.T) {
	forEachDialect(t, func(t *testing.T, db *sql.DB, dialect Dialect) {

		app := NewApp(WithDB(db))

		var capturedEvent event.Event
		app.Events().On(event.EntityCreated, func(ctx context.Context, event event.Event) error {
			capturedEvent = event
			return nil
		})

		err := app.Events().Emit(context.Background(), event.Event{
			Type: event.EntityCreated,
			Data: map[string]any{"entity": "posts", "id": "p1"},
		})
		if err != nil {
			t.Fatalf("emit event: %v", err)
		}

		if capturedEvent.Type != event.EntityCreated {
			t.Errorf("expected event type %v, got %v", event.EntityCreated, capturedEvent.Type)
		}
		data, ok := capturedEvent.Data.(map[string]any)
		if !ok {
			t.Fatalf("expected map data, got %T", capturedEvent.Data)
		}
		if data["id"] != "p1" {
			t.Errorf("expected id=p1, got %v", data["id"])
		}
	})
}

// ============================================================================
// E2E: Plugin System
// ============================================================================

func TestE2E_Plugin_RegisterAndInit(t *testing.T) {
	app := NewApp()

	var initOrder []string
	p1 := &trackingPlugin{name: "alpha", order: &initOrder}
	p2 := &trackingPlugin{name: "beta", order: &initOrder}

	app.RegisterPlugin(p1)
	app.RegisterPlugin(p2)

	if err := app.InitPlugins(); err != nil {
		t.Fatalf("InitPlugins: %v", err)
	}

	if len(initOrder) != 2 {
		t.Fatalf("expected 2 inits, got %d", len(initOrder))
	}
	if initOrder[0] != "alpha" || initOrder[1] != "beta" {
		t.Errorf("expected [alpha beta], got %v", initOrder)
	}
}

func TestE2E_Plugin_HasRoutes(t *testing.T) {
	app := NewApp()
	p := &routePlugin{name: "stats"}
	app.RegisterPlugin(p)

	if err := app.InitPlugins(); err != nil {
		t.Fatalf("InitPlugins: %v", err)
	}

	ta := TestHarness(t, app)
	defer ta.Close()

	resp := ta.Get("/stats/health")
	resp.AssertStatus(t, http.StatusOK)
	resp.AssertBodyContains(t, "ok")
}

// ============================================================================
// E2E: Multiple Entities with Relationships
// ============================================================================

func TestE2E_MultipleEntities(t *testing.T) {
	forEachDialect(t, func(t *testing.T, db *sql.DB, dialect Dialect) {
		createPostsTable(t, db)
		createCommentsTable(t, db)

		app := NewApp(WithDB(db))

		// Posts entity
		postsEntity := entity.Define("posts", entity.EntityConfig{
			Table: "posts",
			Fields: []schema.Field{
				{Name: "title", Type: schema.String, Required: true},
				{Name: "body", Type: schema.Text},
				{Name: "status", Type: schema.String},
				{Name: "author_id", Type: schema.String},
			},
		})
		app.Registry.Register(postsEntity)

		// Comments entity
		commentsEntity := entity.Define("comments", entity.EntityConfig{
			Table: "comments",
			Fields: []schema.Field{
				{Name: "body", Type: schema.String, Required: true},
				{Name: "post_id", Type: schema.String, Required: true},
				{Name: "author_id", Type: schema.String},
			},
		})
		app.Registry.Register(commentsEntity)

		postsCrud := crud.NewCrudHandler(postsEntity, db)
		commentsCrud := crud.NewCrudHandler(commentsEntity, db)
		crud.RegisterCrudRoutes(app.Router(), postsCrud, "/posts")
		crud.RegisterCrudRoutes(app.Router(), commentsCrud, "/comments")

		ta := TestHarness(t, app)
		defer ta.Close()

		// Create a post
		resp := ta.Post("/posts", map[string]string{
			"id":    "p1",
			"title": "My Post",
			"body":  "Content here",
		})
		resp.AssertStatus(t, http.StatusCreated)

		// Create a comment on that post
		resp = ta.Post("/comments", map[string]string{
			"id":     "c1",
			"body":   "Great post!",
			"postId": "p1",
		})
		resp.AssertStatus(t, http.StatusCreated)

		// List comments
		resp = ta.Get("/comments")
		resp.AssertStatus(t, http.StatusOK)
		resp.AssertBodyContains(t, "Great post!")

		// Verify DB state
		var postCount, commentCount int
		db.QueryRow("SELECT COUNT(*) FROM posts").Scan(&postCount)
		db.QueryRow("SELECT COUNT(*) FROM comments").Scan(&commentCount)
		if postCount != 1 {
			t.Errorf("expected 1 post, got %d", postCount)
		}
		if commentCount != 1 {
			t.Errorf("expected 1 comment, got %d", commentCount)
		}
	})
}

// ============================================================================
// E2E: Middleware Chain
// ============================================================================

func TestE2E_MiddlewareChain(t *testing.T) {
	forEachDialect(t, func(t *testing.T, db *sql.DB, dialect Dialect) {
		createPostsTable(t, db)

		app := NewApp(WithDB(db))

		var order []string
		app.Router().Use(func(next http.Handler) http.Handler {
			return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
				order = append(order, "mw1-in")
				next.ServeHTTP(w, r)
				order = append(order, "mw1-out")
			})
		})
		app.Router().Use(func(next http.Handler) http.Handler {
			return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
				order = append(order, "mw2-in")
				next.ServeHTTP(w, r)
				order = append(order, "mw2-out")
			})
		})

		ent := entity.Define("posts", entity.EntityConfig{
			Table: "posts",
			Fields: []schema.Field{
				{Name: "title", Type: schema.String, Required: true},
				{Name: "body", Type: schema.Text},
				{Name: "status", Type: schema.String},
				{Name: "author_id", Type: schema.String},
			},
		})
		app.Registry.Register(ent)

		ch := crud.NewCrudHandler(ent, db)
		crud.RegisterCrudRoutes(app.Router(), ch, "/posts")

		ta := TestHarness(t, app)
		defer ta.Close()

		// The test harness sends through the real router, so middleware fires
		resp := ta.Post("/posts", map[string]string{
			"id":    "p1",
			"title": "Middleware Test",
		})
		resp.AssertStatus(t, http.StatusCreated)

		// Verify middleware executed in order
		expected := []string{"mw1-in", "mw2-in", "mw2-out", "mw1-out"}
		if len(order) != len(expected) {
			t.Fatalf("expected middleware order %v, got %v", expected, order)
		}
		for i, v := range expected {
			if order[i] != v {
				t.Errorf("middleware[%d]: expected %q, got %q", i, v, order[i])
			}
		}
	})
}

// ============================================================================
// E2E: Soft Delete
// ============================================================================

func TestE2E_SoftDelete(t *testing.T) {
	forEachDialect(t, func(t *testing.T, db *sql.DB, dialect Dialect) {

		// Create table with deleted_at column
		_, err := db.Exec(`CREATE TABLE posts (
			id TEXT PRIMARY KEY,
			title TEXT NOT NULL,
			body TEXT DEFAULT '',
			status TEXT DEFAULT 'draft',
			author_id TEXT DEFAULT '',
			deleted_at TIMESTAMP DEFAULT NULL,
			created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
			updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
		)`)
		if err != nil {
			t.Fatalf("create table: %v", err)
		}

		app := NewApp(WithDB(db))
		ent := entity.Define("posts", entity.EntityConfig{
			Table:      "posts",
			SoftDelete: true,
			Fields: []schema.Field{
				{Name: "title", Type: schema.String, Required: true},
				{Name: "body", Type: schema.Text},
				{Name: "status", Type: schema.String},
				{Name: "author_id", Type: schema.String},
			},
		})
		app.Registry.Register(ent)

		ch := crud.NewCrudHandler(ent, db)
		crud.RegisterCrudRoutes(app.Router(), ch, "/posts")

		ta := TestHarness(t, app)
		defer ta.Close()

		// Create a post (server generates ID)
		resp := ta.Post("/posts", map[string]string{
			"title": "Soft Delete Me",
		})
		resp.AssertStatus(t, http.StatusCreated)

		var created map[string]any
		if err := resp.JSON(&created); err != nil {
			t.Fatalf("decode: %v", err)
		}
		id := created["id"].(string)

		// Soft delete
		resp = ta.Delete("/posts/" + id)
		resp.AssertStatus(t, http.StatusNoContent)

		// Verify deleted_at is set in DB
		var deletedAt sql.NullString
		err = db.QueryRow("SELECT deleted_at FROM posts WHERE id = $1", id).Scan(&deletedAt)
		if err != nil {
			t.Fatalf("query deleted_at: %v", err)
		}
		if !deletedAt.Valid {
			t.Error("expected deleted_at to be set, but it's NULL")
		}

		// Row still exists
		var count int
		db.QueryRow("SELECT COUNT(*) FROM posts WHERE id = $1", id).Scan(&count)
		if count != 1 {
			t.Errorf("expected soft-deleted row to still exist, count=%d", count)
		}
	})
}

// ============================================================================
// E2E: Custom Endpoints
// ============================================================================

func TestE2E_CustomEndpoint(t *testing.T) {
	app := NewApp()

	// Custom endpoint
	app.Router().Get("/health", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", "application/json")
		json.NewEncoder(w).Encode(map[string]string{"status": "healthy"})
	}))

	ta := TestHarness(t, app)
	defer ta.Close()

	resp := ta.Get("/health")
	resp.AssertStatus(t, http.StatusOK)
	resp.AssertJSON(t, map[string]string{"status": "healthy"})
}

// ============================================================================
// Test Helpers: Plugin implementations
// ============================================================================

type trackingPlugin struct {
	name  string
	order *[]string
}

func (p *trackingPlugin) Name() string        { return p.name }
func (p *trackingPlugin) Init(app *App) error { *p.order = append(*p.order, p.name); return nil }

type routePlugin struct {
	name string
}

func (p *routePlugin) Name() string { return p.name }
func (p *routePlugin) Init(app *App) error {
	app.Router().Get("/stats/health", http.HandlerFunc(func(w http.ResponseWriter, req *http.Request) {
		w.Header().Set("Content-Type", "application/json")
		json.NewEncoder(w).Encode(map[string]string{"status": "ok"})
	}))
	return nil
}

// ============================================================================
// Debug endpoint opt-in tests
// ============================================================================

func TestDebugEndpoints_DisabledByDefault(t *testing.T) {
	app := NewApp()
	ta := TestHarness(t, app)

	resp := ta.Get("/.debug/stats")
	if resp.Status() != http.StatusNotFound {
		t.Errorf("expected 404 when DebugEndpoints not enabled, got %d; body: %s", resp.Status(), resp.Body())
	}
}

func TestDebugEndpoints_EnabledViaConfig(t *testing.T) {
	app := NewApp(WithConfig(AppConfig{
		DebugEndpoints: true,
	}))
	app.registerDebugEndpoints()
	ta := TestHarness(t, app)

	resp := ta.Get("/.debug/stats")
	if resp.Status() != http.StatusOK {
		t.Fatalf("expected 200 when DebugEndpoints enabled, got %d; body: %s", resp.Status(), resp.Body())
	}

	var body map[string]any
	if err := resp.JSON(&body); err != nil {
		t.Fatalf("parse response: %v", err)
	}
	if _, ok := body["goroutines"]; !ok {
		t.Error("expected goroutines field in debug stats")
	}
	if _, ok := body["memory"]; !ok {
		t.Error("expected memory field in debug stats")
	}
}
