package framework

import (
	"bytes"
	"context"
	"fmt"
	"net/http"
	"path/filepath"
	"strings"
	"time"

	"github.com/gofastr/gofastr/core/upload"
)

// FileField holds metadata about an uploaded file associated with an entity field.
type FileField struct {
	// URL is the publicly accessible path or URL to the file.
	URL string `json:"url"`

	// Filename is the original filename as provided by the client.
	Filename string `json:"filename"`

	// MimeType is the detected MIME type of the file.
	MimeType string `json:"mime_type"`

	// Size is the file size in bytes.
	Size int64 `json:"size"`

	// StorageRef is the storage backend key used to reference this file.
	StorageRef string `json:"storage_ref"`
}

// ProcessFileField reads a file from the given reader, saves it via the storage
// backend, and returns a FileField with all metadata. The file is stored at a
// path generated by GenerateFilePath.
func ProcessFileField(store upload.Storage, file interface {
	Read([]byte) (int, error)
}, filename string, entityName, fieldName string) (*FileField, error) {
	if store == nil {
		return nil, fmt.Errorf("filefield: storage backend is required")
	}

	// Read entire file into buffer to compute size and detect MIME type
	var buf bytes.Buffer
	size, err := buf.ReadFrom(file)
	if err != nil {
		return nil, fmt.Errorf("filefield: reading file: %w", err)
	}

	data := buf.Bytes()

	// Detect MIME type from content
	mimeType := http.DetectContentType(data)
	if mimeType == "application/octet-stream" {
		// Try to detect from filename extension
		if detected := detectMIMEFromName(filename); detected != "" {
			mimeType = detected
		}
	}

	// Generate a safe, unique storage path
	path := GenerateFilePath(entityName, fieldName, filename)

	// Save to storage backend
	ctx := context.Background()
	if err := store.Save(ctx, path, bytes.NewReader(data)); err != nil {
		return nil, fmt.Errorf("filefield: saving file: %w", err)
	}

	return &FileField{
		URL:        path,
		Filename:   filepath.Base(filename),
		MimeType:   mimeType,
		Size:       size,
		StorageRef: path,
	}, nil
}

// DeleteFileField removes a previously stored file from the storage backend.
// Returns nil if the FileField is nil or has no storage reference.
func DeleteFileField(store upload.Storage, ff *FileField) error {
	if store == nil {
		return fmt.Errorf("filefield: storage backend is required")
	}
	if ff == nil || ff.StorageRef == "" {
		return nil
	}
	ctx := context.Background()
	return store.Delete(ctx, ff.StorageRef)
}

// GenerateFilePath produces a safe, unique file path for storage.
// The format is: uploads/{entityName}/{fieldName}/{sanitized_name}_{timestamp}{ext}
// Example: "uploads/posts/avatar/photo_1683398400000000000.png"
func GenerateFilePath(entityName, fieldName, filename string) string {
	// Sanitize the filename to prevent path traversal
	safe := upload.SanitizeFilename(filename)

	// Split into name and extension
	ext := filepath.Ext(safe)
	nameWithoutExt := strings.TrimSuffix(safe, ext)

	// Generate a unique name using nanosecond timestamp
	uniqueName := fmt.Sprintf("%s_%d%s", nameWithoutExt, time.Now().UnixNano(), ext)

	// Build the path using filepath.Join for cross-platform safety
	path := filepath.Join("uploads", entityName, fieldName, uniqueName)

	// Normalize to forward slashes for storage consistency
	return filepath.ToSlash(path)
}

// detectMIMEFromName attempts to detect MIME type from filename extension.
func detectMIMEFromName(filename string) string {
	ext := strings.ToLower(filepath.Ext(filename))
	mimeMap := map[string]string{
		".jpg":  "image/jpeg",
		".jpeg": "image/jpeg",
		".png":  "image/png",
		".gif":  "image/gif",
		".webp": "image/webp",
		".svg":  "image/svg+xml",
		".pdf":  "application/pdf",
		".txt":  "text/plain",
		".csv":  "text/csv",
		".json": "application/json",
		".xml":  "application/xml",
		".zip":  "application/zip",
	}
	if m, ok := mimeMap[ext]; ok {
		return m
	}
	return ""
}
