// Code generated by "gofastr gen styles" from appbar.tokens.css. DO NOT EDIT.
// Source hash: sha256:ae68500378cc8e18c3491d01a7b01cf05bbd904152eba6ffa2fcc7de58c94602

package appbar

import "github.com/DonaldMurillo/gofastr/core-ui/style"

// Tokens is appbar.tokens.css as typed theme tokens. Add them to the theme with
// Extend, which also takes the file's dark values:
//
//	site.WithTheme(theme.Default().Extend(appbar.Tokens))
var Tokens = appbarTokens{
	Sizes: appbarSizes{
		AppbarSearch:    style.Size{Name: "appbar-search", Value: "26rem"},
		AppbarSearchMin: style.Size{Name: "appbar-search-min", Value: "20rem"},
	},
}

// appbarTokens is the token set of appbar.tokens.css, grouped like style.Theme.
type appbarTokens struct {
	Sizes appbarSizes
}

// appbarSizes are the style.Size tokens of appbar.tokens.css.
type appbarSizes struct {
	// AppbarSearch is --size-appbar-search. The desktop search field's resting width, and the narrowest it
	// shrinks to before the bar runs out of room.
	AppbarSearch style.Size

	// AppbarSearchMin is --size-appbar-search-min.
	AppbarSearchMin style.Size
}
