// Code generated by "gofastr gen styles" from docsite-header.tokens.css. DO NOT EDIT.
// Source hash: sha256:e64f18c47f8d0ba5fc496dc8ff1f504d19b3c2250b7d1981aa3962095804b796

package siteheader

import "github.com/DonaldMurillo/gofastr/core-ui/style"

// Tokens is docsite-header.tokens.css as typed theme tokens. Add them to the theme with
// Extend, which also takes the file's dark values:
//
//	site.WithTheme(theme.Default().Extend(siteheader.Tokens))
var Tokens = docsiteHeaderTokens{
	Colors: docsiteHeaderColors{
		LineFaint: style.Color{Name: "line-faint", Value: "oklch(0.92 0.005 75)"},
	},
	Typography: docsiteHeaderTypography{
		Micro: style.FontSize{Name: "micro", Value: "11px"},
		Ui:    style.FontSize{Name: "ui", Value: "13px"},
		UiLg:  style.FontSize{Name: "ui-lg", Value: "15px"},
	},
}

// docsiteHeaderTokens is the token set of docsite-header.tokens.css, grouped like style.Theme.
type docsiteHeaderTokens struct {
	Colors     docsiteHeaderColors
	Typography docsiteHeaderTypography
}

// docsiteHeaderColors are the style.Color tokens of docsite-header.tokens.css.
type docsiteHeaderColors struct {
	// LineFaint is --color-line-faint. The faint hairline under the banner, one step quieter than
	// --color-border on both schemes.
	LineFaint style.Color
}

// docsiteHeaderTypography are the style.FontSize tokens of docsite-header.tokens.css.
type docsiteHeaderTypography struct {
	// Micro is --text-micro. The site's v2 type ramp has three steps between the built-in text
	// tokens: 11px mono footnotes (keycaps, version labels), 13px UI chrome
	// (the bar's voice, drawer links, footer links), 15px the body voice
	// the wordmark sits at.
	Micro style.FontSize

	// Ui is --text-ui.
	Ui style.FontSize

	// UiLg is --text-ui-lg.
	UiLg style.FontSize
}

// DarkTokens returns the @media (--dark) values of docsite-header.tokens.css, which
// Theme.Extend merges into DarkColors when the theme has a dark palette.
func (docsiteHeaderTokens) DarkTokens() map[string]string {
	return map[string]string{
		"line-faint": "oklch(0.22 0.005 75)",
	}
}
