// Code generated by "gofastr gen styles" from rtc-siteheader.style.css. DO NOT EDIT.
// Source hash: sha256:c02fc1e1ac54d78ab0f9e7a03541c7c63c5c02eb6aa62b44f306ccc69c639eef

package siteheader

import "github.com/DonaldMurillo/gofastr/core-ui/ownstyle"

// rtcSiteheaderCSS is the checked source of the rtc-siteheader owned style.
const rtcSiteheaderCSS = `/* The site's top bar: --size-header-height tall over one rule, its
   content on the page measure (--size-page-width, with
   --size-page-gutter outside it) — the same column ui.Container's page
   width gives main, so the brand sits on main's text edge. The links
   fit beside the brand at every width, so nothing folds away and there
   is no phone menu. */
:scope {
  border-block-end: 1px solid var(--color-border);
}

.bar {
  display: flex;
  align-items: center;
  gap: var(--spacing-xl);
  max-inline-size: calc(var(--size-page-width) + 2 * var(--size-page-gutter));
  block-size: var(--size-header-height);
  padding-inline: var(--size-page-gutter);
  margin-inline: auto;
}

.brand {
  display: inline-flex;
  align-items: center;
  gap: var(--spacing-md);
  flex-shrink: 0;
  color: var(--color-text);
  font-weight: var(--font-weight-semibold);
  text-decoration: none;
}

.links {
  display: flex;
  align-items: center;
  gap: var(--spacing-xl);
  margin-inline-start: auto;
}
.links a {
  color: var(--color-text-muted);
  font-size: var(--text-sm);
  font-weight: var(--font-weight-medium);
  text-decoration: none;
  transition: color var(--duration-fast) var(--easing-ease-out);
}
.links a:hover,
.links a[aria-current="page"] { color: var(--color-text); }
`

// rtcSiteheaderStyle carries the rtc-siteheader owned style: the registered sheet (Name, Kind and
// Scope come from the embedded *ownstyle.Sheet) plus its class
// vocabulary as methods returning local class names.
type rtcSiteheaderStyle struct {
	*ownstyle.Sheet
}

// Style is the rtc-siteheader owned style, registered at init.
// This package holds exactly one style file, so the handle is
// exported as Style; a package holding several exports each as
// <Owner>Style.
var Style = rtcSiteheaderStyle{ownstyle.Must("rtc-siteheader", ownstyle.KindScoped, rtcSiteheaderCSS)}

// Bar returns the local class name "bar".
func (s rtcSiteheaderStyle) Bar() string { return "bar" }

// Brand returns the local class name "brand".
func (s rtcSiteheaderStyle) Brand() string { return "brand" }

// Links returns the local class name "links".
func (s rtcSiteheaderStyle) Links() string { return "links" }
