// Code generated by "gofastr gen styles" from docsite-footer.tokens.css. DO NOT EDIT.
// Source hash: sha256:cd61b16ac4d06b8c9b9d817d9786c9504bdd64e37d6baaa78cb30cf9620995ea

package sitefooter

import "github.com/DonaldMurillo/gofastr/core-ui/style"

// Tokens is docsite-footer.tokens.css as typed theme tokens. Add them to the theme with
// Extend, which also takes the file's dark values:
//
//	site.WithTheme(theme.Default().Extend(sitefooter.Tokens))
var Tokens = docsiteFooterTokens{
	Spacing: docsiteFooterSpacing{
		Section: style.Spacing{Name: "section", Value: 64},
	},
}

// docsiteFooterTokens is the token set of docsite-footer.tokens.css, grouped like style.Theme.
type docsiteFooterTokens struct {
	Spacing docsiteFooterSpacing
}

// docsiteFooterSpacing are the style.Spacing tokens of docsite-footer.tokens.css.
type docsiteFooterSpacing struct {
	// Section is --spacing-section. The v2 rhythm's step above --spacing-3xl (48px): the colophon's
	// vertical air — grid top padding, column gap, and the strip above the
	// bottom line.
	Section style.Spacing
}
