// Code generated by "gofastr gen styles" from docpage.style.css. DO NOT EDIT.
// Source hash: sha256:ab68db3460740ed726628e902b9903e78d560e121296dd1a75e185e5f488e9ef

package docpage

import (
	"strings"

	"github.com/DonaldMurillo/gofastr/core-ui/ownstyle"
)

// docpageCSS is the checked source of the docpage owned style.
const docpageCSS = `/* The help/docs page: nav | article | contents, on the page measure
   (--size-page-width, with --size-page-gutter outside it) so the rails
   line up with the header's brand and call to action. */
:scope {
  display: grid;
  grid-template-columns: 13rem minmax(0, 1fr) 12rem;
  gap: var(--spacing-2xl);
  max-inline-size: calc(var(--size-page-width) + 2 * var(--size-page-gutter));
  margin-inline: auto;
  padding: var(--spacing-2xl) var(--size-page-gutter) var(--spacing-3xl);
}
/* An empty rail is one of two shapes: an element with no child at all
   (a region the caller left unset) or a sole child that is empty (an
   outlet with no fill). Both collapse. A rail holding content beside
   an empty outlet is not empty and stays. */
:scope:has(.toc:empty, .toc > :only-child:empty) { grid-template-columns: 13rem minmax(0, 1fr); }
.toc:empty, .toc:has(> :only-child:empty) { display: none; }
:scope:has(.nav:empty, .nav > :only-child:empty) { grid-template-columns: minmax(0, 1fr) 12rem; }
.nav:empty, .nav:has(> :only-child:empty) { display: none; }
/* No rails at all: one centred reading column at the prose measure. */
:scope:has(.nav:empty, .nav > :only-child:empty):has(.toc:empty, .toc > :only-child:empty) { grid-template-columns: minmax(0, 1fr); }
:scope:has(.nav:empty, .nav > :only-child:empty):has(.toc:empty, .toc > :only-child:empty) .article {
  inline-size: 100%;
  max-inline-size: var(--size-prose-measure);
  margin-inline: auto;
}

/* The rails stay in view under the pinned header while the article
   scrolls; a long nav scrolls on its own. */
.nav,
.toc {
  position: sticky;
  inset-block-start: calc(var(--size-header-height) + var(--spacing-2xl));
  align-self: start;
  max-block-size: calc(100dvh - var(--size-header-height) - 2 * var(--spacing-2xl));
  overflow-y: auto;
}

.article { min-inline-size: 0; }
.crumbs { margin-block-end: var(--spacing-lg); }
/* The article's own page header (the class rides its root). */
.title { margin-block-end: var(--spacing-lg); }

/* Article rhythm: headings open a section with room above, body text
   sits at a reading line height. A heading a contents link scrolls to
   stops below the header, not under it. */
.article h2,
.article h3 {
  scroll-margin-block-start: calc(var(--size-header-height) + var(--spacing-lg));
  line-height: 1.3;
}
.article h2 {
  margin: var(--spacing-3xl) 0 var(--spacing-md);
  font-size: var(--text-2xl);
}
.article h3 {
  margin: var(--spacing-2xl) 0 var(--spacing-sm);
  font-size: var(--text-xl);
}
/* Text stops at a reading measure, so an article with no contents
   rail does not run its lines across the freed column. */
.article p,
.article ul {
  max-inline-size: var(--size-prose-measure);
  margin-block: 0 var(--spacing-lg);
  line-height: 1.7;
}
.article ul { padding-inline-start: var(--spacing-xl); }
.article li + li { margin-block-start: var(--spacing-sm); }

/* Previous / next: two cards under the article, the next one on the
   right even when there is no previous. */
.pager {
  display: grid;
  grid-template-columns: repeat(2, minmax(0, 1fr));
  gap: var(--spacing-lg);
  margin-block-start: var(--spacing-3xl);
  padding-block-start: var(--spacing-xl);
  border-block-start: var(--stroke-thin) solid var(--color-border);
}
.page {
  display: flex;
  flex-direction: column;
  gap: var(--spacing-xs);
  padding: var(--spacing-lg);
  border: var(--stroke-thin) solid var(--color-border);
  border-radius: var(--radii-md);
  text-decoration: none;
  transition: border-color var(--duration-fast) var(--easing-ease-out);
}
.page.next {
  grid-column: 2;
  text-align: end;
}
.page:hover { border-color: var(--color-border-strong); }
.page:focus-visible { outline: var(--stroke-focus) solid var(--color-primary); outline-offset: var(--stroke-focus-offset); }
.dir {
  color: var(--color-text-subtle);
  font-size: var(--text-xs);
}
.page-title {
  color: var(--color-text);
  font-weight: var(--font-weight-medium);
}

@media (--reduced-motion) {
  .page { transition: none; }
}
/* Below lg the contents rail goes; the nav and the article remain,
   unless the nav's own region is empty too. */
@media (--below-lg) {
  :scope,
  :scope:has(.toc:empty, .toc > :only-child:empty) { grid-template-columns: 13rem minmax(0, 1fr); }
  :scope:has(.nav:empty, .nav > :only-child:empty) { grid-template-columns: minmax(0, 1fr); }
  .toc { display: none; }
}

/* Phones: one column. The nav is the Sidebar's own drawer row above
   the article, so it no longer pins. */
@media (--below-md) {
  :scope,
  :scope:has(.toc:empty, .toc > :only-child:empty),
  :scope:has(.nav:empty, .nav > :only-child:empty) {
    grid-template-columns: minmax(0, 1fr);
    gap: var(--spacing-lg);
    padding-block-start: var(--spacing-lg);
  }
  .nav {
    position: static;
    max-block-size: none;
    overflow-y: visible;
  }
  .pager { grid-template-columns: minmax(0, 1fr); }
  .page.next { grid-column: auto; }
}
`

// docpageStyle carries the docpage owned style: the registered sheet (Name, Kind and
// Scope come from the embedded *ownstyle.Sheet) plus its class
// vocabulary as methods returning local class names.
type docpageStyle struct {
	*ownstyle.Sheet
}

// Style is the docpage owned style, registered at init.
// This package holds exactly one style file, so the handle is
// exported as Style; a package holding several exports each as
// <Owner>Style.
var Style = docpageStyle{ownstyle.Must("docpage", ownstyle.KindScoped, docpageCSS)}

// Toc returns the local class name "toc".
//
// The rails stay in view under the pinned header while the article
// scrolls; a long nav scrolls on its own.
func (s docpageStyle) Toc() string { return "toc" }

// Nav returns the local class name "nav".
//
// The rails stay in view under the pinned header while the article
// scrolls; a long nav scrolls on its own.
func (s docpageStyle) Nav() string { return "nav" }

// Article returns the local class name "article".
//
// Article rhythm: headings open a section with room above, body text
// sits at a reading line height. A heading a contents link scrolls to
// stops below the header, not under it.
func (s docpageStyle) Article() string { return "article" }

// Crumbs returns the local class name "crumbs".
func (s docpageStyle) Crumbs() string { return "crumbs" }

// Title returns the local class name "title".
//
// The article's own page header (the class rides its root).
func (s docpageStyle) Title() string { return "title" }

// Pager returns the local class name "pager".
//
// Previous / next: two cards under the article, the next one on the
// right even when there is no previous.
func (s docpageStyle) Pager() string { return "pager" }

// Page returns the local class name "page".
func (s docpageStyle) Page() string { return "page" }

// PageVariants selects the variants of the page base class.
type PageVariants struct {
	// Next reports whether the "next" flag class is set.
	Next bool
}

// PageWith returns the page base class plus the selected
// variants, space-separated in declaration order.
func (s docpageStyle) PageWith(v PageVariants) string {
	classes := []string{s.Page()}
	if v.Next {
		classes = append(classes, "next")
	}
	return strings.Join(classes, " ")
}

// Dir returns the local class name "dir".
func (s docpageStyle) Dir() string { return "dir" }

// PageTitle returns the local class name "page-title".
func (s docpageStyle) PageTitle() string { return "page-title" }
