// Code generated by "gofastr gen styles" from meridian-siteheader.tokens.css. DO NOT EDIT.
// Source hash: sha256:e0ddb9731245fec7f47b2f29e1db1c698f13efb04f1446d0076144c2ad51dc73

package siteheader

import (
	"time"

	"github.com/DonaldMurillo/gofastr/core-ui/style"
)

// Tokens is meridian-siteheader.tokens.css as typed theme tokens. Add them to the theme with
// Extend, which also takes the file's dark values:
//
//	site.WithTheme(theme.Default().Extend(siteheader.Tokens))
var Tokens = meridianSiteheaderTokens{
	Durations: meridianSiteheaderDurations{
		MenuStagger: style.Duration{Name: "menu-stagger", Value: 40 * time.Millisecond},
	},
}

// meridianSiteheaderTokens is the token set of meridian-siteheader.tokens.css, grouped like style.Theme.
type meridianSiteheaderTokens struct {
	Durations meridianSiteheaderDurations
}

// meridianSiteheaderDurations are the style.Duration tokens of meridian-siteheader.tokens.css.
type meridianSiteheaderDurations struct {
	// MenuStagger is --duration-menu-stagger. The phone menu's rows land one after another, each this much after
	// the one above; the bar's actions follow the last row.
	MenuStagger style.Duration
}
