// meridian is a terminal client for your app's HTTP API, generated by
// `gofastr generate cli --binary=meridian`. The code is yours to own and edit; to
// regenerate from the current entity set, re-run that command with --force
// (custom.go — your extension seam — is never overwritten).
package main

import (
	"fmt"
	"os"
	"sort"
	"strings"
)

const (
	binaryName = "meridian"
	envPrefix  = "MERIDIAN"
	apiPrefix  = "/api"
)

// command is one dispatchable CLI command. name is the space-joined path
// ("login", "plans list"); the longest match wins, and entries from customCommands()
// (custom.go) override generated ones with the same name.
type command struct {
	name    string
	summary string
	run     func(args []string) int
}

func main() { os.Exit(run(os.Args[1:])) }

// commandMap merges customCommands() over the generated set — a custom
// entry with a generated name replaces it.
func commandMap() map[string]command {
	cmds := map[string]command{}
	for _, c := range builtinCommands() {
		cmds[c.name] = c
	}
	for _, c := range customCommands() {
		cmds[c.name] = c
	}
	return cmds
}

func run(args []string) int {
	cmds := commandMap()
	if len(args) == 0 || args[0] == "help" || args[0] == "--help" || args[0] == "-h" {
		printUsage(cmds)
		return 0
	}
	if args[0] == "version" || args[0] == "--version" {
		fmt.Printf("%s (generated by gofastr)\n", binaryName)
		return 0
	}
	if len(args) >= 2 {
		if c, ok := cmds[args[0]+" "+args[1]]; ok {
			return c.run(args[2:])
		}
	}
	if c, ok := cmds[args[0]]; ok {
		return c.run(args[1:])
	}
	fmt.Fprintf(os.Stderr, "%s: unknown command %q\n\n", binaryName, strings.Join(args[:min(2, len(args))], " "))
	printUsage(cmds)
	return 2
}

func builtinCommands() []command {
	cmds := []command{
		{name: "login", summary: "store the server URL and a scoped API token", run: runLogin},
		{name: "logout", summary: "remove the stored API token", run: runLogout},
	}
	cmds = append(cmds, plansCommands()...)
	cmds = append(cmds, customersCommands()...)
	cmds = append(cmds, subscriptionsCommands()...)
	cmds = append(cmds, invoicesCommands()...)
	cmds = append(cmds, paymentsCommands()...)
	return cmds
}

func printUsage(cmds map[string]command) {
	fmt.Printf("Usage: %s <command> [args]\n\nCommands:\n", binaryName)
	names := make([]string, 0, len(cmds))
	for name := range cmds {
		names = append(names, name)
	}
	sort.Strings(names)
	for _, name := range names {
		fmt.Printf("  %-28s %s\n", name, cmds[name].summary)
	}
	fmt.Printf("\nConnection: --url/--token flags, %s_URL/%s_TOKEN env vars, or `%s login`.\n", envPrefix, envPrefix, binaryName)
}

// groupUsage prints one command group's subcommands (the bare entity
// command lands here). A stray argument means an unknown subcommand:
// usage still prints, exit is 2.
func groupUsage(group string, args []string) int {
	code := 0
	if len(args) > 0 && args[0] != "--help" && args[0] != "-h" && args[0] != "help" {
		fmt.Fprintf(os.Stderr, "%s %s: unknown subcommand %q\n\n", binaryName, group, args[0])
		code = 2
	}
	cmds := commandMap()
	fmt.Printf("Usage: %s %s <subcommand> [flags]\n\nSubcommands:\n", binaryName, group)
	names := make([]string, 0, len(cmds))
	for name := range cmds {
		if strings.HasPrefix(name, group+" ") {
			names = append(names, name)
		}
	}
	sort.Strings(names)
	for _, name := range names {
		fmt.Printf("  %-28s %s\n", name, cmds[name].summary)
	}
	return code
}
