// Code generated by "gofastr gen styles" from meridian-sitefooter.style.css. DO NOT EDIT.
// Source hash: sha256:3d9f7b136e82763bdbfa7c75ac87c00c0fd989948f0c0c03969d9263aa534f0c

package sitefooter

import "github.com/DonaldMurillo/gofastr/core-ui/ownstyle"

// meridianSitefooterCSS is the checked source of the meridian-sitefooter owned style.
const meridianSitefooterCSS = `/* Meridian's colophon: the wordmark, then the link columns. The
   content sits on the page measure (--size-page-width, with
   --size-page-gutter outside it), the column the header and main
   use. */
:scope {
  border-block-start: 1px solid var(--color-border);
}

.inner {
  max-inline-size: calc(var(--size-page-width) + 2 * var(--size-page-gutter));
  margin-inline: auto;
  padding: var(--spacing-3xl) var(--size-page-gutter) var(--spacing-xl);
}

/* The wordmark takes the first third; the columns share the rest and
   wrap when they run out of room. */
.top {
  display: grid;
  grid-template-columns: minmax(0, 1fr) minmax(0, 2fr);
  gap: var(--spacing-2xl);
}

.brand {
  color: var(--color-primary);
  font-weight: var(--font-weight-semibold);
  letter-spacing: -0.01em;
  text-decoration: none;
}
.brand:hover { color: var(--color-primary); }

.columns {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(10rem, 1fr));
  gap: var(--spacing-xl);
}
.title {
  margin: 0 0 var(--spacing-md);
  color: var(--color-text);
  font-size: var(--text-sm);
  font-weight: var(--font-weight-medium);
}
.links {
  display: grid;
  gap: var(--spacing-md);
  margin: 0;
  padding: 0;
  list-style: none;
}
.links a {
  color: var(--color-text-muted);
  font-size: var(--text-sm);
  text-decoration: none;
  transition: color var(--duration-fast) var(--easing-ease-out);
}
.links a:hover { color: var(--color-text); }
.links a:focus-visible,
.brand:focus-visible { outline: 2px solid var(--color-primary); outline-offset: 2px; }

@media (--reduced-motion) {
  .links a { transition: none; }
}

/* Phones: the wordmark stacks over the columns. */
@media (--below-md) {
  .top { grid-template-columns: minmax(0, 1fr); }
}
`

// meridianSitefooterStyle carries the meridian-sitefooter owned style: the registered sheet (Name, Kind and
// Scope come from the embedded *ownstyle.Sheet) plus its class
// vocabulary as methods returning local class names.
type meridianSitefooterStyle struct {
	*ownstyle.Sheet
}

// Style is the meridian-sitefooter owned style, registered at init.
// This package holds exactly one style file, so the handle is
// exported as Style; a package holding several exports each as
// <Owner>Style.
var Style = meridianSitefooterStyle{ownstyle.Must("meridian-sitefooter", ownstyle.KindScoped, meridianSitefooterCSS)}

// Inner returns the local class name "inner".
func (s meridianSitefooterStyle) Inner() string { return "inner" }

// Top returns the local class name "top".
//
// The wordmark takes the first third; the columns share the rest and
// wrap when they run out of room.
func (s meridianSitefooterStyle) Top() string { return "top" }

// Brand returns the local class name "brand".
func (s meridianSitefooterStyle) Brand() string { return "brand" }

// Columns returns the local class name "columns".
func (s meridianSitefooterStyle) Columns() string { return "columns" }

// Title returns the local class name "title".
func (s meridianSitefooterStyle) Title() string { return "title" }

// Links returns the local class name "links".
func (s meridianSitefooterStyle) Links() string { return "links" }
