// Code generated by "gofastr gen styles" from docsite-docpage.tokens.css. DO NOT EDIT.
// Source hash: sha256:0c7a4d4c21e1aa9d2656edcae08830ce2fc460a2bafecafcfbbb9dadb17af6f8

package docpage

import "github.com/DonaldMurillo/gofastr/core-ui/style"

// Tokens is docsite-docpage.tokens.css as typed theme tokens. Add them to the theme with
// Extend, which also takes the file's dark values:
//
//	site.WithTheme(theme.Default().Extend(docpage.Tokens))
var Tokens = docsiteDocpageTokens{
	Spacing: docsiteDocpageSpacing{
		Page: style.Spacing{Name: "page", Value: 96},
	},
}

// docsiteDocpageTokens is the token set of docsite-docpage.tokens.css, grouped like style.Theme.
type docsiteDocpageTokens struct {
	Spacing docsiteDocpageSpacing
}

// docsiteDocpageSpacing are the style.Spacing tokens of docsite-docpage.tokens.css.
type docsiteDocpageSpacing struct {
	// Page is --spacing-page. The air under an article before the page ends — the v2 rhythm's step
	// above the colophon's --spacing-section.
	Page style.Spacing
}
