// Code generated by "gofastr gen styles" from docsite-docpage.style.css. DO NOT EDIT.
// Source hash: sha256:b59c132f9d9aaf450457ba8d4cef4bbe374d5ac50b437cf25844f72e1e012e88

package docpage

import (
	"strings"

	"github.com/DonaldMurillo/gofastr/core-ui/ownstyle"
)

// docsiteDocpageCSS is the checked source of the docsite-docpage owned style.
const docsiteDocpageCSS = `/* The article shell: nav | article, on the 1360px measure the framework
   doc layout used, with the same 48px gutters and the article capped at
   a reading measure. Without a nav the page is the narrow shape: one
   centered column. */
:scope {
  display: grid;
  grid-template-columns: minmax(0, 1fr);
  gap: var(--spacing-3xl);
  /* A definite width is what keeps a grid-item doc page (inside ui.ContentRow) from blowing its track out to min-content; 100% is the parent's width, not a design value */
  inline-size: 100%;
  max-inline-size: 1360px;
  margin-inline: auto;
  padding: var(--spacing-2xl) var(--spacing-2xl) var(--spacing-page);
}
:scope:has(> .nav) { grid-template-columns: 220px minmax(0, 1fr); }

/* The nav slot brings its own styling (interactive.SectionMenu ships
   the sticky rail + mobile sheet); this sheet only sizes its column.
   The wrapper is a flex column whose child fills it, so the grid row's
   stretch reaches the widget root — that tall containing block is what
   the rail's position: sticky travels. */
.nav {
  display: flex;
  flex-direction: column;
}
.nav > * {
  flex: 1 1 auto;
}

/* The article column. */
.content {
  max-inline-size: 720px;
}

/* The layer shape (Layer): nav | article | rail. The rail cell comes
   before the article in source order so it stacks above it on phones;
   on wide screens each cell names its column. An unfilled rail outlet
   is an empty cell: the column collapses and the shell is nav |
   article. The rail is sticky inside a full-height column, the same
   flex shape the nav uses. */
.rail {
  display: flex;
  flex-direction: column;
  grid-column: 3;
  grid-row: 1;
}
.rail > * {
  flex: 1 1 auto;
}
.rail:has(> :empty) { display: none; }
:scope:has(> .rail) > .nav { grid-column: 1; grid-row: 1; }
:scope:has(> .rail) > .content { grid-column: 2; grid-row: 1; }
:scope:has(> .rail > :not(:empty)) { grid-template-columns: 220px minmax(0, 1fr) 220px; }

/* An unfilled crumbs outlet takes no room above the body. */
.crumbs:has(> :empty) { display: none; }
/* The narrow shape centers the article. The track is the reading
   measure and the grid centers the track: auto margins on the article
   would stop it stretching, and a short page would shrink to its
   content. */
:scope:not(:has(> .nav)) {
  grid-template-columns: minmax(0, 720px);
  justify-content: center;
}

/* Breadcrumbs: the mono voice for the trail, the component's own
   rhythm inside it. */
.crumbs {
  margin-block-end: var(--spacing-xl);
  font-family: var(--font-mono);
}

/* Previous / next: two cards under the article, the next one on the
   right even when there is no previous. */
.pager-foot {
  margin-block-start: var(--spacing-2xl);
  padding-block-start: var(--spacing-xl);
  border-block-start: var(--stroke-thin) solid var(--color-border);
}
.pager {
  display: grid;
  grid-template-columns: repeat(2, minmax(0, 1fr));
  gap: var(--spacing-lg);
}
.page {
  display: flex;
  flex-direction: column;
  gap: var(--spacing-sm);
  padding: var(--spacing-lg);
  background: var(--color-surface);
  border: var(--stroke-thin) solid var(--color-border);
  border-radius: var(--radii-md);
  text-decoration: none;
  transition: border-color var(--duration-fast) var(--easing-ease-out);
}
.page.next {
  grid-column: 2;
  text-align: end;
}
.page:hover { border-color: var(--color-border-strong); }
.page:focus-visible { outline: var(--stroke-focus) solid var(--color-text-subtle); outline-offset: var(--stroke-focus-offset); }
.dir {
  font-family: var(--font-mono);
  font-size: var(--text-xs);
  color: var(--color-text-subtle);
}
.page-title {
  color: var(--color-text);
  font-weight: var(--font-weight-medium);
}

@media (--reduced-motion) {
  .page { transition: none; }
}

/* One column below SectionMenu's own swap point: the rail becomes the
   "Sections" pill + sheet there, so this grid must give up its column
   in the same breath. */
/* gofastr:allow(GOFASTR1812) collapses in lockstep with interactive.SectionMenu's own 899.98px rail→sheet swap, the one width neither sheet may drift from */
@media (max-width: 899.98px) {
  :scope {
    display: block;
    max-inline-size: none;
    padding: var(--spacing-lg);
  }
  /* display:block drops the grid gap — restore separation between the
     stacked SectionMenu pill and the article below it. */
  :scope > * + * { margin-block-start: var(--spacing-xl); }
  .content {
    max-inline-size: none;
    overflow-x: hidden;
  }
  .pager { grid-template-columns: minmax(0, 1fr); }
  .page.next { grid-column: auto; }
}
`

// docsiteDocpageStyle carries the docsite-docpage owned style: the registered sheet (Name, Kind and
// Scope come from the embedded *ownstyle.Sheet) plus its class
// vocabulary as methods returning local class names.
type docsiteDocpageStyle struct {
	*ownstyle.Sheet
}

// Style is the docsite-docpage owned style, registered at init.
// This package holds exactly one style file, so the handle is
// exported as Style; a package holding several exports each as
// <Owner>Style.
var Style = docsiteDocpageStyle{ownstyle.Must("docsite-docpage", ownstyle.KindScoped, docsiteDocpageCSS)}

// Nav returns the local class name "nav".
//
// The nav slot brings its own styling (interactive.SectionMenu ships
// the sticky rail + mobile sheet); this sheet only sizes its column.
// The wrapper is a flex column whose child fills it, so the grid row's
// stretch reaches the widget root — that tall containing block is what
// the rail's position: sticky travels.
func (s docsiteDocpageStyle) Nav() string { return "nav" }

// Content returns the local class name "content".
//
// The article column.
func (s docsiteDocpageStyle) Content() string { return "content" }

// Rail returns the local class name "rail".
//
// The layer shape (Layer): nav | article | rail. The rail cell comes
// before the article in source order so it stacks above it on phones;
// on wide screens each cell names its column. An unfilled rail outlet
// is an empty cell: the column collapses and the shell is nav |
// article. The rail is sticky inside a full-height column, the same
// flex shape the nav uses.
func (s docsiteDocpageStyle) Rail() string { return "rail" }

// Crumbs returns the local class name "crumbs".
//
// An unfilled crumbs outlet takes no room above the body.
func (s docsiteDocpageStyle) Crumbs() string { return "crumbs" }

// PagerFoot returns the local class name "pager-foot".
//
// Previous / next: two cards under the article, the next one on the
// right even when there is no previous.
func (s docsiteDocpageStyle) PagerFoot() string { return "pager-foot" }

// Pager returns the local class name "pager".
func (s docsiteDocpageStyle) Pager() string { return "pager" }

// Page returns the local class name "page".
func (s docsiteDocpageStyle) Page() string { return "page" }

// PageVariants selects the variants of the page base class.
type PageVariants struct {
	// Next reports whether the "next" flag class is set.
	Next bool
}

// PageWith returns the page base class plus the selected
// variants, space-separated in declaration order.
func (s docsiteDocpageStyle) PageWith(v PageVariants) string {
	classes := []string{s.Page()}
	if v.Next {
		classes = append(classes, "next")
	}
	return strings.Join(classes, " ")
}

// Dir returns the local class name "dir".
func (s docsiteDocpageStyle) Dir() string { return "dir" }

// PageTitle returns the local class name "page-title".
func (s docsiteDocpageStyle) PageTitle() string { return "page-title" }
