// Code generated by gofastr. Owned — safe to edit.
package blueprint

import (
	"context"
	"fmt"
	"math"
	"strconv"
	"strings"
	"time"

	appui "github.com/DonaldMurillo/gofastr/core-ui/app"
	"github.com/DonaldMurillo/gofastr/core-ui/html"
	"github.com/DonaldMurillo/gofastr/core-ui/patterns/pagination"
	"github.com/DonaldMurillo/gofastr/core/render"
	"github.com/DonaldMurillo/gofastr/framework"
	"github.com/DonaldMurillo/gofastr/framework/filter"
	"github.com/DonaldMurillo/gofastr/framework/ui"
)

// blueprintResources holds one ResourceConfig per entity, populated by
// RegisterGenerated once the CrudHandlers exist. Screens look entities up by
// name to render their server-side list/detail views.
var blueprintResources = map[string]ResourceConfig{}

// ResField is one displayed entity field.
type ResField struct {
	Key    string
	Label  string
	Type   string   // string,text,int,float,decimal,bool,enum,date,timestamp,uuid,relation,...
	Values []string // enum: the allowed values (drives <option>s on the form)
}

// RelSource resolves a foreign-key column to a related record's label.
type RelSource struct {
	Crud    *framework.CrudHandler
	Display string
}

// Transition is a status-change workflow action shown on a detail page — a
// button that PUTs {status: Status} to the entity, then refreshes (Mark paid).
type Transition struct {
	Label   string
	Status  string
	Variant string // "primary" | "secondary" | "danger" | "ghost" (default secondary)
	Stamp   string // optional date field stamped with today on transition
}

// RelatedList is a reverse relation surfaced on a detail page: the records of
// another entity that point back at this one via ForeignKey. Turns a detail
// page from a row editor into an account view (a customer + their invoices).
type RelatedList struct {
	Title      string // e.g. "Invoices"
	ForeignKey string // the FK column on the related entity, e.g. "customer_id"
	BasePath   string // the related entity's app route, e.g. "/app/invoices"
	Crud       *framework.CrudHandler
	Fields     []ResField
	Relations  map[string]RelSource // for resolving the related rows' own FKs
}

// ResourceConfig drives the server-rendered list + detail + form screens for
// one entity.
type ResourceConfig struct {
	Title       string
	Singular    string
	BasePath    string // app route, e.g. "/app/customers"
	APIPath     string // auto-CRUD JSON endpoint, e.g. "/api/customers"
	Crud        *framework.CrudHandler
	Fields      []ResField
	Search      string
	PageSize    int
	Relations   map[string]RelSource
	CanCreate   bool          // List shows "New"; a /new create form is mounted
	CanEdit     bool          // Detail shows Edit + Delete; a /{id}/edit form is mounted
	Heading     string        // overrides the list's title (the block's text:)
	EmptyText   string        // overrides the empty-state description (the block's empty_text:)
	Related     []RelatedList // reverse relations surfaced on the detail page
	Transitions []Transition  // status-transition workflow buttons on the detail page
}

// WithTransitions sets the detail-page status-transition workflow buttons.
func (c ResourceConfig) WithTransitions(ts ...Transition) ResourceConfig {
	c.Transitions = ts
	return c
}

func (c ResourceConfig) pageSize() int {
	if c.PageSize > 0 {
		return c.PageSize
	}
	return 25
}

func (c ResourceConfig) hasField(k string) bool {
	for _, f := range c.Fields {
		if f.Key == k {
			return true
		}
	}
	return false
}

func (c ResourceConfig) field(k string) (ResField, bool) {
	for _, f := range c.Fields {
		if f.Key == k {
			return f, true
		}
	}
	return ResField{}, false
}

// WithColumns returns a copy showing only the named fields, in the given order.
func (c ResourceConfig) WithColumns(keys ...string) ResourceConfig {
	fields := make([]ResField, 0, len(keys))
	for _, k := range keys {
		if f, ok := c.field(k); ok {
			fields = append(fields, f)
		}
	}
	c.Fields = fields
	return c
}

// WithSearch sets the LIKE-search field. WithLimit sets the page size.
// WithCreate shows a "New" action linking to BasePath/new.
func (c ResourceConfig) WithSearch(field string) ResourceConfig { c.Search = field; return c }
func (c ResourceConfig) WithLimit(n int) ResourceConfig         { c.PageSize = n; return c }
func (c ResourceConfig) WithCreate() ResourceConfig             { c.CanCreate = true; return c }

// WithEdit shows Edit + Delete on the detail screen (a /{id}/edit form is mounted).
func (c ResourceConfig) WithEdit() ResourceConfig { c.CanEdit = true; return c }

// WithHeading overrides the list's title; WithEmpty overrides the empty-state text.
func (c ResourceConfig) WithHeading(s string) ResourceConfig { c.Heading = s; return c }
func (c ResourceConfig) WithEmpty(s string) ResourceConfig   { c.EmptyText = s; return c }

func (c ResourceConfig) relationLabels(ctx context.Context) map[string]map[string]string {
	out := map[string]map[string]string{}
	for col, rel := range c.Relations {
		if rel.Crud == nil {
			continue
		}
		rows, err := rel.Crud.ListAll(ctx, framework.ListOptions{Limit: 1000})
		if err != nil {
			continue
		}
		m := map[string]string{}
		for _, r := range rows {
			id := resCell(resGet(r, "id"))
			if id == "" {
				continue
			}
			label := resCell(resGet(r, rel.Display))
			if label == "" {
				label = id
			}
			m[id] = label
		}
		out[col] = m
	}
	return out
}

// List renders the entity list screen.
func (c ResourceConfig) List(ctx context.Context) render.HTML {
	q := appui.QueryFromContext(ctx)
	page := 1
	if n, err := strconv.Atoi(q.Get("p")); err == nil && n > 1 {
		page = n
	}
	limit := c.pageSize()
	search := strings.TrimSpace(q.Get("q"))

	var filters []filter.ParsedFilter
	if search != "" && c.Search != "" {
		filters = append(filters, filter.ParsedFilter{Field: c.Search, Op: filter.OpLike, Value: search})
	}
	var sorts []filter.ParsedSort
	sortCol := q.Get("sort")
	if sortCol != "" && c.hasField(sortCol) {
		sorts = append(sorts, filter.ParsedSort{Field: sortCol, Desc: q.Get("dir") == "desc"})
	}

	total, _ := c.Crud.CountAll(ctx, framework.ListOptions{Filters: filters})
	rows, err := c.Crud.ListAll(ctx, framework.ListOptions{Filters: filters, Sorts: sorts, Limit: limit, Offset: (page - 1) * limit})

	var actions render.HTML
	if c.CanCreate {
		actions = ui.LinkButton(ui.LinkButtonConfig{Label: "New " + c.Singular, Href: c.BasePath + "/new", Variant: ui.ButtonPrimary})
	}
	title := c.Title
	if c.Heading != "" {
		title = c.Heading
	}
	body := []render.HTML{ui.PageHeader(ui.PageHeaderConfig{Title: title, Subtitle: resCountLabel(total, c.Singular, c.Title), Actions: actions})}
	if c.Search != "" {
		body = append(body, ui.SearchInput(ui.SearchInputConfig{
			Name: "q", ID: "search-" + c.Title, Action: c.BasePath, Method: "GET",
			Placeholder: "Search " + c.Title, ExtraAttrs: map[string]string{"value": search},
		}))
	}
	if err != nil {
		body = append(body, ui.Callout(ui.CalloutConfig{Title: "Couldn't load " + c.Title, Variant: ui.StatusDanger}, render.Text("See server logs.")))
		return render.Join(body...)
	}

	rel := c.relationLabels(ctx)
	cols := make([]ui.Column, 0, len(c.Fields)+1)
	for _, f := range c.Fields {
		col := ui.Column{Key: f.Key, Header: f.Label, Sortable: true}
		if resNumeric(f.Type) {
			col.Align = "end"
		}
		cols = append(cols, col)
	}
	cols = append(cols, ui.Column{Key: "_a", Header: "", Align: "end"})

	uiRows := make([]ui.Row, 0, len(rows))
	for _, row := range rows {
		id := resCell(resGet(row, "id"))
		cells := map[string]render.HTML{}
		for _, f := range c.Fields {
			cells[f.Key] = resFormat(f, resGet(row, f.Key), rel)
		}
		cells["_a"] = ui.Link(ui.LinkConfig{Href: c.BasePath + "/" + id, Text: "View", Variant: ui.LinkAction})
		uiRows = append(uiRows, ui.Row{ID: id, Cells: cells})
	}

	carry := ""
	if search != "" {
		carry = "q=" + search + "&"
	}
	dt := ui.DataTableConfig{
		Columns: cols, Rows: uiRows, Responsive: ui.ResponsiveCards,
		SortBy: sortCol, SortDir: ui.SortDir(q.Get("dir")),
		SortHrefPattern: "?" + carry + "sort=%s&dir=%s",
		Empty:           ui.EmptyStateConfig{Title: "No " + c.Title + " yet", Description: resEmptyDesc(c.EmptyText)},
	}
	if pages := int(math.Ceil(float64(total) / float64(limit))); pages > 1 {
		dt.Pagination = &pagination.Config{Total: pages, Current: page, HrefPattern: "?" + carry + "p=%d"}
	}
	body = append(body, ui.DataTable(dt))
	return render.Join(body...)
}

// Detail renders the single-record detail screen.
func (c ResourceConfig) Detail(ctx context.Context, id string) render.HTML {
	row, err := c.Crud.GetOne(ctx, id, nil)
	if err != nil || row == nil {
		return ui.EmptyState(ui.EmptyStateConfig{Title: "Not found", Description: "This " + c.Singular + " does not exist."})
	}
	rel := c.relationLabels(ctx)
	title := resCell(resGet(row, "name"))
	if title == "" {
		title = resCell(resGet(row, "title"))
	}
	if title == "" {
		title = c.Singular
	}
	items := make([]ui.DetailItem, 0, len(c.Fields))
	for _, f := range c.Fields {
		items = append(items, ui.DetailItem{Label: f.Label, Value: resFormat(f, resGet(row, f.Key), rel)})
	}
	actions := []render.HTML{}
	for _, t := range c.Transitions {
		body := "{\"status\":\"" + t.Status + "\""
		if t.Stamp != "" {
			body += ",\"" + t.Stamp + "\":\"" + resToday() + "\""
		}
		body += "}"
		actions = append(actions, ui.Button(ui.ButtonConfig{Label: t.Label, Variant: resButtonVariant(t.Variant), ExtraAttrs: html.Attrs{
			"data-fui-rpc":          c.APIPath + "/" + id,
			"data-fui-rpc-method":   "PUT",
			"data-fui-rpc-body":     body,
			"data-fui-rpc-navigate": c.BasePath + "/" + id,
		}}))
	}
	if c.CanEdit {
		actions = append(actions,
			ui.LinkButton(ui.LinkButtonConfig{Label: "Edit", Href: c.BasePath + "/" + id + "/edit", Variant: ui.ButtonSecondary}),
			ui.Button(ui.ButtonConfig{Label: "Delete", Variant: ui.ButtonDanger, ExtraAttrs: html.Attrs{
				"data-fui-rpc":          c.APIPath + "/" + id,
				"data-fui-rpc-method":   "DELETE",
				"data-fui-rpc-navigate": c.BasePath,
				"data-fui-confirm":      "Delete this " + c.Singular + "? This cannot be undone.",
			}}),
		)
	}
	actions = append(actions, ui.Link(ui.LinkConfig{Href: c.BasePath, Text: "← Back", Variant: ui.LinkMuted}))
	body := []render.HTML{
		ui.PageHeader(ui.PageHeaderConfig{Title: title, Actions: ui.Cluster(ui.ClusterConfig{}, actions...)}),
		ui.DetailList(ui.DetailListConfig{Items: items}),
	}
	for _, rl := range c.Related {
		body = append(body, c.relatedList(ctx, rl, id))
	}
	return render.Join(body...)
}

// relatedList renders one reverse-relation section: the related entity's rows
// where ForeignKey == this record's id, as a compact table under a heading.
func (c ResourceConfig) relatedList(ctx context.Context, rl RelatedList, id string) render.HTML {
	rows, err := rl.Crud.ListAll(ctx, framework.ListOptions{
		Filters: []filter.ParsedFilter{{Field: rl.ForeignKey, Op: filter.OpEq, Value: id}},
		Limit:   10,
	})
	head := ui.PageHeader(ui.PageHeaderConfig{Title: rl.Title, Subtitle: resCountLabel(len(rows), strings.TrimSuffix(rl.Title, "s"), rl.Title)})
	if err != nil {
		return render.Join(head, ui.Callout(ui.CalloutConfig{Variant: ui.StatusDanger, Title: "Couldn't load " + rl.Title}, render.Text("See server logs.")))
	}
	if len(rows) == 0 {
		return render.Join(head, ui.EmptyState(ui.EmptyStateConfig{Title: "No " + strings.ToLower(rl.Title) + " yet", Description: "They will appear here once added."}))
	}
	relLabels := relatedRelationLabels(ctx, rl.Relations)
	cols := make([]ui.Column, 0, len(rl.Fields)+1)
	for _, f := range rl.Fields {
		col := ui.Column{Key: f.Key, Header: f.Label}
		if resNumeric(f.Type) {
			col.Align = "end"
		}
		cols = append(cols, col)
	}
	if rl.BasePath != "" {
		cols = append(cols, ui.Column{Key: "_a", Header: "", Align: "end"})
	}
	uiRows := make([]ui.Row, 0, len(rows))
	for _, row := range rows {
		rid := resCell(resGet(row, "id"))
		cells := map[string]render.HTML{}
		for _, f := range rl.Fields {
			cells[f.Key] = resFormat(f, resGet(row, f.Key), relLabels)
		}
		if rl.BasePath != "" {
			cells["_a"] = ui.Link(ui.LinkConfig{Href: rl.BasePath + "/" + rid, Text: "View", Variant: ui.LinkAction})
		}
		uiRows = append(uiRows, ui.Row{ID: rid, Cells: cells})
	}
	return render.Join(head, ui.DataTable(ui.DataTableConfig{Columns: cols, Rows: uiRows, Responsive: ui.ResponsiveCards}))
}

// relatedRelationLabels resolves the FK columns of a related entity's rows to
// display names (so an invoice row under a customer still shows plan names etc.).
func relatedRelationLabels(ctx context.Context, rels map[string]RelSource) map[string]map[string]string {
	out := map[string]map[string]string{}
	for col, rel := range rels {
		if rel.Crud == nil {
			continue
		}
		rows, err := rel.Crud.ListAll(ctx, framework.ListOptions{Limit: 1000})
		if err != nil {
			continue
		}
		m := map[string]string{}
		for _, r := range rows {
			rid := resCell(resGet(r, "id"))
			if rid == "" {
				continue
			}
			label := resCell(resGet(r, rel.Display))
			if label == "" {
				label = rid
			}
			m[rid] = label
		}
		out[col] = m
	}
	return out
}

// Form renders the create (id == "") or edit (id != "") form for one record.
// It submits as an island: data-fui-rpc posts/puts JSON to the entity's
// auto-CRUD endpoint, then SPA-navigates back to the list/detail on success.
func (c ResourceConfig) Form(ctx context.Context, id string) render.HTML {
	edit := id != ""
	var row map[string]any
	if edit {
		r, err := c.Crud.GetOne(ctx, id, nil)
		if err != nil || r == nil {
			return ui.EmptyState(ui.EmptyStateConfig{Title: "Not found", Description: "This " + c.Singular + " does not exist."})
		}
		row = r
	}
	rel := c.relationLabels(ctx)

	title, submit := "New "+c.Singular, "Create "+c.Singular
	rpc, method, back := c.APIPath, "POST", c.BasePath
	if edit {
		title, submit = "Edit "+c.Singular, "Save changes"
		rpc, method, back = c.APIPath+"/"+id, "PUT", c.BasePath+"/"+id
	}
	attrs := html.Attrs{
		"data-fui-rpc":          rpc,
		"data-fui-rpc-method":   method,
		"data-fui-rpc-navigate": back,
	}

	fields := make([]render.HTML, 0, len(c.Fields))
	for _, f := range c.Fields {
		cur := ""
		if edit {
			cur = resCell(resGet(row, f.Key))
		}
		fields = append(fields, ui.FormField(ui.FormFieldConfig{
			Label: f.Label, For: "f-" + f.Key, Input: c.formInput(ctx, f, cur, rel),
		}))
	}
	form := ui.Form(ui.FormConfig{Action: rpc, Method: "POST", SubmitLabel: submit, ExtraAttrs: attrs, Ctx: ctx}, fields...)
	return render.Join(
		ui.PageHeader(ui.PageHeaderConfig{Title: title, Actions: ui.Link(ui.LinkConfig{Href: back, Text: "← Cancel", Variant: ui.LinkMuted})}),
		form,
	)
}

// formInput builds the typed control for one field, prefilled with cur. Enums
// and relations render their options server-side; relations resolve to the same
// human label the list/detail show.
func (c ResourceConfig) formInput(ctx context.Context, f ResField, cur string, rel map[string]map[string]string) render.HTML {
	id := "f-" + f.Key
	if labels, ok := rel[f.Key]; ok {
		opts := []html.SelectOption{{Value: "", Text: "— Select —"}}
		for val, label := range labels {
			opts = append(opts, html.SelectOption{Value: val, Text: label, Selected: val == cur})
		}
		return html.Select(html.SelectConfig{Name: f.Key, ID: id, Options: opts})
	}
	switch f.Type {
	case "enum":
		opts := []html.SelectOption{{Value: "", Text: "— Select —"}}
		for _, v := range f.Values {
			opts = append(opts, html.SelectOption{Value: v, Text: resTitle(v), Selected: v == cur})
		}
		return html.Select(html.SelectConfig{Name: f.Key, ID: id, Options: opts})
	case "text":
		return html.TextArea(html.TextAreaConfig{Name: f.Key, ID: id, Content: cur, Rows: 4})
	case "bool", "boolean":
		attrs := html.Attrs{}
		if resTruthy(cur) {
			attrs["checked"] = "checked"
		}
		return html.Input(html.InputConfig{Type: "checkbox", Name: f.Key, ID: id, ExtraAttrs: attrs})
	default:
		return html.Input(html.InputConfig{Type: resInputType(f.Type), Name: f.Key, ID: id, Value: cur})
	}
}

// resInputType maps a field type to an <input type=...>.
func resInputType(t string) string {
	switch t {
	case "int", "integer", "float", "decimal":
		return "number"
	case "date":
		return "date"
	case "timestamp", "datetime":
		return "datetime-local"
	case "email":
		return "email"
	default:
		return "text"
	}
}

func resToday() string {
	return time.Now().Format("2006-01-02")
}

func resButtonVariant(v string) ui.ButtonVariant {
	switch v {
	case "primary":
		return ui.ButtonPrimary
	case "danger":
		return ui.ButtonDanger
	case "ghost":
		return ui.ButtonGhost
	default:
		return ui.ButtonSecondary
	}
}

// ----- formatting helpers ---------------------------------------------------

func resCell(v any) string {
	if v == nil {
		return ""
	}
	switch t := v.(type) {
	case string:
		return t
	case bool:
		if t {
			return "true"
		}
		return "false"
	default:
		return fmt.Sprint(v)
	}
}

// resGet reads a row value by snake_case key, falling back to the camelCase
// form the JSON API serializes (requires_prescription → requiresPrescription).
func resGet(row map[string]any, key string) any {
	if v, ok := row[key]; ok {
		return v
	}
	return row[resCamel(key)]
}

func resCamel(s string) string {
	var b strings.Builder
	up := false
	for _, r := range s {
		if r == '_' {
			up = true
			continue
		}
		if up {
			if r >= 'a' && r <= 'z' {
				r = r - 32
			}
			up = false
		}
		b.WriteRune(r)
	}
	return b.String()
}

func resMuted() render.HTML {
	return render.Tag("span", map[string]string{"class": "mrd-muted"}, render.Text("—"))
}

func resNumeric(t string) bool {
	switch t {
	case "int", "integer", "float", "decimal":
		return true
	}
	return false
}

func resTruthy(s string) bool {
	switch strings.ToLower(s) {
	case "true", "1", "yes", "on", "t":
		return true
	}
	return false
}

func resFormat(f ResField, raw any, rel map[string]map[string]string) render.HTML {
	val := resCell(raw)
	if labels, ok := rel[f.Key]; ok {
		if val == "" {
			return resMuted()
		}
		if l, ok := labels[val]; ok {
			return render.Text(l)
		}
		return render.Text(val)
	}
	switch f.Type {
	case "bool", "boolean":
		if resTruthy(val) {
			return ui.StatusBadge(ui.StatusBadgeConfig{Label: "Yes", Variant: ui.StatusSuccess})
		}
		return ui.StatusBadge(ui.StatusBadgeConfig{Label: "No", Variant: ui.StatusNeutral})
	}
	if val == "" {
		return resMuted()
	}
	switch f.Type {
	case "enum":
		return ui.StatusBadge(ui.StatusBadgeConfig{Label: resTitle(val), Variant: resEnumVariant(val)})
	case "decimal", "float":
		return render.Text(resMoney(val))
	case "date":
		return render.Text(resDate(raw, val, "Jan 2, 2006"))
	case "timestamp", "datetime":
		return render.Text(resDate(raw, val, "Jan 2, 2006 3:04 PM"))
	}
	return render.Text(val)
}

// resDate renders a date/timestamp cleanly. DB drivers hand dates back as
// time.Time (whose default String() is the noisy "2006-01-02 15:04:05 -0700
// MST"), so format those directly; fall back to parsing common string layouts,
// then to trimming the time portion off an ISO-ish string.
func resDate(raw any, val, layout string) string {
	if t, ok := raw.(time.Time); ok {
		if t.IsZero() {
			return "—"
		}
		return t.Format(layout)
	}
	for _, l := range []string{
		time.RFC3339,
		"2006-01-02 15:04:05.999999999 -0700 MST",
		"2006-01-02 15:04:05 -0700 MST",
		"2006-01-02T15:04:05Z07:00",
		"2006-01-02 15:04:05",
		"2006-01-02",
	} {
		if parsed, err := time.Parse(l, val); err == nil {
			return parsed.Format(layout)
		}
	}
	if i := strings.IndexByte(val, 'T'); i > 0 {
		return val[:i]
	}
	if i := strings.IndexByte(val, ' '); i > 0 {
		return val[:i]
	}
	return val
}

func resTitle(s string) string {
	s = strings.ReplaceAll(strings.ReplaceAll(s, "_", " "), "-", " ")
	parts := strings.Fields(s)
	for i, p := range parts {
		if p != "" {
			parts[i] = strings.ToUpper(p[:1]) + p[1:]
		}
	}
	return strings.Join(parts, " ")
}

func resEnumVariant(v string) ui.StatusVariant {
	switch strings.ToLower(v) {
	case "active", "paid", "succeeded", "completed", "open":
		return ui.StatusSuccess
	case "past_due", "pending", "trialing", "draft":
		return ui.StatusWarning
	case "canceled", "cancelled", "void", "failed", "refunded", "inactive":
		return ui.StatusNeutral
	}
	return ui.StatusInfo
}

func resMoney(s string) string {
	f, err := strconv.ParseFloat(s, 64)
	if err != nil {
		return s
	}
	neg := f < 0
	if neg {
		f = -f
	}
	whole := int64(f)
	cents := int64(math.Round((f - float64(whole)) * 100))
	if cents == 100 {
		whole++
		cents = 0
	}
	ws := strconv.FormatInt(whole, 10)
	var grp []string
	for len(ws) > 3 {
		grp = append([]string{ws[len(ws)-3:]}, grp...)
		ws = ws[:len(ws)-3]
	}
	grp = append([]string{ws}, grp...)
	out := "$" + strings.Join(grp, ",") + fmt.Sprintf(".%02d", cents)
	if neg {
		out = "-" + out
	}
	return out
}

func resCountLabel(total int, singular, title string) string {
	if total == 1 {
		return "1 " + singular
	}
	return fmt.Sprintf("%d %s", total, strings.ToLower(title))
}

func resEmptyDesc(custom string) string {
	if custom != "" {
		return custom
	}
	return "They will appear here once created."
}

// blueprintAuthError reads the ?error= code an auth redirect sets and returns a
// human message for an auth card's alert slot, or "" when there's no error. The
// auth battery redirects a failed form login back to the login page with this
// code instead of rendering a raw JSON error body.
func blueprintAuthError(ctx context.Context) render.HTML {
	switch appui.QueryFromContext(ctx).Get("error") {
	case "":
		return ""
	case "invalid_credentials":
		return render.Text("Invalid email or password.")
	case "credentials_required":
		return render.Text("Enter your email and password.")
	case "rate_limit":
		return render.Text("Too many attempts — please wait a moment and try again.")
	case "email_taken", "user_exists", "duplicate":
		return render.Text("That email is already registered.")
	default:
		return render.Text("Sorry, something went wrong. Please try again.")
	}
}

// ----- dashboard data binding (stat_card / charts with source) --------------

// blueprintStatValue computes a single metric over an entity for a stat_card:
// agg "count" (optionally filtered "field=value") or "sum" of a numeric field.
func blueprintStatValue(ctx context.Context, entity, agg, field, filterStr, format string) string {
	c, ok := blueprintResources[entity]
	if !ok || c.Crud == nil {
		return "—"
	}
	var filters []filter.ParsedFilter
	if filterStr != "" {
		if i := strings.IndexByte(filterStr, '='); i > 0 {
			filters = append(filters, filter.ParsedFilter{Field: filterStr[:i], Op: filter.OpEq, Value: filterStr[i+1:]})
		}
	}
	if agg == "sum" {
		rows, err := c.Crud.ListAll(ctx, framework.ListOptions{Filters: filters, Limit: 100000})
		if err != nil {
			return "—"
		}
		var total float64
		for _, r := range rows {
			f, _ := strconv.ParseFloat(resCell(resGet(r, field)), 64)
			total += f
		}
		if format == "money" {
			return resMoney(strconv.FormatFloat(total, 'f', 2, 64))
		}
		return blueprintFmtNum(total)
	}
	n, err := c.Crud.CountAll(ctx, framework.ListOptions{Filters: filters})
	if err != nil {
		return "—"
	}
	return strconv.Itoa(n)
}

type blueprintKV struct {
	k string
	v int
}

func blueprintGroupCounts(ctx context.Context, entity, groupBy string) []blueprintKV {
	c, ok := blueprintResources[entity]
	if !ok || c.Crud == nil {
		return nil
	}
	rows, err := c.Crud.ListAll(ctx, framework.ListOptions{Limit: 100000})
	if err != nil {
		return nil
	}
	order := []string{}
	m := map[string]int{}
	for _, r := range rows {
		key := resCell(resGet(r, groupBy))
		if key == "" {
			key = "—"
		}
		if _, seen := m[key]; !seen {
			order = append(order, key)
		}
		m[key]++
	}
	out := make([]blueprintKV, 0, len(order))
	for _, k := range order {
		out = append(out, blueprintKV{k, m[k]})
	}
	return out
}

func blueprintGroupBars(ctx context.Context, entity, groupBy string) []ui.BarChartBar {
	counts := blueprintGroupCounts(ctx, entity, groupBy)
	bars := make([]ui.BarChartBar, 0, len(counts))
	for _, kv := range counts {
		bars = append(bars, ui.BarChartBar{Label: resTitle(kv.k), Value: float64(kv.v)})
	}
	return bars
}

func blueprintGroupSlices(ctx context.Context, entity, groupBy string) []ui.PieSlice {
	counts := blueprintGroupCounts(ctx, entity, groupBy)
	slices := make([]ui.PieSlice, 0, len(counts))
	for _, kv := range counts {
		slices = append(slices, ui.PieSlice{Label: resTitle(kv.k), Value: float64(kv.v)})
	}
	return slices
}

func blueprintFmtNum(f float64) string {
	if f == float64(int64(f)) {
		return strconv.FormatInt(int64(f), 10)
	}
	return strconv.FormatFloat(f, 'f', 2, 64)
}
