package jcs

import (
	"bytes"
	"encoding/hex"
	"encoding/json"
	"math"
	"math/big"
	"os"
	"path/filepath"
	"strconv"
	"strings"
	"testing"
	"unicode/utf16"
)

// ─── Gate A: RFC 8785 reference suite (cyberphone testdata) ─────────

// TestReferenceSuite runs the six official input/expected pairs from
// the RFC 8785 reference implementation repository (testdata/vectors,
// see testdata/README.md for provenance), byte-for-byte against both
// the JSON and the hex forms.
func TestReferenceSuite(t *testing.T) {
	names := []string{"arrays", "french", "structures", "unicode", "values", "weird"}
	for _, name := range names {
		t.Run(name, func(t *testing.T) {
			in, err := os.ReadFile(filepath.Join("testdata", "vectors", "input", name+".json"))
			if err != nil {
				t.Fatal(err)
			}
			want, err := os.ReadFile(filepath.Join("testdata", "vectors", "output", name+".json"))
			if err != nil {
				t.Fatal(err)
			}
			want = bytes.TrimSuffix(want, []byte("\n"))

			got, err := CanonicalizeJSON(in)
			if err != nil {
				t.Fatalf("CanonicalizeJSON: %v", err)
			}
			if !bytes.Equal(got, want) {
				t.Errorf("canonical bytes differ\n got: %q\nwant: %q", got, want)
			}

			// The outhex file pins the same expectation as hex bytes;
			// check it independently so the two fixtures can't drift.
			hexRaw, err := os.ReadFile(filepath.Join("testdata", "vectors", "outhex", name+".txt"))
			if err != nil {
				t.Fatal(err)
			}
			var hexBytes []byte
			for _, field := range strings.Fields(string(hexRaw)) {
				b, err := hex.DecodeString(field)
				if err != nil {
					t.Fatalf("bad hex field %q: %v", field, err)
				}
				hexBytes = append(hexBytes, b...)
			}
			if !bytes.Equal(got, hexBytes) {
				t.Errorf("canonical bytes differ from outhex\n got: %x\nwant: %x", got, hexBytes)
			}
		})
	}
}

// TestRFC8785AppendixB runs the number table transcribed from RFC 8785
// Appendix B (testdata/rfc8785-appendixb.txt). NaN and ±Infinity rows
// are rejection cases covered in TestRejectedNumbers.
func TestRFC8785AppendixB(t *testing.T) {
	runNumberVectors(t, filepath.Join("testdata", "rfc8785-appendixb.txt"))
}

// TestES6NumberVectors runs the committed slice of the reference
// implementation's deterministic 100M-value sequence (5,000 lines
// generated by the reference numgen, see testdata/README.md): the 168
// static edge cases, then 2000 consecutive doubles from the minimum
// normal, then random doubles.
func TestES6NumberVectors(t *testing.T) {
	runNumberVectors(t, filepath.Join("testdata", "es6-numbers.txt"))
}

func runNumberVectors(t *testing.T, path string) {
	t.Helper()
	raw, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	lines := strings.Split(strings.TrimRight(string(raw), "\n"), "\n")
	for i, line := range lines {
		hexStr, want, ok := strings.Cut(line, ",")
		if !ok {
			t.Fatalf("%s:%d: malformed line %q", path, i+1, line)
		}
		bits, ok := new(big.Int).SetString(hexStr, 16)
		if !ok {
			t.Fatalf("%s:%d: bad hex %q", path, i+1, hexStr)
		}
		f := math.Float64frombits(bits.Uint64())
		if got := formatNumber(f); got != want {
			t.Errorf("%s:%d: formatNumber(%s = %v):\n got %q\nwant %q", path, i+1, hexStr, f, got, want)
		}
		// The same value must survive the full public path: a JSON
		// literal parsed and re-serialized canonically. 'g' formatting
		// of subnormals can underflow on parse; those skip this half.
		lit := strconv.FormatFloat(f, 'g', -1, 64)
		if _, err := strconv.ParseFloat(lit, 64); err != nil {
			continue
		}
		got2, err := CanonicalizeJSON([]byte(lit))
		if err != nil {
			t.Fatalf("%s:%d: CanonicalizeJSON(%q): %v", path, i+1, lit, err)
		}
		if string(got2) != want {
			t.Errorf("%s:%d: CanonicalizeJSON(%q):\n got %q\nwant %q", path, i+1, lit, got2, want)
		}
	}
}

// TestRFC8785SortExample pins the property-sorting example from
// RFC 8785 §3.2.3: the expected order of the sample keys.
func TestRFC8785SortExample(t *testing.T) {
	keys := []string{"\r", "1", "", "ö", "€", "\U0001F600", "דּ"}
	sortKeysByUTF16(keys)
	want := []string{"\r", "1", "", "ö", "€", "\U0001F600", "דּ"}
	for i := range keys {
		if keys[i] != want[i] {
			t.Fatalf("position %d: got %q want %q", i, keys[i], want[i])
		}
	}
}

// TestUTF16SortDivergence proves the sort is UTF-16 code-unit order, not
// UTF-8 byte order: U+10000+ keys (surrogate pairs 0xD800–0xDBFF) sort
// BEFORE U+E000–U+FFFF even though their UTF-8 bytes sort after.
func TestUTF16SortDivergence(t *testing.T) {
	if utf16.Encode([]rune("😀"))[0] != 0xD83D {
		t.Fatal("test premise broken")
	}
	keys := []string{"\ue000", "😀"}
	sortKeysByUTF16(keys)
	if keys[0] != "😀" {
		t.Fatalf("UTF-16 order must put the emoji first, got %q", keys[0])
	}
	// Via the full parser: keys are emitted in sorted position.
	in := []byte("{\"\uE000\":\"after-bytes\",\"😀\":\"first-bytes\"}")
	got, err := CanonicalizeJSON(in)
	if err != nil {
		t.Fatal(err)
	}
	want := "{\"😀\":\"first-bytes\",\"\uE000\":\"after-bytes\"}"
	if string(got) != want {
		t.Fatalf("got %s want %s", got, want)
	}
}

// ─── Gate B: independent-implementation corpus ──────────────────────

// TestNodeCorpus replays the corpus canonicalized by the committed
// Node reference (the RFC 8785 Appendix A construction: key-sorted
// JSON.stringify under Node 22, sharing no code with this package).
// Regenerate with `node testdata/gen-corpus.mjs` — never edit
// corpus-expected.txt by hand.
func TestNodeCorpus(t *testing.T) {
	rawCorpus, err := os.ReadFile(filepath.Join("testdata", "corpus.json"))
	if err != nil {
		t.Fatal(err)
	}
	rawExpected, err := os.ReadFile(filepath.Join("testdata", "corpus-expected.txt"))
	if err != nil {
		t.Fatal(err)
	}
	expected := strings.Split(strings.TrimRight(string(rawExpected), "\n"), "\n")

	// Walk the corpus array with the parser to get per-element slices,
	// so each value is exercised exactly as standalone JSON input.
	var elems [][]byte
	p := &parser{data: rawCorpus}
	p.skipWS()
	if p.pos >= len(p.data) || p.data[p.pos] != '[' {
		t.Fatal("corpus.json is not an array")
	}
	p.pos++
	p.skipWS()
	for {
		if p.pos < len(p.data) && p.data[p.pos] == ']' {
			break
		}
		start := p.pos
		if _, err := p.parseValue(1); err != nil {
			t.Fatalf("corpus element %d: %v", len(elems), err)
		}
		elems = append(elems, p.data[start:p.pos])
		p.skipWS()
		if p.pos < len(p.data) && p.data[p.pos] == ',' {
			p.pos++
			p.skipWS()
		}
	}
	if len(elems) != len(expected) {
		t.Fatalf("corpus has %d values but %d expected lines", len(elems), len(expected))
	}
	for i, el := range elems {
		got, err := CanonicalizeJSON(el)
		if err != nil {
			t.Fatalf("corpus[%d]: %v", i, err)
		}
		wantBytes, err := hex.DecodeString(expected[i])
		if err != nil {
			t.Fatalf("expected[%d]: bad hex: %v", i, err)
		}
		if !bytes.Equal(got, wantBytes) {
			t.Errorf("corpus[%d] differs from Node reference\n got: %s\nwant: %s", i, got, wantBytes)
		}
	}
}

// ─── Canonicalize (Go values) ───────────────────────────────────────

func TestCanonicalizeValues(t *testing.T) {
	cases := []struct {
		name string
		in   any
		want string
	}{
		{"map", map[string]any{"b": 1, "a": 2}, `{"a":2,"b":1}`},
		{"nested", map[string]any{"z": map[string]any{"b": true, "a": false}}, `{"z":{"a":false,"b":true}}`},
		{"slice", []any{3, 1, 2}, `[3,1,2]`},
		{"empty obj/slice", []any{map[string]any{}, []any{}}, `[{},[]]`},
		{"string escapes", map[string]string{"k": "a\"b\\c\n\t\r\b\fd"}, `{"k":"a\"b\\c\n\t\r\b\fd"}`},
		{"control escapes", map[string]string{"k": "\x01"}, "{\"k\":\"\\u0001\"}"},
		{"slash literal", map[string]string{"k": "a/b"}, `{"k":"a/b"}`},
		{"del literal", map[string]string{"k": "a\x7f"}, "{\"k\":\"a\x7f\"}"},
		{"number formats", map[string]any{
			"a": 1e21, "b": 1e-7, "c": 100.0, "d": -0.0,
			"e": json.Number("333333333.33333329"),
		}, `{"a":1e+21,"b":1e-7,"c":100,"d":0,"e":333333333.3333333}`},
		{"struct order irrelevant", struct {
			B int `json:"b"`
			A int `json:"a"`
		}{1, 2}, `{"a":2,"b":1}`},
		{"nil", nil, `null`},
		{"bools", []any{true, false}, `[true,false]`},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			got, err := Canonicalize(tc.in)
			if err != nil {
				t.Fatalf("Canonicalize: %v", err)
			}
			if string(got) != tc.want {
				t.Errorf("\n got %s\nwant %s", got, tc.want)
			}
		})
	}
}

// ─── Rejected inputs ────────────────────────────────────────────────

func TestRejectedJSON(t *testing.T) {
	cases := []struct {
		name string
		in   string
		want string // substring of the expected error
	}{
		{"duplicate keys", `{"a":1,"a":2}`, "duplicate object key"},
		{"duplicate nested", `{"x":{"a":1,"a":2}}`, "duplicate object key"},
		{"duplicate after ws", `{ "a" : 1 , "a" : 2 }`, "duplicate object key"},
		{"lone high surrogate", `"\ud800"`, "unpaired high surrogate"},
		{"lone low surrogate", `"a\udead"`, "unpaired low surrogate"},
		{"high surrogate then non-escape", `"\ud800x"`, "unpaired high surrogate"},
		{"surrogate then bad low", `"\ud800\ud800"`, "unpaired high surrogate"},
		{"invalid utf8 raw", "\"a\xffb\"", "invalid UTF-8"},
		{"raw control in string", "\"a\x01b\"", "raw control character"},
		{"raw tab in string", "\"a\tb\"", "raw control character"},
		{"leading zero", `{"a":01}`, "expected ',' or '}'"},
		{"plus number", `{"a":+1}`, "unexpected character"},
		{"bare dot", `{"a":.5}`, "unexpected character"},
		{"trailing dot", `{"a":1.}`, "digit required"},
		{"dot no digits", `{"a":1.e3}`, "digit required"},
		{"bare exponent", `{"a":1e}`, "digit required"},
		{"e plus no digits", `{"a":1e+}`, "digit required"},
		{"minus only", `{"a":-}`, "invalid number"},
		{"overflow to inf", `{"a":1e999}`, "overflows to Infinity"},
		{"negative overflow", `{"a":-1e999}`, "overflows to Infinity"},
		{"hex garbage", `0x10`, "unexpected trailing data"},
		{"empty input", ``, "unexpected end of input"},
		{"whitespace only", `   `, "unexpected end of input"},
		{"trailing garbage", `{"a":1} x`, "unexpected trailing data"},
		{"trailing comma obj", `{"a":1,}`, "expected object key string"},
		{"trailing comma arr", `[1,]`, "unexpected character"},
		{"unterminated obj", `{"a":1`, "unterminated object"},
		{"unterminated arr", `[1`, "unterminated array"},
		{"unterminated string", `"abc`, "unterminated string"},
		{"bad literal", `tru`, "invalid literal"},
		{"NaN literal", `NaN`, "unexpected character"},
		{"Infinity literal", `Infinity`, "unexpected character"},
		{"no colon", `{"a" 1}`, "expected ':'"},
		{"single quotes", `'a'`, "unexpected character"},
		{"comment", `{"a":1}/*x*/`, "unexpected trailing data"},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			_, err := CanonicalizeJSON([]byte(tc.in))
			if err == nil {
				t.Fatalf("CanonicalizeJSON(%q) succeeded, want error containing %q", tc.in, tc.want)
			}
			if !strings.Contains(err.Error(), tc.want) {
				t.Errorf("CanonicalizeJSON(%q) error %q, want substring %q", tc.in, err, tc.want)
			}
		})
	}
}

func TestRejectedNumbers(t *testing.T) {
	for _, tc := range []struct {
		name string
		f    float64
	}{
		{"NaN", math.NaN()},
		{"+Inf", math.Inf(1)},
		{"-Inf", math.Inf(-1)},
	} {
		t.Run(tc.name, func(t *testing.T) {
			if _, err := Canonicalize(tc.f); err == nil {
				t.Fatalf("Canonicalize(%s) succeeded, want error", tc.name)
			}
		})
	}
	// RFC 8785 Appendix B notes (3): NaN/Infinity bit patterns are not
	// valid JSON and must never canonicalize.
	if got := formatNumber(math.Float64frombits(0x7fffffffffffffff)); got != "NaN" {
		t.Errorf("formatNumber(NaN-bits) = %q, want NaN placeholder (unreachable guard)", got)
	}
}

func TestUnderflowCanonicalizesToZero(t *testing.T) {
	// ECMAScript: JSON.parse("1e-400") → 0. Same rule here.
	for _, lit := range []string{"1e-400", "-1e-400", "5e-325"} {
		got, err := CanonicalizeJSON([]byte(lit))
		if err != nil {
			t.Fatalf("CanonicalizeJSON(%q): %v", lit, err)
		}
		if string(got) != "0" {
			t.Errorf("CanonicalizeJSON(%q) = %s, want 0", lit, got)
		}
	}
}

func TestDepthLimit(t *testing.T) {
	deep := strings.Repeat("[", 600) + strings.Repeat("]", 600)
	if _, err := CanonicalizeJSON([]byte(deep)); err == nil || !strings.Contains(err.Error(), "nesting") {
		t.Errorf("depth 600: err = %v, want nesting error", err)
	}
	ok := strings.Repeat("[", 100) + strings.Repeat("]", 100)
	if _, err := CanonicalizeJSON([]byte(ok)); err != nil {
		t.Errorf("depth 100: %v", err)
	}
}

// TestWhitespaceInsensitivity: canonical form is a function of the
// parsed value, not the input layout.
func TestWhitespaceInsensitivity(t *testing.T) {
	a := []byte("{ \"b\" : [ 1 , 2 ] ,\n\"a\" : { } }")
	b := []byte(`{"b":[1,2],"a":{}}`)
	ca, err := CanonicalizeJSON(a)
	if err != nil {
		t.Fatal(err)
	}
	cb, err := CanonicalizeJSON(b)
	if err != nil {
		t.Fatal(err)
	}
	if !bytes.Equal(ca, cb) {
		t.Errorf("layouts differ canonically:\n%s\n%s", ca, cb)
	}
	if string(ca) != `{"a":{},"b":[1,2]}` {
		t.Errorf("got %s", ca)
	}
}

func TestNumberLiteralFormsCollapse(t *testing.T) {
	// Same double, different literals, one canonical form.
	lits := []string{"1E2", "1e2", "100", "100.0", "100.00", "1e+2", "1.0e2"}
	for _, lit := range lits {
		got, err := CanonicalizeJSON([]byte(lit))
		if err != nil {
			t.Fatalf("CanonicalizeJSON(%q): %v", lit, err)
		}
		if string(got) != "100" {
			t.Errorf("CanonicalizeJSON(%q) = %s, want 100", lit, got)
		}
	}
}

func BenchmarkCanonicalizeCard(b *testing.B) {
	doc := map[string]any{
		"name":         "Test Agent",
		"description":  "does things",
		"version":      "1.0.0",
		"capabilities": map[string]bool{"streaming": false, "pushNotifications": false},
		"skills":       []any{map[string]any{"id": "mcp", "name": "MCP tools"}},
		"defaultInputModes": []string{
			"text/plain",
		},
	}
	b.ResetTimer()
	for b.Loop() {
		if _, err := Canonicalize(doc); err != nil {
			b.Fatal(err)
		}
	}
}

// TestTieToEvenSubnormal: 2.5e-324 is exactly half the minimum positive
// subnormal; IEEE 754 round-half-to-even selects the subnormal (5e-324),
// matching ECMAScript Number("2.5e-324").
func TestTieToEvenSubnormal(t *testing.T) {
	got, err := CanonicalizeJSON([]byte("2.5e-324"))
	if err != nil {
		t.Fatal(err)
	}
	if string(got) != "5e-324" {
		t.Errorf("CanonicalizeJSON(2.5e-324) = %s, want 5e-324", got)
	}
}
